### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#1]
The initial work to support SSL connections is there (nginx proxy vhost). Dynamically creating the vhost is more work than it should be. Will work to see how to do this better with `debops.nginx`.

**Comment by tobeycodes** [comment]
@carlalexander have you considered putting Pound in front on Varnish?

**Comment by carlalexander** [comment]
No, I had not! I wasn't really thinking about load balancers yet, but looking into it. It could solve the problem quite nicely as well.

**Comment by tobeycodes** [comment]
Relevant: http://wptavern.com/speed-up-your-wordpress-site-with-pound-varnish-nginx-and-mod_pagespeed

**Comment by carlalexander** [comment]
Pound looks like a real good alternative if I can't get a simple setup going using `debops.nginx`. The other part of the equation is the certificate management. That's the trickier one.

DebOps has a thorough certificate management through `debops.pki`. The system is pretty complex. I disabled it to prevent conflicts, but we'd need to turn it on for this (I think). I'll have to work on familiarizing myself with all of it.

The good news is that it puts in a real good spot to support "[let's encrypt](https://letsencrypt.org/)" when it comes out this fall. That's something that's pretty important to me.

Other thing to test out is using the CloudFlare SSL instead of our own certificate.

**Comment by carlalexander** [comment]
I helped someone do this by hand today. Here are some notes from the whole thing. Here's a sample nginx config, but debops should handle the whole thing itself.

``` conf
server {
  listen [::]:80 ipv6only=off;

  server_name example.wordpress.com;

  return 301 https://$host$request_uri;
}

server {
  listen [::]:443 default_server ssl spdy ipv6only=off;

  server_name example.wordpress.com;

  ssl_certificate /etc/ssl/example.wordpress.com.crt;
  ssl_certificate_key /etc/ssl/example.wordpress.com.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4;

  access_log /var/log/nginx/varnish.example.wordpress.com_access.log;
  error_log /var/log/nginx/varnish.example.wordpress.com_error.log;

  client_max_body_size  32M;

  location / {
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 80;
    proxy_set_header Host $host;
    proxy_pass http://varnish;
  }
}
```

You also run into issues on the WordPress side of things. The codex discusses all of it on the "[Admin Over SSL](https://codex.wordpress.org/Administration_Over_SSL)" page. The important take aways are that you need:
- `FORCE_SSL_ADMIN` set to `true` to turn on wp-admin SSL
- `$_SERVER['HTTPS']='on';` to prevent infinite loops

This last point is important. PHP isn't receiving an HTTPS request per say. You need to fake it. The codex suggest to do this in `wp-config.php`, but this should be handled at the nginx level. 

You can't use `SetEnv HTTPS on` as you do in Apache. That's because php-fpm handles all of the `$_SERVER` on it's own. You can use a `fastcgi_param` though. It's discussed in [this blog post](https://ma.ttias.be/setting-https-server-variables-in-php-fpm-with-nginx/).

**Comment by drybjed** [comment]
@carlalexander Have you looked at `debops.pki` yet? `debops.nginx` has full support for HTTPS using it, you don't need to handle certificates by yourself. If it's still confusing, come over to IRC and I'll try explaining. :)

**Comment by carlalexander** [comment]
I haven't looked at it yet. Someone really wanted it NOW so helped him out.

**Comment by carlalexander** [comment]
Did a test run at this tonight. `debops.pki` didn't seem to like the self-signed certificate I created. It seems to modify it when I ran the standard playbook. This caused nginx to choke. I had to copy over the original certificate for it to work.

Creating the reverse proxy with or without SSL is problematic with `debops.nginx`. I need to copy a lot of logic from the default template and handle it myself. It'd be better if `debops.nginx` had a trimmed down template that could handle this. Right now, the default template seems to require a bit too much.

I managed to create a dynamic config for the WordPress backend to handle `HTTPS` server variable. That worked fine. I'll commit it after a bit more testing.

**Comment by drybjed** [comment]
So, it looks like Ubuntu team will try and backport the fix to Trusty. In the meantime, you could try switching the `mariadb_server_flavor` to `mysql`, it should work fine then. After you test it, it can be added to the flavor map to fix the issue on Trusty for the time being.

**Comment by drybjed** [comment]
@carlalexander I would need to know a bit more about how you created the self-signed certs and how they were used with `debops.pki`. I admit that role is a bit overengineered right now and the whole process could be designed better. However with default configuration you should at least get a working certs as long as your domain is set correctly, without anything required on your part.

If you tried to replace automatically generated certificates with your own by pasting them over, it will definitely not work. The way to add your own certificates is to add then with a different name alongside autogenerated ones and either point various roles to them, for example using:

```
nginx_pki_crt: 'certs/your.domain.com.crt'
nginx_pki_key: 'private/your.domain.com.key'
```

or, by setting the new certificate name as default, in which case the various symlinks will be changed to point to your certs.

A separate nginx template just for proxy seems to be a good idea. Could you send me / post / PR a trimmed down version you would like to see? Probably removing the SSL code and leaving only HTTP should be enough, so that `haproxy` / `varnish` can terminate SSL instead of `nginx`. Perhaps role could even be modified to allow changing the default template type so `nginx` can be set up either at frontend or at backend...

**Comment by carlalexander** [comment]
Varnish can't terminate the SSL. That's why we need the reverse proxy to handle it. I'll toy with `debops.nginx` to see what's needed to do a simpler config. Ideally, I think it's just a question of reducing the required values on the default template.

As for `debops.pki`, I'm not sure what was going on, but it seemed to add intermidiary certs into self-signed certificate I'd put in `secret`. I didn't do more investigation than that. It's possible it's a configuration issue since the only thing I did is put the `.crt` and `.key` files in `secret`. I let `debops.pki` take care of the rest.

I'll try to get back to this later this week so I'll come on IRC and/or update here.

**Comment by drybjed** [comment]
`debops.pki` makes full blown CA chain, from a root CA certificate, several intermediates (first to allow you to move the root CA key offline while still being able to create new intermediate CAs, and second intermediate CA to sign the certs themselves). I imagine if you put your certs in the wrong place it could mess them up... We can talk about it on IRC. :)

**Comment by carlalexander** [comment]
Support for SSL is in! Scores very well when I tested it on my site.

![image](https://cloud.githubusercontent.com/assets/654684/9457316/6a4b3ae8-4aaf-11e5-9691-64dd01eadd6a.png)

Ran into a few issues migrating my site. For example, you need to upgrade legacy URLs in the database. You can cover most of them using the following queries (found in [this article](https://css-tricks.com/moving-to-https-on-wordpress/)):

``` sql
UPDATE wp_posts 
SET    post_content = ( Replace (post_content, 'src="http://', 'src="//') )
WHERE  Instr(post_content, 'jpeg') > 0 
        OR Instr(post_content, 'jpg') > 0 
        OR Instr(post_content, 'gif') > 0 
        OR Instr(post_content, 'png') > 0;
```

``` sql
UPDATE wp_posts 
SET   post_content = ( Replace (post_content, "src='http://", "src='//") )
WHERE  Instr(post_content, 'jpeg') > 0 
        OR Instr(post_content, 'jpg') > 0 
        OR Instr(post_content, 'gif') > 0 
        OR Instr(post_content, 'png') > 0;
```

``` sql
UPDATE wp_postmeta 
SET meta_value=(REPLACE (meta_value, 'iframe src="http://','iframe src="//'));
```

Next up is doing a wiki page for all of this.

**Comment by ypid** [comment]
@carlalexander TLS support works nicely but it is not enabled by default and I did not see it mentioned in the docs. I just implemented support to serve WordPress via [HTTP and HTTPS](https://github.com/ypid/debops-wordpress/commit/0d2fec2fc68437e1bda327f83e9fd79b0d0d2bad) simultaneously. I would suggest that we enable that by default so that admins/users login to wp via HTTPS.

**Comment by carlalexander** [comment]
I was going to look at moving to the proxy template tonight. Finishing up the security docs right now. Why not default `wordpress_redirect_to_ssl` to `False` instead of `undefined`?

**Comment by carlalexander** [comment]
I'll look into implementing some of the stuff in that commit tonight.

**Comment by ypid** [comment]
> Why not default wordpress_redirect_to_ssl to False instead of undefined?

Done :smile:

**Comment by carlalexander** [comment]
I'm looking at closing this ticket tonight. I'll probably implement this for you as well as the `proxy` template. :wink:

**Comment by ypid** [comment]
I already did that …
https://github.com/ypid/debops-wordpress/tree/rework
Do you want to merge it right way? I can open a second PR for my other stuff (plugin management :smile: ) later?

**Comment by carlalexander** [comment]
I know, I saw! Can you break out the changes into its own PR? I know you've been doing a lot of various changes everywhere.

**Comment by carlalexander** [comment]
Alright, documentation is done and can be [found in the wiki](https://github.com/carlalexander/debops-wordpress/wiki/How-to-secure-your-WordPress-site). Once we change to the `proxy` template and add the redirect option, I'll consider this issue done.

**Comment by ypid** [comment]
I could split my rework branch but I would like to avoid that. The other changes are more in the background. And all breaking changes are documented. Could you reconsider this and maybe review my current rework please? #29

**Comment by carlalexander** [comment]
Yep, but, in the future, I'd rather if we didn't do massive PRs like that so we can track things a bit more easily. If you want to add plugin management, create an issue and a PR just for that. :smile:

I'll close this then and work through the PR.

**Comment by tobeycodes** [comment]
Would be cool to support this when it's released properly https://letsencrypt.org/

**Comment by carlalexander** [comment]
For sure! It'll probably just end up being a guide.

**Comment by ypid** [comment]
There is also an interest in the DebOps project to support this. I might look into supporting https://letsencrypt.org/ somehow using the `debops.pki` role in the near future.

**Comment by carlalexander** [comment]
That'd be amazing.
