### ISSUE TITLE
WooCommerce Support

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#10]
I think it would make sense to support WooCommerce out of the box

http://docs.woothemes.com/document/configuring-caching-plugins/

**Comment by carlalexander** [comment]
Right, I debated doing it as I saw it elsewhere during my research. The issue that stayed my hand is what about other plugins? Should I just keep adding rules to accommodate each one.

The Varnish role allows for custom rules to be added. I'm wondering if creating a cookbook to show how to add these additional rules might not be a better approach.

I'm just not sure yet what the better solution is.

**Comment by tobeycodes** [comment]
I think I prefer the way you suggested. Don't bloat something and assume it's needed by everyone

**Comment by maximejobin** [comment]
I think it should be added as a plugin and not by default.

**Comment by carlalexander** [comment]
So I moved the Varnish configs so that they can be overridden. If you wanted to add the WooCommerce config, you'd just need to change the custom host configuration to:

``` yml
wordpress_varnish_vcl_recv_conditions:
  'req.http.Cookie ~ "wordpress_" || req.http.Cookie ~ "comment_"': 'return (pass);'
  'req.url ~ "wp-(admin|cron|login)" || req.url ~ "preview=true" || req.url ~ "xmlrpc.php"': 'return (pass);'
  'req.url ~ "^/(cart|my-account|checkout|addons)" || req.url ~ "\?add-to-cart="': 'return (pass);'
```

This won't mean much unless you've used Ansible before, but I'll do a cookbook for custom Varnish configurations.

**Comment by NicoleGeissinger** [comment]
+1 to your thoughts Carl. I feel offering something out of the box that is so site specific is not the way to go. Flexibility to configure support for a plugin like woocommerce is best.

**Comment by carlalexander** [comment]
Yeah, that's going to be the plan for now @colegeissinger. The immediate goal is to do this and build documentation. We can look into automating some specific setup types in the future.

**Comment by carlalexander** [comment]
Finally, got to making a [cookbook for Varnish](https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-Varnish). There's a section for WooCommerce in there with the default Varnish rules for WooCommerce. I've never built a WooCommerce site so I can't do more testing to see if there's anything else to add.
