### ISSUE TITLE
16.04 Ubuntu Fail2Ban Error

### ISSUE THREAD

**Issue by matthew6688** [carlalexander/debops-wordpress#100]
I switch to newest Ubuntu server.

When i run debops wordpress command, it shows:

TASK [debops.fail2ban : Configure custom fail2ban actions] *********************
fatal: [yuekangsyringe.com]: FAILED! => {"failed": true, "msg": "lookup plugin (template_src) not found"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/ringse/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
yuekangsyringe.com         : ok=20   changed=0    unreachable=0    failed=1

**Comment by matthew6688** [comment]
More details:

`TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<yuekangsyringe> ESTABLISH SSH CONNECTION FOR USER: None
<yuekangsyringe> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r yuekangsyringe '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472703604.33-43606929640737 `" && echo ansible-tmp-1472703604.33-43606929640737="` echo $HOME/.ansible/tmp/ansible-tmp-1472703604.33-43606929640737 `" ) && sleep 0'"'"''
failed: [yuekangsyringe.com](item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [yuekangsyringe.com]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}

RUNNING HANDLER [debops.fail2ban : Restart fail2ban] ***************************
<yuekangsyringe.com> ESTABLISH SSH CONNECTION FOR USER: None
<yuekangsyringe.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r yuekangsyringe.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472703604.86-62656277307066`" && echo ansible-tmp-1472703604.86-62656277307066="`echo $HOME/.ansible/tmp/ansible-tmp-1472703604.86-62656277307066`" ) && sleep 0'"'"''
<yuekangsyringe.com> PUT /var/folders/3k/qjrv5lss4gbglbwvhchkncz00000gn/T/tmpJB5cm6 TO /var/local/ringse/.ansible/tmp/ansible-tmp-1472703604.86-62656277307066/service
<yuekangsyringe.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r '[yuekangsyringe.com]'
<yuekangsyringe.com> ESTABLISH SSH CONNECTION FOR USER: None
<yuekangsyringe.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r -tt yuekangsyringe.com '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qzptczcvnvwtpokwxjpomevmqeifscbb; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /var/local/ringse/.ansible/tmp/ansible-tmp-1472703604.86-62656277307066/service; rm -rf "/var/local/ringse/.ansible/tmp/ansible-tmp-1472703604.86-62656277307066/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [yuekangsyringe.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": null, "name": "fail2ban", "pattern": null, "runlevel": "default", "sleep": null, "state": "restarted"}, "module_name": "service"}, "msg": "Job for fail2ban.service failed because the control process exited with error code. See \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}`

**Comment by drybjed** [comment]
The `fail2ban` is most likely misconfigured at this point because Ansible couldn't finish configuring it. Make sure that you have installed the `debops` package from PyPI, using:

```
pip install debops
```

Alternatively, Ansible is missing [custom lookup plugins](https://github.com/debops/debops-playbooks/tree/master/playbooks/lookup_plugins), you should make sure that they are available where Ansible can find them. This is configured via the `lookup_plugins` parameter in `ansible.cfg`.

**Comment by matthew6688** [comment]
Thank you for your reply, I really appreciated.

## **First,**

when i try pip install debops, below is the message:

RingsedeMacBook-Pro:~ ringse$ pip install debops
Requirement already satisfied (use --upgrade to upgrade): debops in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): netaddr in /Library/Python/2.7/site-packages (from debops)
Requirement already satisfied (use --upgrade to upgrade): argparse in /Library/Python/2.7/site-packages (from debops)
Requirement already satisfied (use --upgrade to upgrade): passlib in /Library/Python/2.7/site-packages (from debops)

**I think it is install correctly.**

## **Second,**

Regarding, lookup plugins, 

here is my ansible.cfg settings:

[defaults]
filter_plugins = /Users/ringse/debops-wordpress/ansible/filter_plugins:/usr/local/share/debops/debops-playbooks/playbooks/filter_plugins:/usr/share/ansible/filter_plugins
hostfile = /Users/ringse/debops-wordpress/inventory
roles_path = /Users/ringse/debops-wordpress/roles:/Users/ringse/debops-wordpress/ansible/roles:/usr/local/share/debops/debops-playbooks/playbooks/../roles:/usr/local/share/debops/debops-playbooks/playbooks/roles:/etc/ansible/roles
connection_plugins = /Users/ringse/debops-wordpress/ansible/connection_plugins:/usr/local/share/debops/debops-playbooks/playbooks/connection_plugins:/usr/share/ansible/connection_plugins
library = /Users/ringse/debops-wordpress/ansible/library:/usr/local/share/debops/debops-playbooks/playbooks/library:/usr/share/ansible/library
vars_plugins = /Users/ringse/debops-wordpress/ansible/vars_plugins:/usr/local/share/debops/debops-playbooks/playbooks/vars_plugins:/usr/share/ansible/vars_plugins
ansible_managed = This file is managed remotely, all changes will be lost
action_plugins = /Users/ringse/debops-wordpress/ansible/action_plugins:/usr/local/share/debops/debops-playbooks/playbooks/action_plugins:/usr/share/ansible/action_plugins
callback_plugins = /Users/ringse/debops-wordpress/ansible/callback_plugins:/usr/local/share/debops/debops-playbooks/playbooks/callback_plugins:/usr/share/ansible/callback_plugins
**lookup_plugins = /Users/ringse/debops-wordpress/ansible/lookup_plugins:/usr/local/share/debops/debops-playbooks/playbooks/lookup_plugins:/usr/share/ansible/lookup_plugins**`

I can find the lookup_plugins under below catagory:
**/usr/local/share/debops/debops-playbooks/playbooks/lookup_plugins**

**Comment by carlalexander** [comment]
Did you try `pip install debops --upgrade` like the message said?
