### ISSUE TITLE
Digital Ocean 16.04; Mac OS Fail2ban error

### ISSUE THREAD

**Issue by matthew6688** [carlalexander/debops-wordpress#105]
RUNNING HANDLER [debops.fail2ban : Restart fail2ban] ***************************
fatal: [fengclass.net]: FAILED! => {"changed": false, "failed": true, "msg": "Job for fail2ban.service failed because the control process exited with error code. See \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}

**Comment by matthew6688** [comment]
The "debops" commmand is complete, and no error. 

But the above error happens in "debops wordpress" command.

I am doing the process again, and will paste the output here in a mins

**Comment by matthew6688** [comment]
After the second run, there is no error:

"PLAY RECAP *********************************************************************
fengclass.net              : ok=170  changed=28   unreachable=0    failed=0   

TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 255.06s
TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 222.84s
TASK: debops.postfix : Generate Postfix hash tables sources ------------ 71.88s
TASK: debops.postfix : Restart Postfix if capabilities change ---------- 71.00s
TASK: debops.fail2ban : Configure fail2ban jails ----------------------- 58.87s
TASK: debops.fail2ban : Install custom fail2ban rule files ------------- 54.05s
TASK: debops.postfix : Generate Postfix tables sources ----------------- 53.37s
TASK: debops.redis : Install Redis custom scripts ---------------------- 45.67s
TASK: debops.ferm : Remove ip(6)tables rules if requested -------------- 42.76s
TASK: debops.fail2ban : Configure custom fail2ban filters -------------- 38.72s
"

but my website is still not accessable.

domain name is fengclass.net. 

Can someone try from your end.

It is showing:"
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx."

Any ideas, what is the problems?

**Comment by matthew6688** [comment]
All command finished with no error, why the website is not installed. only showing "welcome to Nginx"

Any ideas what is the problem?

**Comment by carlalexander** [comment]
fengclass.net times out for me, but I can ping it

**Comment by matthew6688** [comment]
Now it is working propely
