### ISSUE TITLE
Updating ssl certificates

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#107]
Hi Carl,

i am finding it difficult to update the ssl certificates. i cannot find the certbot-auto executable.
Could you point me in the right direction?

**Comment by carlalexander** [comment]
What do you mean upgrade certificates? Replace existing ones with new ones?

**Comment by cezarneaga** [comment]
No. got a certificates expiring notice. They need renewing. Usually a simple `certbot-auto renew` solves it.

**Comment by carlalexander** [comment]
Sorry, I wasn't clear. Which type of certificate are we talking about? `manual`, `letsencrypt`, `selfsigned`?

**Comment by cezarneaga** [comment]
letsencrypt

**Comment by carlalexander** [comment]
Hmmm it should update automatically. That's how `debops-pki` configures it. Is there an error log in `/etc/pki/realms/yourdomain.com/acme/`?

**Comment by cezarneaga** [comment]
nope. no error_log there. maybe it renewed. it just does it after letsencrypt decides to send an email to notify. maybe we could just make the renewal happen more often.

**Comment by carlalexander** [comment]
I'm not sure what the interval is for the renewal. I don't even have let's encrypt setup to send me emails. It's just been doing it lol.

It's possible that Let's Encrypt expects a different setup than what `debops.pki` is doing. And that's why you're getting an email. It's check your certificate expiry date and see if it changes over time.

**Comment by cezarneaga** [comment]
cheers.
thanks!

**Comment by zedrickvillas** [comment]
Please close this ticket if the issue is resolved. Thanks :D

**Comment by cezarneaga** [comment]
this is still an issue at least on ubuntu 14.04 setup. certificates do not renew.

**Comment by carlalexander** [comment]
Is there an `error.log` in `/etc/pki/realms/<domain>/acme`?

**Comment by cezarneaga** [comment]
nope. no error.log

**Comment by carlalexander** [comment]
Can you try to run `/usr/local/lib/pki/pki-realm schedule`? I might have to defer to @drybjed for this since I don't understand everything that goes on in `debops.pki`. I'm not sure why it wouldn't renew.

**Comment by cezarneaga** [comment]
`pki-realm: 7: set: Illegal option -o pipefail`

**Comment by carlalexander** [comment]
Was that with `sudo`? Sorry didn't put it in the comment 😢

**Comment by cezarneaga** [comment]
yes yes

**Comment by carlalexander** [comment]
Weird, that might be why it doesn't renew. At this point, I think you should create a ticket for it in [`debops.pki`](https://github.com/debops/ansible-pki) and see what @drybjed thinks.

**Comment by carlalexander** [comment]
Did you find the issue @cezarneaga?

**Comment by cezarneaga** [comment]
no. i just thought it might be obsolete as now there are other versions already up that might have solved it
