### ISSUE TITLE
Can't Connect to Server (LiNode)

### ISSUE THREAD

**Issue by zedrickvillas** [carlalexander/debops-wordpress#109]
Running Ansible playbook from:
/Users/zedrickvillas/Library/Application Support/debops/debops-playbooks/playbooks/bootstrap.yml ...

PLAY [Bootstrap Python support on a host] **************************************

TASK [debops.bootstrap/raw : Update APT repositories, install mandatory packages] ***
fatal: [45.118.132.224]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/Users/zedrickvillas/Library/Application Support/debops/debops-playbooks/playbooks/bootstrap.retry

PLAY RECAP *********************************************************************
45.118.132.224             : ok=0    changed=0    unreachable=1    failed=0   

TASK: debops.bootstrap/raw : Update APT repositories, install mandatory packages --- 0.79s

**Comment by carlalexander** [comment]
I don't have any experience with Linode, but does it setup ssh access for the root account?

**Comment by carlalexander** [comment]
I'd also point out that you can't use an IP address. You need to setup a DNS entry or the server won't be configured properly.

**Comment by zedrickvillas** [comment]
I thought it also works with IP

> Once your server is created, you'll only have an IP address that points to it. While "DebOps for WordPress" works with an IP address, it works better when you have a domain. That's because a lot of the defaults use that domain.

Quoted from the docs.

**Comment by zedrickvillas** [comment]
Was now able to connect and run the script through Mac's Root and its ssh key.

I am now encountering some problems with the command debops wordpress regarding fail2ban and mariadb creating database. WIll create a new ticket and close this one. thanks.
