### ISSUE TITLE
Access denied on database on Wordpress configuration.

### ISSUE THREAD

**Issue by zedrickvillas** [carlalexander/debops-wordpress#112]
Access denied on database.

`TASK [wordpress : Configure WordPress] *****************************************
fatal: [www.thehealthhacks.com]: FAILED! => {"changed": true, "cmd": ["wp", "core", "config", "--dbhost=localhost", "--dbname=wordpress", "--dbuser=wordpress", "--dbpass=OTAIwDYF_WZPGoRgCh4ZLwi5H:hrUCsOdzYJ62h7cyFKnN6R", "--dbprefix=wp_"], "delta": "0:00:00.123454", "end": "2016-11-13 10:54:03.321365", "failed": true, "rc": 1, "start": "2016-11-13 10:54:03.197911", "stderr": "ERROR 1698 (28000): Access denied for user 'wordpress'@'localhost'", "stdout": "", "stdout_lines": [], "warnings": []}`

**Comment by carlalexander** [comment]
Does the `wordpress` user exist if you connect to the database? I'd also try running your playbook on a new droplet to test if your change from #110 worked.

**Comment by zedrickvillas** [comment]
Ok. Maybe i'll just create a droplet on DigitalOcean since it is the service im using on production. Just want to explore linode because according to reviews and tests it is much more faster than DigitalOcean.

**Comment by zedrickvillas** [comment]
> Does the wordpress user exist if you connect to the database?

I've tried and it doesnt connect, does it mean that one of the task failed?
i didn't see any task failing exempt the error above.

**Comment by carlalexander** [comment]
If I have a bit of time today, I'll try to do a test on Linode and let you know what I find.

**Comment by carlalexander** [comment]
Ok, well right away I can see an issue. Did you setup [SSH authentication on your Linode](https://www.linode.com/docs/security/use-public-key-authentication-with-ssh)? It's mandatory with DebOps.

**Comment by zedrickvillas** [comment]
> If I have a bit of time today, I'll try to do a test on Linode and let you know what I find.

This would be a big help. Thank you.

> Ok, well right away I can see an issue. Did you setup SSH authentication on your Linode? It's mandatory with DebOps.

Yes i've configured that. Other tasks are successful instead of the one connecting to the database. I am now looking for the tasks which creates the db users and the one which connects the user to the db.

**Comment by zedrickvillas** [comment]
Didn't encountered this error with DigitalOcean Droplet.
I think the error i encountered was cause by the difference setup between linode and digitalocean.

**Comment by zedrickvillas** [comment]
Was able to complete the configuration, but i can't access the site.
https://github.com/carlalexander/debops-wordpress/issues/105 
Had the same error, wonder what kind of fix he did.

**Comment by carlalexander** [comment]
> Yes i've configured that. Other tasks are successful instead of the one connecting to the database. I am now looking for the tasks which creates the db users and the one which connects the user to the db.

I opened an [issue](https://github.com/carlalexander/debops-wordpress/issues/113) to document how to setup a Linode so that DebOps work. No ETA on it quite yet.

> Was able to complete the configuration, but i can't access the site.

What do you mean that by can't access the site?

**Comment by zedrickvillas** [comment]
The same as issue #105,
i was prompted with the nginx welcome page.

btw here are the logs from the command debops wordpress.

`TASK [wordpress : Get list of active WordPress plugins] ************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ok: [www.thehealthhacks.com]

TASK [wordpress : Set list of of installed/activated WordPress plugins] ********
ok: [www.thehealthhacks.com]

TASK [wordpress : Install WordPress plugins] ***********************************

TASK [wordpress : Activate WordPress plugins] **********************************

TASK [wordpress : Update WordPress plugins] ************************************

TASK [wordpress : Deactivate WordPress plugins] ********************************

TASK [wordpress : Uninstall WordPress plugins] *********************************

TASK [wordpress : Create WordPress ACME challenge directory] *******************
skipping: [www.thehealthhacks.com]

TASK [wordpress : Append PKI ACME group to WordPress user] *********************
skipping: [www.thehealthhacks.com]

TASK [wordpress : Append PKI ACME group to nginx user] *************************
skipping: [www.thehealthhacks.com]

TASK [wordpress : Run PKI realm configuration] *********************************
skipping: [www.thehealthhacks.com]

TASK [wordpress : Restart nginx to pickup new user group] **********************
skipping: [www.thehealthhacks.com]

RUNNING HANDLER [varnish : Reload systemd daemon] ******************************
changed: [www.thehealthhacks.com]

RUNNING HANDLER [varnish : Restart varnish] ************************************
changed: [www.thehealthhacks.com]

PLAY RECAP *********************************************************************
www.thehealthhacks.com     : ok=171  changed=28   unreachable=0    failed=0   

TASK: debops.ferm : Configure ip(6)tables rules ------------------------ 63.32s
TASK: debops.ferm : Configure ip(6)tables rules ------------------------ 60.54s
TASK: debops.fail2ban : Install custom fail2ban rule files ------------- 29.88s
TASK: debops.redis : Install Redis custom scripts ---------------------- 20.17s
TASK: varnish : Install required packages ------------------------------ 16.82s
TASK: debops.postfix : Generate Postfix hash tables sources ------------ 15.99s
TASK: debops.redis : Install required packages ------------------------- 14.73s
TASK: debops.fail2ban : Configure fail2ban jails ----------------------- 13.13s
TASK: debops.postfix : Generate Postfix tables sources ----------------- 12.78s
TASK: debops.ferm : Remove ip(6)tables rules if requested -------------- 11.64s`

**Comment by zedrickvillas** [comment]
Here is the site.
http://www.thehealthhacks.com/
which displays:
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

**Comment by zedrickvillas** [comment]
https://github.com/carlalexander/debops-wordpress/issues/114
Created a new issue, and will be closing this one.
