### ISSUE TITLE
Write documentation for Linode

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#113]
While doing some testing for this [issue](https://github.com/carlalexander/debops-wordpress/issues/112), I found that a basic Linode doesn't work well with DebOps. Like with Digital Ocean, we'll need good documentation to show how to setup a Linode so that DebOps works on it.

**Comment by zedrickvillas** [comment]
Will try to help out with this. 
Let me know what i can help.

**Comment by carlalexander** [comment]
Well if you get it to work, let me know what you did 😄

**Comment by zedrickvillas** [comment]
Hahaha. Ok 👍 
I've passed the database error, through changing the changing the mariabdbclient and server but what prompted access denied to the generated user.

**Comment by robert1112** [comment]
What about another popular hosting like Vultr? Try before? Thanks.

**Comment by carlalexander** [comment]
Yup, I want to write it for vultr too!

**Comment by robert1112** [comment]
Thanks for your prompt reply.  I am banning my head to set up a top tier wordpress site( as you mentioned) and finally find this.
So you recommend using Digital Ocean?
Does you mean there is problem with Vultr too? 
What about Google Cloud Platform? I used 3 above. Thanks.

**Comment by carlalexander** [comment]
Closing and consolidating all VPS issues to #205. I didn't run into any issues with Vultr @robert1112.
