### ISSUE TITLE
HANDLER Error - Fail2ban failed - DigitalOcean - Ubuntu 16.04

### ISSUE THREAD

**Issue by Mv13** [carlalexander/debops-wordpress#115]
Hello,

- I ran the debops-wordpress playbook. Everything went ok, until reaching the fail2ban handler. Got a fail to restart the service.

Local  Env : Lubutnu 16.04
_DigitalOcean Droplets_ : Ubuntu 16.04 and Ubuntu 16.04 LEMP

> **RUNNING HANDLER** [**debops.fail2ban : Restart fail2ban**] ***************************
> fatal: [digital.tn]: FAILED! => {"changed": false, "failed": true, "msg": "**Unable to restart service fail2ban: Job for fail2ban.service failed because the control process exited with error code**. See \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}
> 
> RUNNING HANDLER [debops.fail2ban : Reload fail2ban jails] **********************
> 
> RUNNING HANDLER [debops.ferm : Restart ferm] ***********************************
> 
> RUNNING HANDLER [debops.nginx : Test nginx and restart] ************************
> 
> RUNNING HANDLER [debops.nginx : Test nginx and reload] *************************
> 
> RUNNING HANDLER [debops.php : Restart php-fpm] *********************************
> 	to retry, use: --limit @/home/mv13/debops-wordpress/playbooks/wordpress.retry
> 
> PLAY RECAP *********************************************************************
> digital.tn                 : **ok=105  changed=64   unreachable=0    failed=1**   
> 
> TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 215.73s
> TASK: debops.mariadb_server : Install database server packages --------- 39.44s
> TASK: debops.fail2ban : Install custom fail2ban rule files ------------- 30.54s
> TASK: debops.nginx : Generate nginx server configuration --------------- 26.80s
> TASK: debops.php : Install PHP packages -------------------------------- 26.75s
> TASK: debops.nginx : Configure nginx upstreams ------------------------- 25.16s
> TASK: debops.ferm : Make sure required directories exist --------------- 22.60s
> TASK: debops.fail2ban : Configure fail2ban jails ----------------------- 21.79s
> TASK: debops.ferm : Remove ip(6)tables rules if requested -------------- 19.35s
> TASK: debops.nginx : Create default nginx directories ------------------ 19.14s
> 
> 

When I retried to run the playbook, oddly it locked me out of the Droplet : 

> _Running Ansible playbook from_:
> /home/mv13/debops-wordpress/playbooks/wordpress.yml ...
> 
> _PLAY_ [Manage WordPress web server] *********************************************
> 
> _TASK_ [setup] *******************************************************************
> fatal: [digital.tn]: **UNREACHABLE!** => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host digital.tn port 22: **Connection refused**\r\n", "unreachable": true}
> 	to retry, use: --limit @/home/mv13/debops-wordpress/playbooks/wordpress.retry
> 
> _PLAY RECAP_ *********************************************************************
> digital.tn                 : ok=0    changed=0    **unreachable=1**    failed=0   
> 
> TASK: setup ------------------------------------------------------------- 2.08s
> 

-I did get through the VNC console to check for ufw (disabled), iptables and fail2ban jails that would prevent me from sshing to the Droplet. 

This is the fail2ban log entry, _before_ successfully restarting it from the VNC  : 

![image](https://cloud.githubusercontent.com/assets/8958971/20423960/ad54089c-ad73-11e6-8503-5d6f9966de2d.png)

The Droplet is listening on Port 22 : 

![image](https://cloud.githubusercontent.com/assets/8958971/20425553/628a5886-ad7b-11e6-99eb-9c6454e7e8e3.png)
 
SSH Service is enabled : 

![image](https://cloud.githubusercontent.com/assets/8958971/20425595/866c1e06-ad7b-11e6-82ba-97d54ae47269.png)

I had a similar issue with another droplet, in which I got restricted from accessing the VPS. When I flushed the iptables and removed fail2ban jails, the error went from connection refused to connection timed out.

Currently I am unable to retry the wordpress playbook.

Thanks in advance.

**Comment by zedrickvillas** [comment]
Hi, have you setup your ssh keys before doing the process?

**Comment by Mv13** [comment]
Hi, Yes indeed, the ssh keys were added and used without a problem during the initial bootstrap, and later during the run of the wordpress-playbook.

**Comment by zedrickvillas** [comment]
Ok. Have you edited other configuration files other than the inventory files or the .cfg if you are using Mac?
If not, Can you try rebuilding your droplet and try again?

**Comment by Mv13** [comment]
No other configuration files were edited. I'll rebuild the droplet and re-try again. Thanks

**Comment by zedrickvillas** [comment]
Ok, Let me know what happens.
btw, i've encountered that problem before, but when at the second run of debops wordpress, everything worked fine. Just need to restart my droplet then it the site is up and running.

**Comment by Mv13** [comment]
Hi,
I eventually re-configured the iptables rules, removed fail2ban ones and reset the INPUT chain to ACCEPT. **Now I can ssh back to the Droplet.**

I suppose it's fail2ban strict jail rules behind it #116 . It's better to wait a little bit before trying to re-run the playbook when encountring a fail error.

**Comment by carlalexander** [comment]
SSH shouldn't trigger the DDOS jail. Is there anything in your fail2ban log?

**Comment by Mv13** [comment]
Hi Carl,

This was present on the fail2ban log 

> 2016-11-20 15:10:50,077 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Ban 162.13.178.32
> 2016-11-20 15:20:51,036 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Unban 162.13.178.32
> 2016-11-20 20:38:35,679 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Ban 162.13.178.32
> 2016-11-20 20:48:36,656 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Unban 162.13.178.32
> 2016-11-20 21:59:39,237 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Ban 162.13.178.32
> 2016-11-20 22:09:39,242 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Unban 162.13.178.32
> 2016-11-20 23:35:53,048 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Ban 162.13.178.32
> 2016-11-20 23:35:54,788 fail2ban.actions        [2435]: NOTICE  [wordpress-permanent] Ban 162.13.178.32
> 2016-11-20 23:45:53,054 fail2ban.actions        [2435]: NOTICE  [wordpress-login] Unban 162.13.178.32
> 2016-11-21 10:54:32,771 fail2ban.actions        [2435]: NOTICE  [sshd] Ban 91.224.161.88
>

**Comment by carlalexander** [comment]
Is `162.13.178.32` your IP?

**Comment by Mv13** [comment]
No it's not.

**Comment by carlalexander** [comment]
Do you see your IP anywhere in your log? It would tell you if fail2ban blocked you. Otherwise, it's possible that the firewall blocked you. I've seen it happen before. DebOps configures iptables to block excessive SSH connections.

**Comment by Mv13** [comment]
Exactly, my IP appeared multiple times. I re-connected a lot through ssh.

Thank you for your input and the job done behind debops-wordpress. This issue is resolved at the moment
