### ISSUE TITLE
TASK [debops.bootstrap : Install ssh public key on admin accounts] error

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#118]
Hi guys,
encountering a new error by running off of tag v0.3.1.

on `debops bootstrap -u root` the process fails.
failed: [<domain>] (item={'name': 'root'}) => {"failed": true, "item": {"name": "root"}, "msg": "invalid key specified: ---- BEGIN SSH2 PUBLIC KEY ----"}
failed: [<domain>] (item={u'name': u'cezar'}) => {"failed": true, "item": {"name": "cezar"}, "msg": "invalid key specified: ---- BEGIN SSH2 PUBLIC KEY ----"}

i can connect just fine with `ssh root@<domain>` 
appreciate your help

Cezar

**Comment by drybjed** [comment]
It looks like the SSH key the role detects has the format used by Putty. Can you check and convert the key to the normal `authorized_keys` entry instead?

**Comment by cezarneaga** [comment]
Used the same key before. How could it have changed?

**Comment by carlalexander** [comment]
I've never seen this error before. Not sure, if it's not an Ansible issue more than an issue with DebOps. Did you update anything since the last time it worked?

**Comment by cezarneaga** [comment]
`debops update` only

**Comment by cezarneaga** [comment]
seems solved today. after another `debops-update`

**Comment by cezarneaga** [comment]
now this reappeared! showing me no love again :)

**Comment by carlalexander** [comment]
Do you still have this problem @cezarneaga?
