### ISSUE TITLE
Wordpress Doesnt Detect Varnish

### ISSUE THREAD

**Issue by zedrickvillas** [carlalexander/debops-wordpress#120]
When i try to configure Varnish Purge. There is a warning saying We did not find Varnish active for this domain.
Is this normal or something is wrong on my server?

**Comment by carlalexander** [comment]
Hmmmm I have not checked the new major version of the Varnish plugin. It's really designed for Dreamhost so it's possible I need to fake something for it. I'll investigate.

**Comment by zedrickvillas** [comment]
Ok thank you.
let me know once you find a solution.

**Comment by carlalexander** [comment]
I've just installed a fresh version of WordPress 4.7 and the Varnish plugin version 4.0.2. If I click on "Purge Varnish", I don't get an error. Do you have any more details on your current setup?

**Comment by zedrickvillas** [comment]
Does wordpress detect varnish or does the responses has varnish headers?

**Comment by carlalexander** [comment]
Neither WordPress nor Varnish detect each other. Varnish has special rules for dealing with WordPress requests or response, but it doesn't know if they came from WordPress per say. 

If Varnish is active, you should have some special headers in your response like `x-cache` and `x-cache-hits`. If they're not there then, it's possible that Varnish isn't running on the server.

**Comment by carlalexander** [comment]
I feel like a bit of an idiot for not thinking of it sooner, but did you add the directives in the [wiki](https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-Varnish#varnish-http-purge)?

**Comment by carlalexander** [comment]
Is this still an issue @zedrickvillas?

**Comment by georgiemathews** [comment]
@carlalexander this is an issue for me. I made sure the right directives were in the vars and tried removing and reinstalling the plugin. I do have the `x-cache` headers, but the varnish plugin does not detect varnish.

**Comment by carlalexander** [comment]
Do you have a link to the site in question @georgiemathews?

**Comment by carlalexander** [comment]
I'm going to close this for now. You can reopen the issue again if you still have a problem @georgiemathews!

**Comment by gleert** [comment]
I am getting the error "We did not find Varnish active for this domain." in the "Varnish HTTP Purge" plugin...

![screen shot 2017-06-01 at 00 35 30](https://cloud.githubusercontent.com/assets/1012430/26657084/44c75314-4662-11e7-912f-e194f9b56d9f.png)

I have followed the following instructions https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-Varnish

Varnish is running:
![screen shot 2017-06-01 at 00 41 03](https://cloud.githubusercontent.com/assets/1012430/26657257/15eccec4-4663-11e7-8b33-f7a981feae86.png)
