### ISSUE TITLE
failing to install php

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#121]
i get this error
```
TASK [debops.php : Install PHP packages] ***************************************
task path: /Users/cezar/Library/Application Support/debops/debops-playbooks/roles/debops.php/tasks/main.yml:15
<www.mhpss.net> ESTABLISH SSH CONNECTION FOR USER: None
<www.mhpss.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/cezar/.ansible/cp/ansible-ssh-%h-%p-%r www.mhpss.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1480837923.15-256562845418054 `" && echo ansible-tmp-1480837923.15-256562845418054="` echo $HOME/.ansible/tmp/ansible-tmp-1480837923.15-256562845418054 `" ) && sleep 0'"'"''
<www.mhpss.net> PUT /var/folders/8d/882m203j7qj4__4k4fspycmw0000gn/T/tmpZcR9_L TO /root/.ansible/tmp/ansible-tmp-1480837923.15-256562845418054/apt
<www.mhpss.net> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/cezar/.ansible/cp/ansible-ssh-%h-%p-%r '[www.mhpss.net]'
<www.mhpss.net> ESTABLISH SSH CONNECTION FOR USER: None
<www.mhpss.net> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/cezar/.ansible/cp/ansible-ssh-%h-%p-%r -tt www.mhpss.net '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-vwmwcsowaqgpnznomvreacpjxmtjoidh; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1480837923.15-256562845418054/apt; rm -rf "/root/.ansible/tmp/ansible-tmp-1480837923.15-256562845418054/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
failed: [www.mhpss.net] (item=[u'', u'php7.0-cli', u'php7.0-fpm', u'php7.0', u'php7.0-curl', u'php7.0-gd', u'php7.0-mcrypt', u'php7.0-mysql', u'php7.0-curl', u'php7.0-dev', u'php-redis', u'php7.0-xml']) => {"failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": null, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": false, "name": ["", "php7.0-cli", "php7.0-fpm", "php7.0", "php7.0-curl", "php7.0-gd", "php7.0-mcrypt", "php7.0-mysql", "php7.0-curl", "php7.0-dev", "php-redis", "php7.0-xml"], "only_upgrade": false, "package": ["", "php7.0-cli", "php7.0-fpm", "php7.0", "php7.0-curl", "php7.0-gd", "php7.0-mcrypt", "php7.0-mysql", "php7.0-curl", "php7.0-dev", "php-redis", "php7.0-xml"], "purge": false, "state": "present", "update_cache": false, "upgrade": null}, "module_name": "apt"}, "item": ["", "php7.0-cli", "php7.0-fpm", "php7.0", "php7.0-curl", "php7.0-gd", "php7.0-mcrypt", "php7.0-mysql", "php7.0-curl", "php7.0-dev", "php-redis", "php7.0-xml"], "msg": "No package matching '' is available"}
```
any ideas why?
Cezar

**Comment by zedrickvillas** [comment]
I have encountered this and was able to resolve the issue by starting over again, didn't bothered to check for the root cause, but i think this was cause by connectivity issue either the droplet or the php package.

**Comment by cezarneaga** [comment]
tried already 3 times
will try again :)

**Comment by zedrickvillas** [comment]
May i ask which server provider are u using?

**Comment by cezarneaga** [comment]
digital ocean. failed again

**Comment by zedrickvillas** [comment]
Hmmm. have you created a new droplet and tried again?
Try it one last time, put ---v to debug if it happens again.

**Comment by cezarneaga** [comment]
the code above comes from -vvvv

**Comment by zedrickvillas** [comment]
yeah thats what i meant.
Wait, i am trying to deploy a server again, let wait if i would encounter the same error as yours.

**Comment by zedrickvillas** [comment]
Was able to deploy a new wordpress site just now with no errors.
I suggest you destroy that droplet and try it from the beginning. :)

**Comment by carlalexander** [comment]
Sorry I didn't answer sooner @cezarneaga! I was out of town for WordCamp US. Are you using the newest tag from a week or two ago? I fixed a bug with the `php-redis` package that sounds like this.

**Comment by carlalexander** [comment]
It does look like the issue is back. I'm running tests and I can reproduce it.

**Comment by carlalexander** [comment]
Running it a second time seems to go ok. I'll run it by @drybjed to see if I did something wrong.

**Comment by carlalexander** [comment]
I did a new test droplet today to test the issue. This time everything worked on the first try. I'll keep an eye out as I work on other issues.

**Comment by bonakor** [comment]
Hey @carlalexander,
I have exactly the same issue.
`failed: [2k17.fr] (item=[u'', u'php7.0-cli', u'php7.0-fpm', u'php7.0', u'php7.0-curl', u'php7.0-gd', u'php7.0-mcrypt', u'php7.0-mysql', u'php7.0-curl', u'php7.0-dev', u'php-redis', u'php7.0-xml']) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoremove": false, 
            "cache_valid_time": 0, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "install_recommends": false, 
            "name": [
                "", 
                "php7.0-cli", 
                "php7.0-fpm", 
                "php7.0", 
                "php7.0-curl", 
                "php7.0-gd", 
                "php7.0-mcrypt", 
                "php7.0-mysql", 
                "php7.0-curl", 
                "php7.0-dev", 
                "php-redis", 
                "php7.0-xml"
            ], 
            "only_upgrade": false, 
            "package": [
                "", 
                "php7.0-cli", 
                "php7.0-fpm", 
                "php7.0", 
                "php7.0-curl", 
                "php7.0-gd", 
                "php7.0-mcrypt", 
                "php7.0-mysql", 
                "php7.0-curl", 
                "php7.0-dev", 
                "php-redis", 
                "php7.0-xml"
            ], 
            "purge": false, 
            "state": "present", 
            "update_cache": false, 
            "upgrade": null
        }, 
        "module_name": "apt"
    }, 
    "item": [
        "", 
        "php7.0-cli", 
        "php7.0-fpm", 
        "php7.0", 
        "php7.0-curl", 
        "php7.0-gd", 
        "php7.0-mcrypt", 
        "php7.0-mysql", 
        "php7.0-curl", 
        "php7.0-dev", 
        "php-redis", 
        "php7.0-xml"
    ], 
    "msg": "No package matching '' is available"
}
`
 I've tried with two droplets, each time brand new. And I use the last version (0.3.1)

**Comment by carlalexander** [comment]
Sorry, I didn't investigate sooner. There's an [open issue](https://github.com/debops/ansible-php/issues/17) for it in `debops.php`. Will keep track of it.

**Comment by carlalexander** [comment]
This should now be fixed! Run `debops-update` to get the latest `debops.php` and everything should be good. I hope... 😂
