### ISSUE TITLE
fail2ban fails to start

### ISSUE THREAD

**Issue by jbicha** [carlalexander/debops-wordpress#123]
My remote machine is a Ubuntu 16.10 cloud image 20161214 run with qemu-kvm. Except for 'sudo apt update; sudo apt dist-upgrade' I have not anything else to it except run:
```
debops bootstrap -b
debops wordpress
```

```
RUNNING HANDLER [debops.fail2ban : Restart fail2ban] ***************************
fatal: [example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service fail2ban: Job for fail2ban.service failed because the control process exited with error code.\nSee \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [debops.fail2ban : Reload fail2ban jails] **********************

RUNNING HANDLER [debops.nginx : Test nginx and restart] ************************

RUNNING HANDLER [debops.nginx : Test nginx and reload] *************************

RUNNING HANDLER [debops.php : Restart php-fpm] *********************************
	to retry, use: --limit @/home/jeremy/devel/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
example.com                  : ok=150  changed=90   unreachable=0    failed=1   
```

journalctl -xe
----------------
```
-- Subject: Unit fail2ban.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit fail2ban.service has begun starting up.
Dec 30 23:12:18 example fail2ban-client[25049]: ERROR  No file(s) found for glob /var/log/nginx/varnish*access.log
Dec 30 23:12:18 example fail2ban-client[25049]: ERROR  Failed during configuration: Have not found any log file for wordpress-badbots jail
Dec 30 23:12:18 example systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Dec 30 23:12:18 example systemd[1]: Failed to start Fail2Ban Service.
```

**Comment by jbicha** [comment]
I duplicated this with Ubuntu 16.04 also

**Comment by carlalexander** [comment]
Did you disable varnish by any chance? It's not seeing any varnish log files and crashing. (Horrible behaviour.)

**Comment by cnaccio** [comment]
I ran into this issue as well... Tried running debops wordpress again and it worked the second time....

**Comment by JeffCleverley** [comment]
I had this problem too.

I retried running again with:

`$ debops wordpress --limit @/Users/Jeff/debops-wordpress/playbooks/wordpress.retry`

It ran the playbook to the end after, and wordpress is up and running, but I don't know if fail2ban is running or not, how to check?

**Comment by carlalexander** [comment]
You can do `sudo service fail2ban status`

**Comment by carlalexander** [comment]
I haven't run into this issue in a while. Do you still have it @jbicha?

**Comment by jbicha** [comment]
@carlalexander I haven't used debops in several months. Thanks!

**Comment by skygunner** [comment]
The current v0.4.0 version still has this problem. Run 
debops wordpress --limit @/home/jeremy/devel/debops-wordpress/playbooks/wordpress.retry following this error will work.
