### ISSUE TITLE
wp-cli failed to validate SSL certificate

### ISSUE THREAD

**Issue by jbicha** [carlalexander/debops-wordpress#124]
I experienced this with Ubuntu 16.04 and 16.10. ca-certificates is installed.

TASK [wpcli : Download wp-cli] *************************************************
fatal: [amx03.com]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for raw.githubusercontent.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by jbicha** [comment]
I was able to log in to the server and look some more.

```
$ wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
--2016-12-31 07:22:58--  https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
wget: unable to resolve host address ‘raw.githubusercontent.com’
```
The "server" is just a virtual machine running on my local Ubuntu machine. I can resolve other URLs in the virtual machine and I can access URL fine from my regular local machine.

**Comment by jbicha** [comment]
Could we get that file mirrored somewhere else?

Maybe github wants a referral link from https://github.com/wp-cli/builds/blob/gh-pages/phar/wp-cli.phar

**Comment by carlalexander** [comment]
It's the link given on the wp-cli.org page. Maybe the documentation is outdated. I'd check with them about it. You can change `wpcli__base_url` to the builds project if you want a fix for now.

**Comment by jbicha** [comment]
I'm going to go ahead and close this.

I'm using Ubuntu GNOME 17.04 Alpha which has some odd issues with cname resolution in certain cases so I would just ignore this issue unless you see other reports. Thank you!
