### ISSUE TITLE
Setup: Failed to connect to the host via ssh: Permission denied

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#127]
Hi,

I am stuck at running the `debops boostrap -u root` command, it gives me this error:

```
PLAY [Bootstrap Python support on a host] **************************************

TASK [debops.bootstrap/raw : Update APT repositories, install mandatory packages] ***
fatal: [12.345.6.789]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
        to retry, use: --limit @/home/user/.local/share/debops/debops-playbooks/playbooks/bootstrap.retry

PLAY RECAP *********************************************************************
12.345.6.789               : ok=0    changed=0    unreachable=1    failed=0
```

Any ideas?

**Comment by carlalexander** [comment]
```
Failed to connect to the host via ssh: Permission denied (publickey,password).
```

This means that there's an issue with the SSH key when you tried to connect. What host are you using?

**Comment by ghost** [comment]
Digital Ocean.
I double checked and when connecting with putty, it works, meaning it doesn't prompt me with a password request.

**Comment by carlalexander** [comment]
If you're using putty, does that mean that you're you using Ansible inside Windows?

**Comment by ghost** [comment]
Ansible is on the server at DO right? It's running Ubuntu. Not sure what you mean with that. I use putty to connect to my droplet, which is where I want this to run.

**Comment by ghost** [comment]
Oh I see.

I mean that my SSH key which I generated using puttygen works with the servers public key, when I connect using putty and my key.

**Comment by carlalexander** [comment]
No, Ansible runs on your computer and not the server. I explain it [here](https://github.com/carlalexander/debops-wordpress/wiki/Installation#installation). This is why I asked about Windows because, as far as I know, Ansible doesn't officially support Windows yet. 

However, there's a [tutorial](http://www.jeffgeerling.com/blog/2017/using-ansible-through-windows-10s-subsystem-linux) on how to install it using the new Windows bash subsystem. I haven't tested it yet though.

**Comment by warhost** [comment]
Wait, ansible runs on me being the client to install debops on the droplet?
So should I use a linux distro to connect to my droplet via SSH, and this could be fixed?

**Comment by ghost** [comment]
Ah I see, I didn't realize this, thanks!

**Comment by warhost** [comment]
Okay so I am still getting that same error on Ubuntu. Also tried adding it to the ssh config file, didn't work.
