### ISSUE TITLE
Please allow configuring cron frequency

### ISSUE THREAD

**Issue by jbicha** [carlalexander/debops-wordpress#131]
Please add an option to configure how often wp-cron is run.

Currently it runs every single minute, but I recommend setting the default to be less frequent.
- [6 times per hour](https://easyengine.io/tutorials/wordpress/wp-cron-crontab/)
- [4 times per hour](https://tommcfarlin.com/wordpress-cron-jobs/)
- [4 times per hour](https://support.hostgator.com/articles/how-to-replace-wordpress-cron-with-a-real-cron-job)
- [4 times per day](http://www.inmotionhosting.com/support/website/wordpress/disabling-the-wp-cronphp-in-wordpress)

**Comment by carlalexander** [comment]
I'm actually reworking the cron to use wp-cli as I'm working on [supporting bedrock](https://github.com/carlalexander/debops-wordpress/issues/2). I'll add an option to change this, but I'm just not sure why doing it every minute is an issue.

**Comment by carlalexander** [comment]
I'm keeping the default to every minute. That said, you have `wordpress__cron_minute` and `wordpress__cron_hour` exposed to alter how often it runs per day.
