### ISSUE TITLE
Error while "Run Task from Postfix Makefile"

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#132]
I am getting this while running debops wordpress:

```
TASK [debops.postfix : Run tasks from Postfix Makefile] ************************
fatal: [12.345.678.910]: FAILED! => {"changed": true, "cmd": ["make"], "delta": "0:00:01.006358", "end": "2017-01-19 09:09:06.272111", "failed": true, "rc": 2, "start": "2017-01-19 09:09:05.265753", "stderr": "postmap: warning: valid_hostname: numeric hostname: 46\npostmap: fatal: file /etc/postfix/main.cf: parameter myhostname: bad parameter value: 46\nmake: *** [hash_tables/archive_transport.db] Error 1", "stdout": "Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed", "stdout_lines": ["Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed"], "warnings": []}
```

Someone else get this?

**Comment by carlalexander** [comment]
I've never seen this :/

**Comment by eldarc** [comment]
@warhost Have you used an IP address for `[debops_all_hosts]` and `[wordpress]` in `inventory/hosts`?

Setting up a domain name and using it in the `hosts` file will probably solve this.

**Comment by ghost** [comment]
Indeed I am using an IP. Will try with a domain later.

**Comment by carlalexander** [comment]
You must use a resolvable domain with DebOps. Otherwise, weird things can happen.

**Comment by ghost** [comment]
I didn't know this, the Wiki suggested that an IP would be fine.

**Comment by carlalexander** [comment]
You're right. This isn't the case anymore. I've modified the wiki to reflect this.

**Comment by JeffCleverley** [comment]
I just ran into this.

```
TASK [debops.postfix : Run tasks from Postfix Makefile] ************************
fatal: [lxix.clothing]: FAILED! => {"changed": true, "cmd": ["make"], "delta": "0:00:01.042760", "end": "2017-02-01 16:14:19.312468", "failed": true, "rc": 2, "start": "2017-02-01 16:14:18.269708", "stderr": "postmap: warning: valid_hostname: numeric hostname: 139\npostmap: fatal: file /etc/postfix/main.cf: parameter myhostname: bad parameter value: 139\nmake: *** [hash_tables/archive_transport.db] Error 1", "stdout": "Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed", "stdout_lines": ["Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed"], "warnings": []}
```

I think the wiki still suggests using an IP is okay:
https://github.com/carlalexander/debops-wordpress/wiki/Configuring-your-server#add-your-server-to-the-hosts-file

Anyway, I assigned a resolvable domain and updated the hosts file accordingly.

But the error persisted, so I ran it again with `-vvvv`, full error code below:

```
TASK [debops.postfix : Run tasks from Postfix Makefile] ************************
task path: /root/.local/share/debops/debops-playbooks/roles/debops.postfix/tasks/configure.yml:110
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<lxix.clothing> ESTABLISH SSH CONNECTION FOR USER: None
<lxix.clothing> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r lxix.clothing '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611 `" && echo ansible-tmp-1485965816.48-100063751820611="` echo $HOME/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611 `" ) && sleep 0'"'"''
<lxix.clothing> PUT /tmp/tmpX1hvuW TO /root/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611/command.py
<lxix.clothing> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[lxix.clothing]'
<lxix.clothing> ESTABLISH SSH CONNECTION FOR USER: None
<lxix.clothing> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r lxix.clothing '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611/ /root/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611/command.py && sleep 0'"'"''
<lxix.clothing> ESTABLISH SSH CONNECTION FOR USER: None
<lxix.clothing> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt lxix.clothing '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-cyqksijxkscrjnzygdpgserrknwhyihe; LC_ALL=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485965816.48-100063751820611/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [lxix.clothing]: FAILED! => {
    "changed": true,
    "cmd": [
        "make"
    ],
    "delta": "0:00:01.012811",
    "end": "2017-02-01 16:16:57.744232",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "make",
            "_uses_shell": false,
            "chdir": "/etc/postfix",
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 2,
    "start": "2017-02-01 16:16:56.731421",
    "stderr": "postmap: warning: valid_hostname: numeric hostname: 139\npostmap: fatal: file /etc/postfix/main.cf: parameter myhostname: bad parameter value: 139\nmake: *** [hash_tables/archive_transport.db] Error 1",
    "stdout": "Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed",
    "stdout_lines": [
        "Makefile:16: recipe for target 'hash_tables/archive_transport.db' failed"
    ],
    "warnings": []
}
```

Set up:

512MB Digital Ocean Droplet 1 - Debops/Ansible Controller - Ubuntu 16.04.1 LTS - No domain assigned

512MB Digital Ocean Droplet 2 - Machine being configured - Ubuntu 16.04.1 LTS - Domain assigned (lxix.clothing)

**Comment by carlalexander** [comment]
I've modified that page too! Thanks!

**Comment by JeffCleverley** [comment]
No worries. I've deleted those droplets now, but will give it another shot later with the domain assigned from the very beginning of the process. 

See if that problem still persists.

**Comment by carlalexander** [comment]
Do you still have this problem?

**Comment by JeffCleverley** [comment]
@carlalexander 

Hey, I haven't been deploying via 2 droplets since then. I installed a new vpn on my router which negated the need, ssh'ing into the singapore droplet to deploy is fast enough.

I can have a go again sometime over this weekend and let you know.

**Comment by carlalexander** [comment]
Yup, let me know if you have the time. 😄

**Comment by carlalexander** [comment]
Any news on this @JeffCleverley? At worst, we can close and reopen if the issue appears again. 😄

**Comment by JeffCleverley** [comment]
@carlalexander I'll provision a new server now, have a check. I'm back in the UK now, so situation is a bit different (China before), but i'll let you know.

---

New install is up and running. No problems. Can probably close, like you say.

**Comment by carlalexander** [comment]
Awesome! Thanks @JeffCleverley!

**Comment by AlifArnado** [comment]
i have similar issue, 512MB Digital Ocean

512MB Digital Ocean

``
TASK [debops.postfix : Generate Postfix Makefile] ******************************
ok: [mydomain.net]

TASK [debops.postfix : Generate Postfix configuration] *************************
failed: [mydomain.net] (item=main.cf) => {"failed": true, "item": "main.cf", "msg": "KeyError: 'undefined variable: 0'"}
failed: [mydomain.net] (item=master.cf) => {"failed": true, "item": "master.cf", "msg": "KeyError: 'undefined variable: 0'"}
	to retry, use: --limit @/var/www/html/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
mydomain.net              : ok=29   changed=0    unreachable=0    failed=1   

TASK: debops.ferm : Configure ip(6)tables rules ------------------------ 33.69s
TASK: debops.ferm : Remove ip(6)tables rules if requested --------------- 7.19s
TASK: debops.ferm : Make sure required directories exist ---------------- 4.67s
TASK: Gathering Facts --------------------------------------------------- 3.25s
TASK: debops.ferm : Ensure ferm is installed ---------------------------- 2.93s
TASK: debops.postfix : Create Postfix configuration directories --------- 2.66s
TASK: debops.postfix : Divert original Postfix configuration ------------ 2.05s
TASK: debops.postfix : Configure Postfix local facts -------------------- 1.96s
TASK: debops.ferm : Configure forwarding in ifupdown if enabled --------- 1.95s
TASK: debops.ferm : Configure sysctl ------------------------------------ 1.84s
``

**Comment by drybjed** [comment]
Oh, I know what this is - you have incompatible `python-jinja2` library, something like 2.9.x version installed. Roll it back to ~2.7.x and it should be good. Check the list of system packages (`dpkg -l | grep python-jinja`) as well as list of PyPI packages (`pip list | grep Jinja`) to see what version you have currently using.

**Comment by carlalexander** [comment]
I've also removed `debops.postfix` from the project since then so it should be ok.
