### ISSUE TITLE
Adding SSL Causes debops-wordpress to fail

### ISSUE THREAD

**Issue by ejholdings** [carlalexander/debops-wordpress#133]
I used debops-wordpress to setup a new website a few days ago (without SSL).  I wanted to have SSL setup so I went and changed the vars.yml file appropriately.  After multiple attempts, I cannot get a new website configured.  I get one of two issues.  If I start with a fresh VPS, I get an error on the ACME challenge directory (please see the attached screen capture).  If I don't start with a completely fresh VPS, fail2ban fails to restart and debops-wordpress dies (restarting the server, which I've found to often fix problems when fail2ban fails to restart, does not fix the problem in this case).  I can't seem to get around this problem -- no SSL seems to be the only way to get the server to configure.  Based on the documentation, that is clearly not the intent.  I have not tried this on Ubuntu 14.04 yet to see if there are key differences between the OS versions that are causing the problem; I'm not sure which version of Ubuntu the SSL piece was originally written against...  Trying to assess what variables may be in play here that are thwarting me from getting SSL setup.

One other thing: In my vars.yml file, I'm also trying to change the default admin username and wordpress table prefix.  I don't think the ACME issue is related to those two other changes but I want to provide details on the full extent of any change/customization I've made from having debops-wordpress work fine and fail to finish.  I recognize the documentation says that you have to start with a fresh server if you are trying to change the default admin username and deftaul table prefix; I think I've tried six different times to get a server to configure with SSL (both with completely fresh VPS and with an already configured one) to no avail.  

The machine I'm running debops from:
- Using VirtualBox to virtualize Ubuntu (on Windows 7)
- SSHing into the VM from the host
- VM is running Ubuntu 16.04 (Xenial)

Machine I'm running debops against:
- Digital Ocean VPS / 512 MB Box
- Ubuntu 16.04 (Xenial)

![acmechallengefailed](https://cloud.githubusercontent.com/assets/25045872/22109526/bafaed0a-de1d-11e6-8356-b407bbaefcd9.png)

**Comment by carlalexander** [comment]
Sorry, I didn't get back to you sooner @ejholdings. Are you able to share your `vars.yml`?

**Comment by yuriolive** [comment]
Same here. I'm sharing my `vars.yml`:

ntp__timezone: 'Etc/UTC'
pki_internal: False
pki_authorities: []
wordpress__ssl: True

![untitled](https://cloud.githubusercontent.com/assets/10088631/22575465/be8143cc-e99c-11e6-948d-92674407e5ec.png)

**Comment by carlalexander** [comment]
Does it fail at the same location if you run it a second time?

**Comment by yuriolive** [comment]
Yes @carlalexander , I have tried a couple of times.

**Comment by yuriolive** [comment]
I don't know exactly, but I suppose the script is not creating the user `pki-acme`. When I print all the users with `cut -d: -f1 /etc/passwd`, `pki-acme` doesn't appear.

**Comment by carlalexander** [comment]
That's what I'm thinking, but I'm not sure why it wouldn't.

**Comment by yuriolive** [comment]
@carlalexander you know where is the code where debops wordpress tries to create the pki-acme user? I can't try help fix that.

**Comment by yuriolive** [comment]
@carlalexander You know exactly where it tries to create the user `pki-acme`? I can try to help solve this bug.

**Comment by yuriolive** [comment]
I have succesfully solved part of the issue adding manually the user `pki-acme`, the group `pki-acme` and assigning  `pki-acme` user to `pki-acme` group. I used the following commands: 
`sudo useradd pki-acme`
`sudo usermod -G pki-acme -a 'pki-acme'`

But now I'm getting the following error:
![error](https://cloud.githubusercontent.com/assets/10088631/22664619/98db1f7c-ec98-11e6-8f87-84f4cb688fe6.png)

I have verified that the folder `/usr/local/lib` don't have the pki directory.

**Comment by carlalexander** [comment]
Sorry, I was away until today. So this is all created by the [`debop.pki`](https://github.com/debops/ansible-pki) role. Can you tell me if it runs or skips if you run this command: `debops wordpress --tags= depend::pki`?

**Comment by yuriolive** [comment]
I have manually added `pki-realm` (link: https://github.com/debops/ansible-pki/blob/8a7fdebe4104d6249c065fb15a7bf36933fd3d8e/files/usr/local/lib/pki/pki-realm) to `/usr/local/lib/pki` and added `pki-acme` as the folder owner. Fixed the problem, but I got another error when it tries to restart nginx to pickup new user group:
![error2](https://cloud.githubusercontent.com/assets/10088631/22674392/e261343c-ecc6-11e6-8e6c-5713bcf3c2dc.png)
Result of `systemctl status nginx.service`:
![error](https://cloud.githubusercontent.com/assets/10088631/22674771/f027d8a8-ecc8-11e6-9c28-1d5969be1297.png)

I have run `debops wordpress --tags=depend::pki` this was the result:
![error](https://cloud.githubusercontent.com/assets/10088631/22674302/66a8deda-ecc6-11e6-9e0e-be3bdb6eae64.png)

**Comment by carlalexander** [comment]
It looks like everything is skipping from `debops.pki` from your last picture. I think that's why everything is broken. Could you just for the sake of testing change `wordpress__ssl` to `False`? I just want to narrow down the issue and see if everything else works.

**Comment by yuriolive** [comment]
@carlalexander Yes when I change `wordpress__ssl` to `False`, everything goes fine. I have changed back  `wordpress__ssl` to `True` and rerun `debops wordpress --tags=depend::pki` with `-vvvv` and verified that is skipping almost everything from `debops.pki`

![error](https://cloud.githubusercontent.com/assets/10088631/22694604/02418190-ed2f-11e6-89c3-7642ba2d35e0.png)

**Comment by carlalexander** [comment]
Can you run `debops wordpress` with `wordpress__ssl: False`? I want to see if the whole playbook runs ok.

**Comment by yuriolive** [comment]
@carlalexander This was the result:
![error](https://cloud.githubusercontent.com/assets/10088631/22720500/63af861c-ed92-11e6-9e83-44d55d262790.png)

**Comment by carlalexander** [comment]
And does the site work? http://gotubers.com/ works for me, but it's not a blank WordPress installation. Also what's the name of the server in the `hosts` file?

**Comment by yuriolive** [comment]
@carlalexander Yes it works without https enable, but I really need https. I think the site is not properly caching pages with Varnish too.  The page is returning `Cache-Control:no-cache, must-revalidate, max-age=0` and is always a MISS. My hosts file is configured with `gotubers.com`:

[debops_all_hosts]
gotubers.com
[wordpress]
gotubers.com

I can give you access with you want, is still a dev server.

**Comment by carlalexander** [comment]
I think we found the issue. You need a full domain name in the `hosts` file. This is mentioned in [this issue](https://github.com/carlalexander/debops-wordpress/issues/137). You might need to recreate the server and give it a full domain name.

Let me know if that works. Otherwise, I can take a look.

**Comment by yuriolive** [comment]
@carlalexander Yes that was the problem. But now how can I use the site like `example.com`, and not `wordpress.example.com`?

**Comment by carlalexander** [comment]
Just set `wordpress__domain` to `example.com`. The playbooks take care of the rest. 😄

**Comment by yuriolive** [comment]
I'm still having problem to configure the DNS, `wordpress.example.com` and `example.com` should be pointing to the server IP? Or `wordpress.example.com` should be pointing to `example.com`. And the vars file with `wordpress__ssl: True` and `wordpress__domain: 'example.com'` should be configure before I run `debops wordpress` for the first time?

**Comment by carlalexander** [comment]
Both `wordpress.example.com` and `example.com` should point to the server IP. Rest sounds good.

**Comment by carlalexander** [comment]
Did this work?

**Comment by yuriolive** [comment]
Sorry for the delay. But I gave up trying to find the bug and configured the server manually.

**Comment by carlalexander** [comment]
Will close this then. Sorry you had so many issues. 😢
