### ISSUE TITLE
fail2ban fails to restart on Digital Ocean Ubuntu 16.04.1 x64

### ISSUE THREAD

**Issue by DanNeish** [carlalexander/debops-wordpress#136]
I have setup a fresh ubuntu 16.04.1 x64 droplet ($5 small droplet) on digital ocean. No modifications have been made to it.
Then ran:
```
debops bootstrap -u root
debops
debops wordpress
```
The first two commands complete successfully, however I receive the following error during `debops wordpress`
```
RUNNING HANDLER [debops.fail2ban : Restart fail2ban] ***************************
fatal: [example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service fail2ban: Job for fail2ban.service failed because the control process exited with error code. See \"systemctl status fail2ban.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [debops.fail2ban : Reload fail2ban jails] **********************

RUNNING HANDLER [debops.nginx : Test nginx and restart] ************************

RUNNING HANDLER [debops.nginx : Test nginx and reload] *************************

RUNNING HANDLER [debops.php : Restart php-fpm] *********************************
	to retry, use: --limit @/Users/daniel/Projects/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
example.com              : ok=149  changed=79   unreachable=0    failed=1

TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 359.78s
TASK: debops.ferm : Configure ip(6)tables rules ----------------------- 314.83s
TASK: debops.fail2ban : Install custom fail2ban rule files ------------ 173.64s
TASK: debops.postfix : Generate Postfix hash tables sources ----------- 112.66s
TASK: debops.postfix : Generate Postfix tables sources ----------------- 99.09s
TASK: debops.fail2ban : Configure fail2ban jails ----------------------- 90.44s
TASK: debops.ferm : Remove ip(6)tables rules if requested -------------- 64.81s
TASK: debops.fail2ban : Configure custom fail2ban filters -------------- 62.23s
TASK: debops.ferm : Make sure required directories exist --------------- 53.60s
TASK: debops.postfix : Generate Postfix configuration ------------------ 51.59s
```
Rerunning 'debops wordpress' completes successfully however when I go to the site in the browser I receive the "Welcome to nginx!" page.

I am on MacOS Sierra using Ansible 2.2.0.0, debops-wordpress tag 0.3.1 

Also, these steps seem to be taking quite a long time, is this normal? (I have no experience with Ansible but have previously used Chef)
Below is the time it took for each of the commands.
```
debops bootstrap -u root   3.5 mins
debops   27 mins
debops wordpress   23 mins 
```
A total of almost 54 minutes to provision a clean server seems excessive?

**Comment by carlalexander** [comment]
Have you tried restarting nginx as mentioned in [this issue](https://github.com/carlalexander/debops-wordpress/issues/114)?  

I'm sorry it took so long to setup your server, but this might be a latency issue. What's the ping to your server?

**Comment by DanNeish** [comment]
Restarting Nginx a second time fixed it, thanks :-)
Is it worth adding this to the known issues page?

Results from ping:
16 packets transmitted, 15 packets received, 6.2% packet loss
round-trip min/avg/max/stddev = 266.097/355.978/605.041/109.130 ms

I noticed in google page speed analysis it recommends minifying css and javascript. Is this managed through Varnish already or do I need to use a minify plugin to achieve this?

**Comment by carlalexander** [comment]
I'd rather fix the issue, but I've never encountered it myself and I create 10+ servers a week right now. 😢 

These are some very high pings. That's why it took so long. My avg ping with Digital Ocean is 25ms. But when I setup a server in Europe, it can easily take twice as long due to the latency. (Which is only 100-125ms.) This is an unfortunate problem with Ansible since it runs everything from your computer.

Minifying CSS and JavaScript should be done by you. I don't have a plugin to recommend, but I'm open to suggestions. In general, I assume that you have a workflow where you use unconcatenated versions in development and the minified one in production.

That said, you shouldn't concatenate CSS or JavaScript files together anymore. It's actually a bad practice with HTTP/2. So I'd avoid a plugin that does that, but minification is fine.

**Comment by DanNeish** [comment]
Ok thanks for the feedback.
What is the best way for me to learn more about the following features and how they are implemented in debops-wordpress:

1. database backups/schedule
2. server monitoring & alerts (eg. monit?)
3. firewall rules: Is it using UFW? from what I can see on the server I setup UFW is disabled.
4. Letsencrypt SSL: Is this set to autorenew?
5. Automatic updates: is it configured to install only security updates? Will it auto-restart after installation if required?

Awesome work on debops-wordpress by the way, very helpful!!

**Comment by carlalexander** [comment]
You can ask @drybjed. You'll need to use debops to install some of these things. That said, some of these I can answer for you:

 1.  Automysql backups happen daily. You can find them under `/var/lib/automysqlbackup`.
 2. You have to set these up yourself using debops roles (for monit) or by hand.
 3. Firewall is iptables managed by ferm. You can find the rules under `/etc/ferm/ferm.d/`.
 4. Yes, it's on autorenew
 5. Security updates only and it won't auto-restart.

**Comment by DanNeish** [comment]
Great, thanks for your help!
