### ISSUE TITLE
Redirect www to non-www on SSL enabled site

### ISSUE THREAD

**Issue by DanNeish** [carlalexander/debops-wordpress#137]
I have successfully setup my site with LetsEncrypt ssl on the non-www domain. It is automatically redirecting any http requests to https.
How can I redirect www to the non-www?
I need both of the below addresses to redirect to this address: https://example.com
http://www.example.com
https://www.example.com

**Comment by carlalexander** [comment]
It should since [this commit](https://github.com/carlalexander/debops-wordpress/commit/70ebb492417c275d9b174df172039e493d019a93). Make sure to run `debops-update`. Also `wordpress_domain` should be `example.com` and not `www.example.com`.

**Comment by DanNeish** [comment]
I have tested this with the latest devops-wordpress master branch on a fresh server, however it is not redirecting www to non-www. The result is:
http://example.com redirects to https://example.com --> OK
http://www.example.com redirects to https://www.example.com --> INCORRECT, should be http://example.com or https://example.com
https://www.example.com shows an SSL certificate error (because no certificate exists for www) --> INCORRECT, should be https://example.com

wordpress__domain is set to 'example.com'

I have also checked this without SSL enabled and redirect also does not work.

Looking into this further it looks like ansible_domain is set to the TLD, rather than the whole domain. eg. ansible_domain = 'com' instead of 'example.com'. This is probably why the redirect is not being implemented as `wordpress__domain == ansible_domain` will be false.
Should the check be ansible_fqdn instead of ansible_domain?
Making the above changes fixes the issue when not using SSL, however when using SSL the result is:
http://example.com redirects to https://example.com --> OK
http://www.example.com redirects to http://example.com --> OK
https://www.example.com shows an SSL certificate error (because no certificate exists for www) --> INCORRECT, should be https://example.com

**Comment by carlalexander** [comment]
That's weird. `ansible_domain` is supposed to resolve to more than just the TLD. It's supposed to be the top level domain. `ansible_fqdn` is for the fully-qualified domain name like `server.example.com`.

Is it possible that you're using `example.com` in your `hosts` file? I could see that causing this problem. You need to give your server a fully-qualified domain name.

**Comment by DanNeish** [comment]
That was the problem, even though I specifically read the installation guide where it says to use a FQDN for the server such as server.example.com I still somehow didn't do it... 😞
All fixed now 👍
