### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by mosamlife** [carlalexander/debops-wordpress#14]
This is weird  issue i found i just deploy a successful WordPress installation. but i have to import my database backup so i delete the old database. when i delete old database the website is gone i show error every where 

The error is : 

Error 503 Backend fetch failed

Backend fetch failed

Guru Meditation:

XID: 51

Varnish cache server

**Comment by carlalexander** [comment]
This means there's probably a PHP error when Varnish tries to fetch a WordPress page. Can you give the output from the error log? You can find it under `/var/log/nginx`.

**Comment by mosamlife** [comment]
here is the output of error.log file 

2015/08/10 16:18:36 [notice] 35221#0: using inherited sockets from "10;11;"
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:46 [emerg] 35241#0: still could not bind()
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:18:50 [emerg] 35253#0: still could not bind()
2015/08/10 16:20:48 [emerg] 35280#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:20:48 [emerg] 35280#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:20:48 [emerg] 35280#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:20:48 [emerg] 35280#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:20:48 [emerg] 35280#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/08/10 16:20:48 [emerg] 35280#0: still could not bind()
2015/08/10 16:27:49 [notice] 3195#0: signal process started
2015/08/10 16:39:50 [notice] 3372#0: signal process started
2015/08/10 17:12:13 [notice] 4820#0: signal process started
2015/08/10 17:14:11 [notice] 5334#0: signal process started

and this is the output pf thepcbucket.com_erro.log

2015/08/10 16:10:07 [crit] 27508#0: *3 connect() to unix:/var/run/hhvm/hhvm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: thepcbucket.com, request: "GET /2015/08/10/hello-world/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "thepcbucket.com"
2015/08/10 16:26:01 [crit] 1121#0: *1 connect() to unix:/var/run/hhvm/hhvm.sock failed (2: No such file or directory) while connecting to upstream, client: 191.238.236.112, server: *.thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "thepcbucket.com"
2015/08/10 16:27:16 [crit] 1121#0: *4 connect() to unix:/var/run/hhvm/hhvm.sock failed (2: No such file or directory) while connecting to upstream, client: 191.238.236.112, server: *.thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "thepcbucket.com"
2015/08/10 16:28:01 [crit] 3204#0: *1 connect() to unix:/var/run/hhvm/hhvm.sock failed (2: No such file or directory) while connecting to upstream, client: 191.238.236.112, server: *.thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "thepcbucket.com"
2015/08/10 17:21:13 [error] 5340#0: *272 open() "/var/www/thepcbucket.com/wp-content/plugins/yith-woocommerce-wishlist/assets/css/jquery.selectBox.css" failed (2: No such file or directory), client: 127.0.0.1, server: *.thepcbucket.com, request: "GET /wp-content/plugins/yith-woocommerce-wishlist/assets/css/jquery.selectBox.css?ver=4.2.2 HTTP/1.1", host: "www.thepcbucket.com", referrer: "https://www.thepcbucket.com/brand/activeden/?add_to_wishlist=67&action=yith-woocompare-add-product&id=47&_wpnonce=80083b3442"
2015/08/10 17:21:13 [error] 5340#0: *272 open() "/var/www/thepcbucket.com/wp-content/plugins/woocommerce/assets/css/prettyPhoto.css" failed (2: No such file or directory), client: 127.0.0.1, server: *.thepcbucket.com, request: "GET /wp-content/plugins/woocommerce/assets/css/prettyPhoto.css?ver=4.2.2 HTTP/1.1", host: "www.thepcbucket.com", referrer: "https://www.thepcbucket.com/brand/activeden/?add_to_wishlist=67&action=yith-woocompare-add-product&id=47&_wpnonce=80083b3442"
2015/08/10 17:21:14 [error] 5340#0: *272 open() "/var/www/thepcbucket.com/wp-content/themes/pcbucket/assets/css/owl.carousel.min.css" failed (2: No such file or directory), client: 127.0.0.1, server: *.thepcbucket.com, request: "GET /wp-content/themes/pcbucket/assets/css/owl.carousel.min.css?ver=4.2.2 HTTP/1.1", host: "www.thepcbucket.com", referrer: "https://www.thepcbucket.com/brand/activeden/?add_to_wishlist=67&action=yith-woocompare-add-product&id=47&_wpnonce=80083b3442"

**Comment by carlalexander** [comment]
Can you run `service hhvm status`? If it isn't started, can you try `service hhvm restart`?

**Comment by mosamlife** [comment]
i did it but still  same issue :(

**Comment by carlalexander** [comment]
Is hhvm started?

**Comment by mosamlife** [comment]
yes hhvm is running successfully restart

**Comment by mosamlife** [comment]
here is the output of varnish log file

2015/08/10 16:21:01 [error] 35223#0: *72 connect() failed (111: Connection refused) while connecting to upstream, client: 191.238.236.112, server: thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "http://127.0.0.1:6081/wp-cron.php", host: "thepcbucket.com"
2015/08/10 16:21:22 [error] 35223#0: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 122.102.127.79, server: thepcbucket.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:6081/", host: "thepcbucket.com"
2015/08/10 16:21:29 [error] 35223#0: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 122.102.127.79, server: thepcbucket.com, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:6081/phpmyadmin/", host: "thepcbucket.com"
2015/08/10 16:21:33 [error] 35223#0: *77 connect() failed (111: Connection refused) while connecting to upstream, client: 122.102.127.79, server: thepcbucket.com, request: "GET /phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:6081/phpmyadmin/", host: "thepcbucket.com"
2015/08/10 16:22:02 [error] 35223#0: *79 connect() failed (111: Connection refused) while connecting to upstream, client: 191.238.236.112, server: thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "http://127.0.0.1:6081/wp-cron.php", host: "thepcbucket.com"
2015/08/10 16:23:01 [error] 35223#0: *93 connect() failed (111: Connection refused) while connecting to upstream, client: 191.238.236.112, server: thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "http://127.0.0.1:6081/wp-cron.php", host: "thepcbucket.com"
2015/08/10 16:24:01 [error] 35223#0: *95 connect() failed (111: Connection refused) while connecting to upstream, client: 191.238.236.112, server: thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "http://127.0.0.1:6081/wp-cron.php", host: "thepcbucket.com"
2015/08/10 16:24:12 [error] 35223#0: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 85.17.131.209, server: thepcbucket.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:6081/", host: "thepcbucket.com"
2015/08/10 16:24:12 [error] 35223#0: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 85.17.131.209, server: thepcbucket.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:6081/favicon.ico", host: "thepcbucket.com"
2015/08/10 16:25:01 [error] 35223#0: *100 connect() failed (111: Connection refused) while connecting to upstream, client: 191.238.236.112, server: thepcbucket.com, request: "GET /wp-cron.php HTTP/1.1", upstream: "http://127.0.0.1:6081/wp-cron.php", host: "thepcbucket.com"

**Comment by carlalexander** [comment]
What about `/var/log/hhvm/error.log`? Any errors there?

**Comment by mosamlife** [comment]
i can't even access phpmyadmin

**Comment by mosamlife** [comment]
here is the output of hhvm error log 

Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
SlowTimer [3027ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = 'O:8:\"stdClass\":4:{s:12:\"last_checked\";i:1439223107;s:8:\"response\";a:1:{s:19:\"akismet/akismet.php\";O:8:\"stdClass\":6:{s:2:\"id\";s:2:\"15\";s:4:\"slug\";s:7:\"akismet\";s:6:\"plugin\";s:19:\"akismet/akismet.php\";s:11:\"new_version\";s:5:\"3.1.3\";s:3:\"url\";s:38:\"https://wordpress.org/plugins/akismet/\\";s:7:\\"package\\";s:56:\\"https://downloads.wordpress.org/plugin/akismet.3.1.3.zip\\";}}s:12:\\"translations\\";a:0:{}s:9:\\"no_update\\";a:1:{s:9:\\"hello.php\\";O:8:\\"stdClass\\":6:{s:2:\\"id\\";s:4:\\"3564\\";s:4:\\"slug\\";s:11:\\"hello-dolly\\";s:6:\\"plugin\\";s:9:\\"hello.php\\";s:11:\\"new_version\\";s:3:\\"1.6\\";s:3:\\"url\\";s:42:\\"https://wordpress.org/plugins/hello-dolly/\\";s:7:\\"package\\";s:58:\\"https://downloads.wordpress.org/plugin/hello-dolly.1.6.zip\\";}}}' WHERE `option_name` = '_site_transient_update_plugins'
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
SlowTimer [1430ms] at runtime/ext_mysql: slow query: DROP TABLE `wp_commentmeta`, `wp_comments`, `wp_links`, `wp_options`, `wp_postmeta`, `wp_posts`, `wp_terms`, `wp_term_relationships`, `wp_term_taxonomy`, `wp_usermeta`, `wp_users`;
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
SlowTimer [23123ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = '5.21' WHERE `option_name` = 'vcht_version'
SlowTimer [20606ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = '1439228101' WHERE `option_name` = '_transient_timeout__redux_activation_redirect'
SlowTimer [17178ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = '5.21' WHERE `option_name` = 'vcht_version'
SlowTimer [2216ms] at runtime/ext_mysql: slow query: UPDATE `wp_options` SET `option_value` = '5.21' WHERE `option_name` = 'vcht_version'
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5
Finished singleJitRequest 1
Finished singleJitRequest 2
Finished singleJitRequest 3
Finished singleJitRequest 4
Finished singleJitRequest 5

**Comment by carlalexander** [comment]
Did you edit any of the nginx configuration? You should have a fallback to php-fpm as well if hhvm isn't working.

**Comment by mosamlife** [comment]
nup i did not edit any nginx configuration. i just uploaded my database and its working but when i uploaded my ftp files it shows me 503 error

**Comment by carlalexander** [comment]
When I try to connect to the server, I'm redirected to HTTPS. If you didn't change anything, this will cause an issue.

**Comment by mosamlife** [comment]
yes i am using your https config thats it. try to open thepcbucket.com/wp-admin

**Comment by carlalexander** [comment]
You need to remove the https in the URL. See if that works. Or take a look at #1 for a temporary solution until I add support for SSL.

**Comment by mosamlife** [comment]
yes i am using this https configuration i use this code in varnish.thepcbucket.com.conf and https working.

**Comment by mosamlife** [comment]
hey its weird when i delete my themes and plugins its working any idea why this happening ?

**Comment by carlalexander** [comment]
Not sure, there might be an error with one of the plugins. The error logs should show that.

**Comment by mosamlife** [comment]
let me install plugins by one by one

**Comment by mosamlife** [comment]
Got the problem 
this problem cause because of [maintenance mode plugin](https://wordpress.org/plugins/wp-maintenance-mode/). :) 

P.S : All Maintenance Mode plugin not working.

**Comment by carlalexander** [comment]
I tried the plugin on a freshly configured server and couldn't get any errors. Are you still having problems?

**Comment by carlalexander** [comment]
Going to close this. Please update if you're still having the issue.

**Comment by gopinath93** [comment]
Hi guys,
I am using ubuntu LTS and nginx server. I have installed varnish. if i run "varnishstat" in terminal. it is showing some process. I am new to varnish. I am trying to install in localhost. is it possible?

Can u help me guys? I am working on it for 2 days but no response. getting the same error :

Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 3

Varnish cache server

**Comment by kengsub** [comment]
My website is also like that. Please help me fix it: http://www.kengsub.net
