### ISSUE TITLE
Location of the Wordpress Files

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#142]
Hey,

this might seem a little trivial, but just by browsing my droplet via FTP I can't seem to locate the Wordpress files, such as the wp-admin folder for example.

What is the default path where ansible puts this?

**Comment by ghost** [comment]
Never mind, I thought it was under the root user, but turned out it is located under my local user name.
`~/var/www/`

**Comment by carlalexander** [comment]
It's always under `/var/www/{{ wordpress__domain }}` 😄
