### ISSUE TITLE
Site unreachable after Reboot - IPv6 Issue?

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#143]
Hey,

I had to reboot my Droplet in order to apply some settings. My page is no not reachable anymore, the droplet is back up and running. 
I restarted the following:
`sudo systemctl restart nginx`
However, the site still doesn't show up. Is there another service which needs to be restarted? The IP of the droplet did not change, I can still ssh into it using the domain. It is weird that the site is running after debops is done with it's setup, but it doesn't survive a reboot.

Cheers

--Update:
I think this has to do with the IPv6 I am trying to setup this with. Domain records are all fine, but what is the correct setup for the nginx configs?
`netstat -nlp | grep nginx`
shows:
`tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      20632/nginx -g daem`
`tcp6       0      0 :::80                   :::*                    LISTEN      20632/nginx -g daem`

My varnish conf file looks like this:
`server { listen [::]:80 default_server ipv6only=off; .....`
My wordpress conf file:
`server { listen 8080 default_server; .....`

---Update2:
This is so weird, another reboot and it's back. No idea what's going on.

**Comment by carlalexander** [comment]
Did you reboot again to see if it worked a second time? lol

**Comment by carlalexander** [comment]
Is this related to #144?

**Comment by ghost** [comment]
It was indeed, resolved now.
