### ISSUE TITLE
Site becomes unreachable randomly

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#144]
Hey,

so after finally having a copy of the page I want to migrate online on a staging droplet with debops, I was making some changes in Wordpress itself and noticed that the page randomly just becomes unavailable. For example editing a post, and clicking "update" leads to the complete page becoming unavailable.
Anyone having similar experiences? I also noticed this on a fresh vanilla install.

**Comment by carlalexander** [comment]
I've never had that happen. What does the access log or error log say? Do you see your request hit the server?

**Comment by ghost** [comment]
I have narrowed it down to my local machine being the issue here. When the site becomes unreachable, pinging it results in "unkown host", but at the same time a different computer can ping it and all is fine, kinda weird.

**Comment by carlalexander** [comment]
Hmmmm what DNS servers do you use? Maybe try with the [Google ones](https://developers.google.com/speed/public-dns/).

**Comment by ghost** [comment]
The default ones provided by my ISP, just found an article which blame them for some issues.
Posted this issue on superuser, someone suggested something ARP related.

The 'other' computer is on the same network by the way (99% sure they are not changed on the local machine), which contradicts this a little.

**Comment by carlalexander** [comment]
Doesn't matter if it's on the same network. The browser doesn't know that. It still needs to ask the DNS server for the address. :)

**Comment by ghost** [comment]
Okay, good to know :)
So are you suggesting changing the DNS servers on my local machine and see if it works out?

**Comment by carlalexander** [comment]
Yup, I've had this issue before myself. It worked out once I changed the DNS server.

**Comment by carlalexander** [comment]
Did changing the DNS server work?

**Comment by ghost** [comment]
Yes it worked. I'm going to close this.
