### ISSUE TITLE
custom varnish work

### ISSUE THREAD

**Issue by aelsharawi** [carlalexander/debops-wordpress#148]
hello

can I ask you please to optimize varnish on my WordPress-woo commerce website?

it will be a paid job for sure

**Comment by wpbullet** [comment]
If Carl is too busy I can help you out @aelsharawi

**Comment by carlalexander** [comment]
I'd check with @wpbullet @aelsharawi, but you can't open issues asking for help here. It's really for project related problems. You can reach out to me on Twitter if you need help finding someone. 😃
