### ISSUE TITLE
www not working

### ISSUE THREAD

**Issue by georgiemathews** [carlalexander/debops-wordpress#150]
I have SSL on, and entered the domains right in my host file, but cannot get the https://www.example.com -> to https://example.com redirect working. Getting the SPDY error.

**Comment by carlalexander** [comment]
Do you have the real URL of the site so I can check?

**Comment by kclack** [comment]
I have a similar issue, If I try to go to a domain being hosted, I can go with domain.com no issue.  If I do www.domain.com the firewall blocks the site.

trying to add www.domain.com and domain.com in the hosts inventory seems to try to create two different sites hosted on the same server.  The intent was to fix the firewall rules.  

Edit: Was able to resolve this issue by changing the Nginx configuration for the 'www' site to point to the directory for the 'domain.com' site

**Comment by stefangweichinger** [comment]
Should it be wordpress__domain: 'example.com" and then it generates the correct rewrites for "www.example.com" ? I tried that and get an endless loop of redirections.

So I unset wordpress__domain and then "http://example.com" does not work: no forward to www., no correct SSL cert.

I'd love to get these things correctly configured.

**Comment by stefangweichinger** [comment]
additional: does the target host have to be in the [debops__service_pki] group in the inventory or not? I assume, no, according to your docs? Spent quite some time fiddling with getting the SSL certs generated and hit problems.

**Comment by carlalexander** [comment]
You shouldn't need `debops__service_pki` group. The redirect should be created automatically if `wordpress__domain` is the same as `ansible_domain`.

**Comment by stefangweichinger** [comment]
thanks. I repeatedly got errors around resolving the hostname of the target host. Compared with another one, no success. Will report back or consult debops-devs on IRC.

**Comment by stefangweichinger** [comment]
OK, I have 
wordpress__domain: '{{ ansible_domain }}'
instead of your default pointing to '{{ inventory_hostname }}'

In my tests this gave me errors within debops.pki, I have to rerun my tests asap (can't take the site down too often). I'll check back when I have the definitive error message.

**Comment by stefangweichinger** [comment]
update from testing now: Certs now seem OK, but I get a loop of redirections in nginx.

generated varnish.conf :: https://gist.github.com/stefangweichinger/c4da07b8860073b63ff0e7bb976872dd

**Comment by stefangweichinger** [comment]
solved redirect etc manually. Will report back as soon as I understand things :-P

**Comment by stefangweichinger** [comment]
additional feedback: the generated config of your role results in a somehow weaker SSL-Config for the FQDN "example.com", compared to "www.example.com". jwd on debops IRC helped me to write different rewrites. Now I get an A or A+ at ssllabs.com.

plus: had to edit the listen statements to work with both ipv6 and ipv4.

see my conf for reference, I will try to automate that as soon as I can think clearly again :-P

```
# Redirect all traffic from HTTP to HTTPS
server {
        listen 80;
        listen [::]:80;
	server_name www.dupps-selbach.com dupps-selbach.com;

	# Destination redirect base URI
	set $RURI https://www.dupps-selbach.com;
	
	location / {return 301 $RURI$request_uri;}
}

# Redirect non-WWW HTTPS traffic to WWW HTTPS
server {
	listen 443 ssl http2;
        listen [::]:443 http2;

	# NOTE: only to redirect https traffic to the proper domain (including the www.
	server_name dupps-selbach.com;
	return 301 $scheme://www.$host$request_uri;
}

server {

        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;

        ssl_certificate           /etc/pki/realms/dupps-selbach.com/default.crt;
        ssl_certificate_key       /etc/pki/realms/dupps-selbach.com/default.key;
        ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               "EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH"; # TLS cipher suites set: bettercrypto_org__set_b_pfs
        ssl_dhparam               /etc/pki/dhparam/set0;
        ssl_ecdh_curve            secp384r1;
        ssl_stapling              on;
        ssl_stapling_verify       on;
        ssl_trusted_certificate   /etc/pki/realms/dupps-selbach.com/trusted.crt;
        resolver                  213.133.99.99 213.133.100.100 213.133.98.98 valid=300s;
        resolver_timeout          5s;
        add_header                Strict-Transport-Security "max-age=15768000; includeSubDomains";
        add_header                X-Content-Type-Options "nosniff" always;
        add_header                X-Frame-Options "SAMEORIGIN" always;
        add_header                X-XSS-Protection "1; mode=block";
        add_header                Referrer-Policy "same-origin";

        server_name www.dupps-selbach.com;

        include snippets/acme-challenge.conf;

        keepalive_timeout 60;

        access_log /var/log/nginx/varnish.dupps-selbach.com_access.log;
        error_log /var/log/nginx/varnish.dupps-selbach.com_error.log;
        client_max_body_size  32M;

        if ($host != $server_name) {
            return 444;
        }

        location = /nginx_status {
                stub_status on;
                access_log off;
                allow 127.0.0.1/32;
                allow ::1/128;
                allow 172.31.1.100;
                allow 2a01:4f8:c17:1b89::2;
                deny all;
        }

        include /etc/nginx/sites-default.d/*.conf;

        location / {
                proxy_set_header Host              $host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port  443;
                proxy_pass http://varnish;
        }


}

```

**Comment by carlalexander** [comment]
What provider are you using @stefangweichinger?

**Comment by stefangweichinger** [comment]
What provider? The server is located at hetzner in germany (hetzner.de), and it runs debian, provisioned via debops-wordpress ;-)

**Comment by carlalexander** [comment]
Sorry, I meant are you using Digital Ocean, AWS, etc?

**Comment by stefangweichinger** [comment]
No

**Comment by carlalexander** [comment]
Going to close this, but feel free to reopen if you're still having an issue @stefangweichinger 😄
