### ISSUE TITLE
ocsp_verify: False?

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#151]
Currently this is hardcoded in [roles/wordpress/vars/main.yml](https://github.com/carlalexander/debops-wordpress/blob/1a1bc62bbc7c67bc2c61bca4cf7d96d548644b5a/roles/wordpress/vars/main.yml#L234). I did not have an issue with this being enabled by default in DebOps. Maybe it can be rechecked if this is still required and if so maybe a comment why this was done. https://github.com/carlalexander/debops-wordpress/commit/15b563a5f984fd2e10f94f79e1e5c8783485a28e does not explain it.

**Comment by carlalexander** [comment]
I can't remember why, but it's probably because it broke something at the time.

**Comment by carlalexander** [comment]
Couldn't find an issue testing without `ocsp_verify: False` so I removed the option as suggested
