### ISSUE TITLE
README tells to checkout tags/v0.3.1

### ISSUE THREAD

**Issue by stefangweichinger** [carlalexander/debops-wordpress#155]
... but only "git checkout master" works for me as it contains the merged PR fixing latest nginx-issues.
-> maybe update the README ?

**Comment by carlalexander** [comment]
Agreed, I've been trying to wrap up the next release which still needs a lot of documentation. I'll just tag and release it today/tomorrow. I'll finish the documentation before working on the next features.

**Comment by stefangweichinger** [comment]
looking forward to the updated release. prepping a demo for a talk on saturday ;-)

**Comment by carlalexander** [comment]
Sorry, I only go to this today. I had to double check if I could reproduce #156 first.
