### ISSUE TITLE
plugins not installed

### ISSUE THREAD

**Issue by stefangweichinger** [carlalexander/debops-wordpress#156]
following your example I have

$ cat inventory/host_vars/wordpress.example.com/vars.yml 
wordpress__plugins:
  - name: 'akismet'
  - name: 'varnish-http-purge'
  - name: 'redis-cache'

But I don't get them into WP (not visible) in Web GUI.

It seems the include gets skipped:

TASK [wordpress : Check if WordPress is installed] 
ok: [wordpress.example.com]

TASK [wordpress : include] 
skipping: [wordpress.example.com]

otherwise "debops" and "debops wordpress" runs through fine.

could you point me at my mistake?

**Comment by carlalexander** [comment]
Let me test and get back to you on that. It should work.

**Comment by stefangweichinger** [comment]
I commented line 29 in roles/wordpress/tasks/main.yml ... then plugins were installed.

**Comment by carlalexander** [comment]
I just ran a test and I had the plugins install fine. Can you share your `vars.yml`?

**Comment by stefangweichinger** [comment]
tested OK with tags/v0.4.0 now. I think we can close this as obsolete?
