### ISSUE TITLE
Error in TASK [debops.nginx : Assert that no legacy options are used] 

### ISSUE THREAD

**Issue by AlifArnado** [carlalexander/debops-wordpress#159]
Never success finishing `debops wordpress`, always fail... 
- Latest debops
- Digital Ocean [ ubuntu 16.04.2 x64 ] 512mb

first error is related with this issue..
https://github.com/carlalexander/debops-wordpress/issues/132#issuecomment-298219014

after downgrade the python-jinja2, i got this error.
http://imgur.com/a/ZNeqG

**Comment by carlalexander** [comment]
Can you do a checkout of the new `v0.4.0` version to see if you still have the issue?

**Comment by ck1981** [comment]
Hello guys,

I did the below after "debops-update" to work around this issue as I was using v0.3.1 ie the version prior to v0.4.0:

cd ~/.local/share/debops/debops-playbooks/roles/debops.nginx/
git checkout tags/v0.1.9

or

(cd ~/.local/share/debops/debops-playbooks/roles/debops.nginx/ && git checkout tags/v0.1.9)

Sorry but I have not tested to see if the issue still occurs with v0.4.0 but if I get the chance to test it I will post back. Note that I am using GCE however this obviously should have no effect.

Thank you

**Comment by ck1981** [comment]
For me this issue no longer appears in v0.4.0

**Comment by carlalexander** [comment]
What about you @AlifArnado? Are you still having the issue with `v0.4.0`?

**Comment by carlalexander** [comment]
I'm going to close this. Feel free to reopen if you're still having problems @AlifArnado!
