### ISSUE TITLE
Suggested Imporvement: Add cURL support to php

### ISSUE THREAD

**Issue by shawnhooper** [carlalexander/debops-wordpress#16]
Although WordPress doesn't recommend calling cURL directly, and using wp_remote_get instead, there are some plugins and libraries that make use of the native PHP functions, which require the extension.

sudo apt-get install php5-curl

**Comment by carlalexander** [comment]
Good point! I'm surprised it's not there in fact. Oversight on my part. I'll add it over the weekend.
