### ISSUE TITLE
What file should be altered to change the Varnish config?

### ISSUE THREAD

**Issue by BoDonkey** [carlalexander/debops-wordpress#161]
As the title says, I'm not sure where the varnish config is located to change it for woo. Wicked newbie trying to learn, sorry if this is the wrong place to ask this question.

**Comment by carlalexander** [comment]
No worries @BoDonkey! Have you looked at this [wiki article](https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-Varnish)?

**Comment by BoDonkey** [comment]
So you just set the additional params in the inventory/host_vars/wordpress.example.com/vars.yml? Can we also set subdomain params for letsencrypt/PKI there?

**Comment by carlalexander** [comment]
Yup!

**Comment by carlalexander** [comment]
Did this resolve your issue @BoDonkey?

**Comment by carlalexander** [comment]
Going to close this for now. Feel free to reopen if you still have an issue @BoDonkey 😄
