### ISSUE TITLE
cannot update wordpress to newer version

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#166]
perhaps this could be stupid question, but I think it might be useful for future community member who use debops wordpress and love it. the question is 

I cannot update wordpress to a newer version. what should I do?

**Comment by carlalexander** [comment]
I had an issue with WordPress 4.8 as well. Did you press update and nothing happened?

**Comment by ghost** [comment]
Yes! I press update and nothing happened. 

slug: https://www.website.com/wp-admin/update-core.php?action=do-core-upgrade

**Comment by carlalexander** [comment]
You might want to try turning Varnish off (`sudo service varnish stop`) to see if it's the issue. If that doesn't work, you can login and go to your wordpress directory and use wp-cli. (`wp core update`)

**Comment by ghost** [comment]
I solved it using ( **sudo service varnish stop** ) => goes to wordpress dashboard then update.

**wp core update** is not working => 

Updating to version 4.8 (en_US)...
Using cached file '/var/local/cencered/.wp-cli/cache/core/wordpress-4.8-no-content-en_US.zip'...
Unpacking the update...
Error: Could not create directory.
