### ISSUE TITLE
Varnish doesn't restart

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#17]
Ran into an issue where Varnish wouldn't restart at all. This was the error:

```
Running VCC-compiler failed, exited with 2

VCL compilation failed
```

The only mention of a similar issue was on [Server Fault](http://serverfault.com/questions/489296/varnish-fails-to-start-running-vcc-compiler-failed-without-a-compiler-error). This mentions that there was no space to compile the VCL. I couldn't confirm that this was the same issue here. Rebooting the server fixed the issue though.

**Comment by tobeycodes** [comment]
I still get this error when restarting and it's stopping me from clearing the cache. It's a shame there is no helpful error message here. I increased my ram and disk size and the issue remained so I don't think it's running out of space

**Comment by carlalexander** [comment]
Does restarting fix the issue like it did for me? I haven't had it happen again yet.

**Comment by carlalexander** [comment]
Do you still get this error @schrapel? I haven't had it happen to me since then.

**Comment by tobeycodes** [comment]
I honestly haven’t tried restarting since. I’d close it as well and if it pops up again investigate

**Comment by carlalexander** [comment]
Perfect!
