### ISSUE TITLE
issue installing pscrypto on fresh DO droplet

### ISSUE THREAD

**Issue by daniel-s-valencia** [carlalexander/debops-wordpress#172]
Update: I may have misinterpreted the instructions and done a step out of order, I think that doesn't affect this issue however.
-----------------------

When running this command,

`sudo pip install ansible debops passlib pycrypto`

I got this error 'python failed building wheel for cryptography'.

I fixed missing dependency by installing,

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

then ran this again

`sudo pip install ansible debops passlib pycrypto `

successfully.

**Comment by carlalexander** [comment]
Does it work if you run this command before `pip`: 

```
sudo apt-get install build-essential libssl-dev libffi-dev python-pip python-dev git
```

**Comment by carlalexander** [comment]
Are you trying to install debops on a DO droplet?

**Comment by daniel-s-valencia** [comment]
> Does it work if you run this command before pip: sudo apt-get install build-essential libssl-dev libffi-dev python-pip python-dev git

Yes, thank you that worked.
