### ISSUE TITLE
Deploying specific changes only?

### ISSUE THREAD

**Issue by inspiredearth** [carlalexander/debops-wordpress#175]
Hello,
Is there a way to deploy only specific changes made on the Ansible controller?
For instance, I wanted to activate SSL on the primary domain of one of my sites.
I thought (wrongly) that running just `debops wordpress` would only push out changes to the wordpress configuration, not anything related to the Nginx and varnish config, etc.

Is there a way I could have specified for ONLY the changes to Wordpress to deploy?

**Comment by carlalexander** [comment]
Running `debops wordpress` again after the initial setup isn't always guaranteed to work. For example, not everything related to SSL gets recreated if you run it again. In general, in the wiki, I'll mention what command to use to push the changes out. You can also make use of the tags in the role.

**Comment by sheatsb** [comment]
For SSL, I ran into the same issue, Certbot didn't get installed and I ended up with a self-signed cert when I set `wordpress__ssl: True` on the second playbook runs.

I ended up installing Certbot for Nginx and running it with no issues.

**Comment by carlalexander** [comment]
For SSL, you have to go delete the realm in the `/etc/pki/realms` directory before running it again.

**Comment by carlalexander** [comment]
Did this work for you @sheatsb?

**Comment by sheatsb** [comment]
@carlalexander It did eventually - I had to re-run on a clean server.

**Comment by inspiredearth** [comment]
Sorry about not responding to your answers to my questions Carl. I got busy on  other projects. Just revisiting this now. I'll be taking another look at deploying the SSL side of things over the holidays. (summer, in New Zealand)

**Comment by carlalexander** [comment]
Closing this. Feel free to reopen if something is still going on. 😄
