### ISSUE TITLE
invalid key specified: -----BEGIN PGP PUBLIC KEY BLOCK-----"

### ISSUE THREAD

**Issue by calvez** [carlalexander/debops-wordpress#184]
ssh key added, fqdn ok, ssh ok, and install fails all the time. 
Brand new linode.
I don't know what to do. 
Any suggestion?

failed: [fr3.clvsrv.xyz] (item={'name': 'root'}) => {"failed": true, "item": {"name": "root"}, "msg": "invalid key specified: -----BEGIN PGP PUBLIC KEY BLOCK-----"}

**Comment by calvez** [comment]
I had to change the local user to root and rebuild the server with root user, otherwise it didn't work.
now it's ok.
No matter if I added the local user to the server with keys, or root user with keys. SSH doesn't care about users. 
So running debops with root user from the local machine solved the problem

**Comment by carlalexander** [comment]
Hey @calvez, I'm sorry that I don't have a detailed walkthrough for Linode yet. It's on my todos.

Is the issue resolved?

**Comment by carlalexander** [comment]
Closing for now, but feel free to reopen if you have any new information @calvez 😃
