### ISSUE TITLE
Redis mixes up website URLs

### ISSUE THREAD

**Issue by jstoeffler** [carlalexander/debops-wordpress#189]
So I followed the instructions to install multiple sites on the same server, but the 3rd one has a problem: as soon as I install the redis plugin, it redirects to the 1st one.

Any idea how to fix this?

**Comment by jstoeffler** [comment]
Ok, so I found the solution, I needed to set a different cache key salt for each website by adding this to wp-config.php: `define( 'WP_CACHE_KEY_SALT', 'websiteX_');`

**Comment by carlalexander** [comment]
I'm going to reopen this as a legitimate bug. Thanks for this @jstoeffler!
