### ISSUE TITLE
git push crashes php5-fpm

### ISSUE THREAD

**Issue by shawnhooper** [carlalexander/debops-wordpress#19]
I have a bare repo on my server that I push to as a remote.  In the post_receive hook, it copies the contents of the repo to the /var/www/<domain>/ folder.

Most of the time when doing this, I have to restart the php5-fpm service or I get a 500 series error when going to the site. 

Here's the contents of my post-receive:

```
#!/bin/bash
echo "Copying site content to web root..."
git --work-tree=/var/www/example.com/ --git-dir=/var/repo checkout -f
cd /var/www/example.com/
composer update --no-dev
echo "Setting File Ownership"
chown www-data:www-data /var/www/example.com/* -R
echo "Clearing Varnish Cache..."
varnishadm "ban req.url ~ /"
echo "Deployment Complete"
echo "Restart PHP5-FPM"
service php5-fpm restart;
touch /var/www/example.com/index.php
echo "Done"
```

Restarting php5-fpm and touching the index.php where both attempts at fixing this problem - but neither have been reliable.  I still have to SSH in and restart the service.

**Comment by carlalexander** [comment]
Is there anything in the error logs? 500 series error should show up in theory.

**Comment by shawnhooper** [comment]
I'll check on my next push.  I assume it's the nginx logs I'm looking at?

**Comment by carlalexander** [comment]
Yep!

**Comment by carlalexander** [comment]
Is this still happening @shawnhooper?

**Comment by carlalexander** [comment]
I'll close this for now. You can reopen a new one if it happens again @shawnhooper.
