### ISSUE TITLE
https pages serving http contents

### ISSUE THREAD

**Issue by codegranite** [carlalexander/debops-wordpress#190]
Hi,

I manage to setup a page successfully with this debops setup on live together with the ssl when I access the site using https protocol it does load but files like css and js are loading via http I tried to dig within the configuration but don't know what is causing this behaviour the only thing I see is that varnish is being configured to listen to port 443 and nginx to port 8080 and that is all I knew while checking the configuration is there anything else that I might be doing wrong?

BR

**Comment by carlalexander** [comment]
Can you check the `home_url` and `site_url` of your WordPress site? It's possible they might be http. Not sure why, but I've seen that when that happened.

**Comment by codegranite** [comment]
I tried to rerun `debops wordpress -u root` from my machine but now nginx is not starting I tried to check for the error and this is what I only see:

```
Nov 16 01:06:32 www nginx[29753]: nginx: [emerg] PEM_read_bio_X509_AUX("/etc/pki/realms/www.codegranite.com/default.crt") failed (SSL: error:0906D066:PEM routi
Nov 16 01:06:32 www nginx[29753]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 16 01:06:32 www systemd[1]: nginx.service: Control process exited, code=exited status=1
Nov 16 01:06:32 www systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.

```

I already configure my manual ssl certificate on my debops setup as instructed here https://github.com/carlalexander/debops-wordpress/wiki/How-to-secure-your-WordPress-site#a-note-about-securing-your-wordpress-site when this happened previously I request the reissue of the ssl and it did work well and after I rerun again due to contents being loaded as http the nginx won't start again with the error sorry I thought rerunning the debops wordpress -u root would fix the issue
