### ISSUE TITLE
Support for Python3? Varnish Fatal Error 

### ISSUE THREAD

**Issue by isaiaholoyede** [carlalexander/debops-wordpress#198]
Does debops-wordpress support Python 3? I upgraded my python recently using homebrew and it is now pointing to Python 3. Afterward, when I try to use debops-wordpress to set up a fresh WordPress installation, I have been getting lots of warning and then this fatal error. The certificate created has also been local-signed instead of the Letsencrypt one. I got the fatal error below also.

TASK [varnish : Configure default.vcl for Varnish] ****************************************************************************************
fatal: [adam.rccgoha.org]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}

**Comment by carlalexander** [comment]
I'm not sure about Python3 support. That's more a question for @drybjed who maintains the larger DebOps project.

**Comment by drybjed** [comment]
Hi. Currently DebOps scripts should work on Python 3, although I haven't tested that extensively. You're welcome to help, of course.

The issue above seems to be due to the `varnish` role in `debops-wordpress` repository using the `iteritems()` method. These need to be switched to `items()` to work under Python 3.

**Comment by carlalexander** [comment]
Ah ok! So I guess I need to get on it and make sure I'm python 3 compatible! 😂

**Comment by carlalexander** [comment]
I'll fix this as part of #201

**Comment by carlalexander** [comment]
I haven't tested Python 3. But I updated the wiki to make sure Python 2 gets installed.
