### ISSUE TITLE
Support for Bionic Beaver

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#199]
New version of Ubuntu LTS is [coming out next month](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule). Ensure that everything works and fix issues with it.

**Comment by stefangweichinger** [comment]
Progress? I have to start two new wp vms soon and would like to use latest LTS if possible.

**Comment by carlalexander** [comment]
I'm in Europe travelling for the next month. I don't expect to be able to take a look at this before July.

**Comment by stefangweichinger** [comment]
have fun

**Comment by carlalexander** [comment]
I started working on this. Running into issues with the `bootstrap` role and the `php` role so far. I'll need to create tickets with DebOps about it.

**Comment by carlalexander** [comment]
Fixed [two](https://github.com/debops/debops/pull/413) [issues](https://github.com/debops/debops/pull/414) with `debops.php`. This solved all the compatibility issues on the DebOps side. I need to work on fixing issues inside the project. 

So far, there's a minor PHP pool configuration error. The larger issue is updating the Varnish configuration since we're moving from Varnish 4.1.1 to Varnish 5.2.1. The old configuration file doesn't work anymore and crashes Varnish.

**Comment by carlalexander** [comment]
Released a new version (`v0.5.0`) just now which runs on bionic after doing a bunch of testing. It should also be backwards compatible with Xenial, but I probably won't support it for much longer once Bionic becomes standard.
