### ISSUE TITLE
Support Bedrock

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#2]
Supporting bedrock should just be a question of adding additional roles and creating a `bedrock.yml` playbook.

**Comment by storm2k** [comment]
Given that Bedrock already has its own well established project to do everything you're doing here (Trellis), this is most unnecessary.

**Comment by carlalexander** [comment]
This issue is more for myself! :smile: 

I want to have a bedrock compatible setup for upcoming projects. bedrock-ansible has no plans to support DebOps (since they're MIT) and they're building out all the roles themselves.

They also don't support Varnish and they opted for memcached instead of Redis.

**Comment by carlalexander** [comment]
The role refactor to support Bedrock is pretty much done, but [this issue](https://github.com/debops/ansible-php/issues/28) with `debops.php` is a block. I either need to raise the `memory_limit` for all PHP or I can't run the Composer install.

**Comment by carlalexander** [comment]
Got the chance to wrap this up tonight. DebOps will now set up a Bedrock project if you give it this option:
```yml
wordpress__install_type: 'bedrock'
```

By default, this isn't going to be super useful since you can't update anything. That's why I also created a [template project](https://github.com/carlalexander/debops-bedrock-template) that you can use with Deployer to help with this [issue](https://github.com/carlalexander/debops-wordpress/issues/102). 

That said, there's an issue with deploys that I still need to work through. I get a white screen after a deploy until I log into the admin. Not sure why that is yet.

But besides that, this is working now. I just need to document it.

**Comment by carlalexander** [comment]
[Wiki page](https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-a-server-for-a-Bedrock-project) is done. I'm going to update it with the template project stuff once I've written the documentation for deployments.
