### ISSUE TITLE
Rocketeer SSH

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#20]
When I try to connect to the server via Rocketeer I get the following error. If I try to connect via SSH it works fine. If I try to connect via Rocketeer before installing debops-wordpress it connects fine (albeit tells me a lot of dependencies like php, composer, etc are not installed). I know there ideally should be a deploy user to handle this but there has to be some variable/setting changed during the installation process that stops Rocketeer connecting. 

```
PHP Notice:  No compatible key exchange algorithms found in /Users/tobyschrapel/.composer/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1359

Notice: No compatible key exchange algorithms found in /Users/tobyschrapel/.composer/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1359

  [Rocketeer\Exceptions\ConnectionException]                                                                                                       
  Unable to connect to remote server.                                                                                                              
  With credentials:                                                                                                                                
```

On a side note I've created a task to push/pull the db and uploads folder via rocketeer that looks ready to go.

**Comment by drybjed** [comment]
@schrapel Hi. `debops-wordpress` uses [DebOps sshd role](https://github.com/debops/ansible-sshd/) to manage OpenSSH server. Recently I changed it so that suggested ciphers from [cipherli.st](https://cipherli.st/) are used by the OpenSSH server. They should work on recent OpenSSH versions, so I suggest that you try upgrading your OpenSSH client.

**Comment by tobeycodes** [comment]
@drybjed I've updated OpenSSH (using https://mochtu.de/2015/01/07/updating-openssh-on-mac-os-x-10-10-yosemite/) and verified it's working but I still get the same error.

I'm not sure if OpenSSH would be the problem since connecting via SSH in terminal works fine it's just when the Laravel SSH component tries to connect it doesn't work

**Comment by drybjed** [comment]
Perhaps Laravel SSH component is too old? I suppose if you really need to, you can change the default `sshd_*` variables to allow more ciphers by setting them in Ansible inventory, but I would look for making the software work with current ones instead.

**Comment by tobeycodes** [comment]
I think it's the phpseclib library that is probably too old, but honestly this is getting way over my level of competence. I'm guessing this is somewhat relevant: https://github.com/phpseclib/phpseclib/issues/676

Where the code breaks: https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SSH2.php#L1359

Is there a easy way to allow more ciphers to an existing server? Otherwise I will probably have a look at using Capistrano instead

**Comment by drybjed** [comment]
Sure, if algorithm maps are not set, specific lists of algorithms are not defined in `/etc/ssh/sshd_config`, which means that OpenSSH server uses the default ones. Set this in inventory:

```
sshd_ciphers_map: {}
sshd_kex_algorithms_map: {}
sshd_macs_map: {}
```

**Comment by tobeycodes** [comment]
In the vars.yml file? I tried that and re-ran debops -u root but doesn't look like the sshd config changed. It's widely different from the default sshd_config and actually only has 4 lines that are not commented out.

I'll give it a go on a fresh server

**Comment by carlalexander** [comment]
Is there multiple cipher options for `debops.sshd` like `debops.nginx` @drybjed? Maybe we could see if the weaker cipher suite works with Rocketeer?

**Comment by drybjed** [comment]
@schrapel I would put these variables in your Ansible inventory, depending on how large the scope you want. All of your hosts? Put it in `ansible/inventory/group_vars/all/sshd.yml`. Just a group? Put it in `ansible/inventory/group_vars/group_name/sshd.yml`. Only a specific host? Put it in `ansible/inventory/host_vars/hostname/sshd.yml`.

@carlalexander There are no lists of ciphers algorithms to choose from since I haven't seen any good lists around, do you have any suggestions? Current algorithm lists depend on what OpenSSH version you are setting up. If you don't want them, just reset the dictionaries like I showed before so that OpenSSH will use its own defaults, or provide your own list of ciphers depending on an OpenSSH version you use.

**Comment by carlalexander** [comment]
There's a link on cipherli.st that switches the ciphers to something else for older browser support. I can't to it because it's just jQuery, but here are the ciphers he mentions:

```
EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
```

It's worth trying out to see if works here. I'm sure someone else is going to run into issues with modern ciphers.

**Comment by drybjed** [comment]
I'm not sure if OpenSSH understands list of ciphers in this format, here's an example set of ciphers and algorithms: https://security.stackexchange.com/questions/25662/openssh-default-preferred-ciphers-hash-etc-for-ssh2

**Comment by carlalexander** [comment]
Oh, I see! I'll look into it.

**Comment by tobeycodes** [comment]
Using the default ciphers worked fine, so thank you for your help on this. Few other issues cropped up but I'm working through them and will document it all for anyone that wants to do this also.

**Comment by tobeycodes** [comment]
For example, not sure if it's intentional but mcrypt is installed but not enabled by default. Perhaps consider adding the following

```
sudo php5enmod mcrypt
```

**Comment by carlalexander** [comment]
What do you mean not enabled?

**Comment by tobeycodes** [comment]
As in one of the debops scripts installs mycrpt using 

```
sudo apt-get install php5-mcrypt
```

But the command to enable it was run. In the same way this would have been run to enable rewrites

```
sudo a2enmod rewrite
```

This is probably getting a bit out of scope for this issue though

**Comment by carlalexander** [comment]
Yeah. Maybe open another issue about it so I can look into it

**Comment by tobeycodes** [comment]
I closed this because the phpseclib library was updated

https://github.com/phpseclib/phpseclib/pull/714
