### ISSUE TITLE
Migrate to DebOps monorepo

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#201]
DebOps now uses a [monorepo](https://github.com/debops/debops/) instead of managing roles using `debops-update`. Old roles aren't being maintained anymore and it looks necessary to fix issues like [the one with Let's Encrypt](https://github.com/carlalexander/debops-wordpress/issues/200).

**Comment by drybjed** [comment]
Actually, you shouldn't really need to do anything special to do this. If you install recent version of `debops` Python package from PyPI, and run `debops-update`, it will download the DebOps monorepo automatically (in the next version even that won't be needed). All of the `debops-*` commands work as before, so no need to change the initial setup.

You might want to pay attention to the [DebOps changelog](https://docs.debops.org/en/latest/news/changelog.html) and the [upgrade notes](https://docs.debops.org/en/latest/news/upgrades.html) to see if there are any changes that might concern DebOps for WordPress. Apart from that, most of the things should work the same as usual. Even [your contributions](https://github.com/debops/debops/commits?author=carlalexander) to the project were preserved in the monorepo. :-)

**Comment by carlalexander** [comment]
This worked exactly as @drybjed described. I'd like to be able to lock debops to a version eventually, but that might never be possible.
