### ISSUE TITLE
my computer broke when updating, Now what to do?

### ISSUE THREAD

**Issue by 8hxhjd** [carlalexander/debops-wordpress#203]
my mac recently went corrupt while updating. now I have only debops folder and ssh folder backup. I went into the debops directory, but I cannot use any "debops" command. 

I use digital ocean for server, and the wordpress website still running normally. 

I can ssh using root@website.com

I can NOT use debops command.

what should I do?

**Comment by carlalexander** [comment]
Is this still an issue? I need the output from Ansible to know more.

**Comment by carlalexander** [comment]
Closing this. Please reopen if you still have issues @8hxhjd 😄
