### ISSUE TITLE
Installing debops

### ISSUE THREAD

**Issue by ghost** [carlalexander/debops-wordpress#204]
If you follow the instructions for installing ansible and debops in https://github.com/carlalexander/debops-wordpress/wiki/Installation on either Ubuntu 16.04 or 18.04 you will get a compilation error trying to build python-ldap. This is discussed in this debops issue: https://github.com/debops/debops/issues/385.

The workaround is to run the following command:
`
sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev

`
The documentation should probably be updated.

**Comment by carlalexander** [comment]
Are you saying that this:

```console
$ sudo apt-get install python-pip python-dev git
````

should become this:

```console
$ sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev
```

Is that the solution @drybjed?

**Comment by ghost** [comment]
It worked in my environment but should probably be tested in other
environments.
