### ISSUE TITLE
Inconsistence with required Ubuntu version

### ISSUE THREAD

**Issue by jstoeffler** [carlalexander/debops-wordpress#210]
So I had troubles provisionning a server on Vultr using 16.04 LTS 
 as instructed here: https://github.com/carlalexander/debops-wordpress/wiki/Creating-a-server ,

The problems were solved when I followed the Vultr instructions that say to use 18.04 x64  https://github.com/carlalexander/debops-wordpress/wiki/Create-a-Vultr-cloud-compute-%28VC2%29-instance

So I think the documentation needs update ?

**Comment by carlalexander** [comment]
Thanks for that @jstoeffler. Updated the wiki page to say 18.04 LTS 😄
