### ISSUE TITLE
Make sure everything works with DebOps 1.0.0

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#212]
DebOps released their version 1.0.0 milestone this week. I want to make sure everything is up to date and working with it.

**Comment by carlalexander** [comment]
I've done some preliminary testing. The `wordpress` role will need to get reworked. DebOps doesn't use dependencies anymore so a lot of that needs to move to the `wordpress` playbook instead.

**Comment by drybjed** [comment]
I think that all you would need to do is move stuff from the `wordpress/meta/main.yml` "dependencies" list to the playbook, the only roles you should leave there are `debops.secret` and / or `debops.ansible_plugins` if you use these roles in the `wordpress` role.

**Comment by carlalexander** [comment]
Yeah, that's the plan. I also need to add all the dependent stuff as needed. I was going to look at all the playbook for each service.

**Comment by carlalexander** [comment]
Wrapped all the work for this. The new `0.6.0` release is compatible with the DebOps 1.0.0 release. Will need to do a pass at the documentation.
