### ISSUE TITLE
FAILED! => {"msg": "'pki_env_secret_directories' is undefined"}

### ISSUE THREAD

**Issue by wknechtel** [carlalexander/debops-wordpress#216]
Hello!  I'm a n00b to debops, so please forgive me if I'm missing something obvious.  I'm walking through the "Configuring your server" portion of the wiki, and keep slamming into this error when running `debops wordpress`: 

TASK [debops.secret : Create secret directories on Ansible Controller] ************************
fatal: [myhostname]: FAILED! => {"msg": "'pki_env_secret_directories' is undefined"}

The `debops bootstrap -u root` and `debops` commands seem to run just fine.  This is on a fresh install of everything - new server, new debops (tag v0.6.0), the works. At first I thought it was somehow perhaps my WSL instance messing with me, but then I spun up a new VM install of 18.04 LTS, installed debops wordpress there, and hit the same error.

Any insight would be most appreciated.

**Comment by yazzou** [comment]
Hi got the same error on a fresh install Debian 10 running as a VM

**Comment by carlalexander** [comment]
I'm a bit swamped this week with the conference I'm organizing. I hope to take a look at this next week. Sorry for the delay :)

**Comment by krodik** [comment]
Hi, has anyone figured out the fix to this issue? Thank you.

**Comment by carlalexander** [comment]
Sorry, I haven't followed up on this. Are you building a website with `wordpress__ssl` set to `false`?

**Comment by krodik** [comment]
no, `wordpress__ssl` is set to `True`.

**Comment by carlalexander** [comment]
Can you confirm that the step "Prepare debops.pki environment" is running? That's the step that sets that variable.

**Comment by krodik** [comment]
This is the output. Just now,  trying a fresh install.
`TASK [debops.pki/env : Prepare debops.pki environment] ******************************************
ok: [www.domain.do]`

Side note: I have a bunch of `[WARNING]: Could not match supplied host pattern, ignoring: ...` I didn't notice it before.

**Comment by thecreed** [comment]
this issue was also reproduced in my env:
ansible is running from fedora 29 with venv, 
VM is running `Ubuntu 18.04.3 LTS`

-- solved after changing:
roles/wordpress/defaults/main.yml
+wordpress__ssl: True

**Comment by carlalexander** [comment]
Released `v0.6.1` with a fix. I've also gone ahead and made `wordpress_ssl` on by default as well because at this point it should be.

Sorry for the delay 😓
