### ISSUE TITLE
 ansible task  "Install PKI packages" failed

### ISSUE THREAD

**Issue by thecreed** [carlalexander/debops-wordpress#217]
`TASK [debops.pki : Install PKI packages] **************************************************************************************************************************************************************************
fatal: [eslutsky.com]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ (True if ((ansible_all_ipv4_addresses|d([]) + ansible_all_ipv6_addresses|d([])) | ipaddr(\"public\") and pki_default_domain) else False) | bool }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: The ipaddr filter requires python's netaddr be installed on the ansible controller"}
`
solved by `pip install netaddr` on the deployment

**Comment by carlalexander** [comment]
Can you clarify where you installed `netaddr`? Was it on the `eslutsky.com` server?

**Comment by thecreed** [comment]
nope .. on the ansible controller node.

**Comment by carlalexander** [comment]
Update the docs. Thanks! 👍
