### ISSUE TITLE
connection to hhvm.sock failed

### ISSUE THREAD

**Issue by Ichag** [carlalexander/debops-wordpress#22]
After installation of a fresh installed debops-wordpress on a digitalocean droplet my error log is going to filled with the following error message.
The site works in general but some times some page are don't render completly especialy during installation of plugins the page stops with a whitescreen.

> 2015/09/30 17:29:30 [crit] 1473#0: *55947 connect() to unix:/var/run/hhvm/hhvm.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: example.com, request: "HEAD /
> HTTP/1.1", upstream: "fastcgi://unix:/var/run/hhvm/hhvm.sock:", host: "example.com"

**Comment by carlalexander** [comment]
The only thing that stands out is the `server: example.com`. Is it possible that there's a placeholder value in your configuration still? The whitescreen issue could be related to [this](https://github.com/carlalexander/debops-wordpress/issues/13). We'd have to see once the other issue is fixed.

**Comment by Ichag** [comment]
Oh sorry, I replaced the real servername with example.com.
I will do some testing later in a virtualbox for more informations

**Comment by carlalexander** [comment]
Did it work?

**Comment by Ichag** [comment]
No, not yet. I have kickstarted a few maschines and deployed the playbook on it. It is always the same error mesage flooding my log.

**Comment by carlalexander** [comment]
Sorry, I haven't followed up on this. Did you ever get this to work?

**Comment by ejamesc** [comment]
Can confirm this issue is happening for me as well. Attempting to debug.

**Comment by carlalexander** [comment]
Can you post the config file you're using to configure your server?

**Comment by carlalexander** [comment]
I'm going to close this for now. If this is still happening, please reopen with a bit of details so that I can troubleshoot with you.
