### ISSUE TITLE
Merge role wpcli into the wordpress role.

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#24]
I will probably do this during rework and make it optional. Any thoughts?

**Comment by carlalexander** [comment]
A lot of this was designed with the idea that @drybjed could merge what he wanted upstream. Someone might want just WP-CLI and not a full WordPress installation. Or they could have it as a dependency in their own WordPress role.

For those reasons, I'm biased towards keeping it seperate. The goal of the `wordpress` role is to wire all these dependencies together like `debops.gitlab` does. This means that the role shouldn't install anything itself (besides WordPress). The dependencies should handle all lof that. I plan on doing composer that way as well when I start working on Bedrock.

Did you have a specific reason for wanting to merge it?

**Comment by ypid** [comment]
Pro merging:
- Super simple role by itself
- The command could be used to further automate the installation, see https://github.com/debops/ansible-owncloud/pull/11 (not sure about this as I am just diving into wordpress setup)

Contra merging:
- Others can not simply use it as a single role (which they will not do anyway when the thing is not on Galaxy but just write it themselfs again like you did :smile: )
- There is a better role on Galaxy which does this, and only this, the proper way: https://github.com/MatthewMi11er/ansible-role-wpcli/blob/master/tasks/main.yml

Result: Merging

**Comment by carlalexander** [comment]
I don't understand "The command could be used to further automate the installation". Shouldn't it not change anything? The dependency will install it before using the role. You should be able to run commands anyways.

I'm installing WP-CLI the [same way that WP Engine does](https://github.com/wpengine/hgv/blob/master/provisioning/roles/wp-cli/tasks/main.yml). The goal of the mercury project is to mirror their production servers. I'm assuming they didn't do those extra steps for fun. :smile: I could always ask them why they do it though if that's an issue.

I realize that no one can use it as a single role at the moment. This is a limitation of all my roles (like Varnish). I'd rather work on than making that possible as opposed to merging it. In the long run, the goal would be to extract more roles out so they can be used by others.

**Comment by ypid** [comment]
I will come back to that when I am actually locking into it. I just wanted to discuss this up front.

**Comment by ypid** [comment]
All right, I will leave it a separate role :smile: but when this is merged into the DebOps project, it will be the smallest role by far ;-)

**Comment by carlalexander** [comment]
That's fine. I still think it makes more sense this way. :smile:
