### ISSUE TITLE
Remove swap from repo.

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#25]
Drop the current `swap` role. There are better roles out there. You can even include them in this git repo via submodules.

After a quick review of the roles on Galaxy, [`tersmitten.swapfile`](https://github.com/Oefenweb/ansible-swapfile) looks the most promising.

**Comment by drybjed** [comment]
@ypid I like this role as well. After some cleanup and better defaults (like for example, create a swap 2x the size of RAM if RAM < 4 GB, else create say, 2 GB swap, and configurable swapfile name) it could be implemented in DebOps. I don't want to add it directly to the project without author's permission, but I like ideas implemented in it.

**Comment by ypid** [comment]
Sounds good.

**Comment by carlalexander** [comment]
Yep, I want to remove it, but wanted to use a debops role for it. I forget where me and @drybjed talked about it though. I left it as is for now. 

I'm not sure how debops handles external galaxy dependencies though. Does it support them? I'm wary of adding steps for the user to use this project. It's already too many steps in general. I want to [improve it in the long run](https://github.com/carlalexander/debops-wordpress/issues/11).

**Comment by drybjed** [comment]
@carlalexander `debops` scripts don't really care about Ansible Galaxy roles or their dependencies. That is, as long as the roles are installed somewhere within Ansible `roles_path`, they should be available to other roles and playbooks.

**Comment by carlalexander** [comment]
Right so it's another step for users

**Comment by ypid** [comment]
`ansible-galaxy install` might come in handy.

**Comment by carlalexander** [comment]
I saw `debops.swapfile` go through a few days ago. We'll be able to migrate to it.
