### ISSUE TITLE
Installing WordPress from distribution

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#27]
At least in the Debian community some install wordpress via apt (there was a short poll in a DebConf15 talk and most of the people there install wp via apt :) ). Did you think about this?

https://packages.debian.org/search?keywords=wordpress
http://packages.ubuntu.com/search?suite=vivid&searchon=names&keywords=wordpress

**Comment by carlalexander** [comment]
The main thing that sticks out is that the stack looks completly different (Apache, MySQL, no Varnish).

How would we configure all the different components to work together? How would we handle multisite vs single site? SSL? Configure everything after the apt package? Still doesn't handle the stack mismatch very well though.

Or did you mean converting all of this into a package?

**Comment by ypid** [comment]
No, I meant to use the unmodified wordpress package from Debian. I am not sure how the Multisite setup could be done there. Everything else should be double.

**Comment by carlalexander** [comment]
These packages don't seem to update fast enough either. They're three major releases behind (WordPress doesn't use semantic versioning). I'm going to continue with installing using WP-CLI.
