### ISSUE TITLE
wordpress_url is not a url.

### ISSUE THREAD

**Issue by ypid** [carlalexander/debops-wordpress#28]
https://en.wikipedia.org/wiki/Uniform_Resource_Locator#Syntax

Sorry, but I just had to link to this https://www.youtube.com/watch?v=2Tvy_Pbe5NA&t=2m44s

Other DebOps roles use a list like `wordpress_domain` for this.

**Comment by carlalexander** [comment]
I'm not sure about this one. I'm aware of the distinction here. :stuck_out_tongue: 

That said, we also have to maintain a language that's understandable to the people that will use this project. They might not know the finer distinction between URL components vs just an URL. For them, `wordpress_url` is what you see everywhere. 

That said, this might the best time to do a breaking change like this.

**Comment by ypid** [comment]
All right. It’s ok when the users don’t know what an URL is. We can just add more documentation to the defaults file or the wiki in that case.

> That said, this might the best time to do a breaking change like this.

Sounds good. All (breaking) changes are documented here: https://github.com/ypid/debops-wordpress/blob/rework/roles/wordpress/CHANGES.rst

**Comment by carlalexander** [comment]
Yep, that's fine!

**Comment by carlalexander** [comment]
Can you make a standalone PR for this? I'll merge it right away.

**Comment by carlalexander** [comment]
This will be included in the group of commits around #29.
