### ISSUE TITLE
Installing extra dependencies

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#38]
I'm finishing up my config for Rocketeer. I've written a custom task that'll automatically run the build process for gulp but this means the dependencies need to be installed on the server. Currently I've ssh'd into the server and installed this manually. How easy would it be for me to extend debops to run these commands during the installation process? I'm sure this is a pretty basic question, but I really don't know much about Ansible/DebOps
1. https://getcomposer.org/doc/00-intro.md#globally
2. https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server#how-to-install-using-nvm
3. npm install -g gulp bower

I'm going to make sure this repo also has great documentation. You can have a look at how it's started to be put together here: https://github.com/schrapel/wordpress-deploy/wiki/Configuring-DebOps

**Comment by ypid** [comment]
I would recommend to create an extra role for this. For the NodeJS stuff you can use [debops.nodejs](https://github.com/debops/ansible-nodejs) as role dependency and use the npm module to install bower and gulp.

**Comment by tobeycodes** [comment]
You're right on the debops.nodejs stuff, looks like I can define the global modules for bower / gulp at the end of this file https://github.com/debops/ansible-nodejs/blob/master/defaults/main.yml

Also, there appears to be a debops for composer too but it does look half finished
https://github.com/barraponto/debops.composer

There are also a bunch of things just for ansible https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ansible%20composer

Anyway I'm gonna have to do some further reading as this is all way over my head right now. I don't know where to begin

**Comment by ypid** [comment]
Just to clarify, you don’t need to use `nodejs_npm_global_packages` to install the npm dependencies (in case of role dependencies). This role can be used to ensure that NodeJS is installed. Since there is an npm module in Ansible, you can use that directly.

**Comment by carlalexander** [comment]
I plan on tackling some this soon (after I'm done with all of @ypid's PRs :stuck_out_tongue:). The next feature I want to work on is Bedrock + Capistrano which should have some overlap with this.

**Comment by tobeycodes** [comment]
I personally don't see the benefit in having a bedrock role. Once you can deploy from Capistrano or Rocketeer, you would assume that the repo contains Bedrock anyway so it's just case of running a deploy once the server is installed. The only thing I can see a bedrock role is installing something that's going to get overwritten by a deploy anyway. Or did you plan something else?

The way I do it at the moment is once I've installed a server I just remove all the files from `/var/www` and then run a deploy. Then I add my .env file to the shared folder configured with the db credentials created by debops.

**Comment by carlalexander** [comment]
It wasn't going to be a role as much as a separate playbook `bedrock.yml`. You might be right and it's not necessary. I just have to see what we need to get from point A to B like I did for SSL. Might just be configuration, changes to DebOps roles and/or documentation.

The goal is to run two commands and you can do `cap deploy` or the equivalent Rocketeer command.

**Comment by tobeycodes** [comment]
I just pushed up my Rocketeer config. And wrote a lot of my notes in my head about changes that need to be made. It's all a bit of a mess but as long as you follow it one command deploys work. 

I'm going to work on refactoring and improving the code but more importantly the wiki needs to make more sense.

https://github.com/schrapel/wordpress-deploy

Hopefully it helps you or someone else

**Comment by carlalexander** [comment]
I asked about adding composer to `debops.php5` [here](https://github.com/debops/ansible-php5/issues/11). Until they offer a debian package, we'll have to do this ourselves. I'll have something once I add support for bedrock projects.

**Comment by tobeycodes** [comment]
I don't really like this idea anymore. I don't think building on the production box is a good idea. It makes a lot more sense to build elsewhere and package a release. I am happy to close this ticket @carlalexander

**Comment by carlalexander** [comment]
Cool, let's wrap this up then!
