### ISSUE TITLE
Change storage structure of WordPress secrets

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#40]
After speaking with @drybjed yesterday, it seems that the `wordpress` role would also benefit from a change of structure for its secrets. WordPress secrets aren't tied to `{{ ansible_fqdn }}`, but to the WordPress installation. This will be a problem once we look at distributed architecture.

Instead, the storage format should be `secret/wordpress/{{ wordpress_domain }}/credentials/{{ wordpress_user }}/password`. This decouples the secret from `{{ ansible_fqdn }}` and ties it to the WordPress installation instead.

**Comment by drybjed** [comment]
:+1:
