### ISSUE TITLE
skipping: no hosts matched

### ISSUE THREAD

**Issue by outerbridge** [carlalexander/debops-wordpress#42]
Hi Carl

I've set up several of your configurations before, with your generous help, but it's not working today.  I'm getting multiple "skipping: no hosts matched" messages.

I've tried it on 2 different Macs (1 which has never had debops on it) and a fresh DigitalOcean droplet (Ubuntu 14.04) to see whether it's a Mac thing.  Always get the same problem - below is the output from the DO U14.04 version.

Many thanks
Mike

root@debops:~/debops-wordpress# debops -u root
Running Ansible playbook from:
/root/.local/share/debops/debops-playbooks/playbooks/site.yml ...

PLAY [Prepare core environment] ***********************************************
skipping: no hosts matched

PLAY [Common configuration for all hosts] *************************************
skipping: no hosts matched

PLAY [Configure swap files] ***************************************************
skipping: no hosts matched

PLAY [Manage users with git-shell accounts] ***********************************
skipping: no hosts matched

PLAY [Manage users with SFTPonly accounts] ************************************
skipping: no hosts matched

PLAY [Manage OpenLDAP service] ************************************************
skipping: no hosts matched

PLAY [Configure Logical Volume Manager] ***************************************
skipping: no hosts matched

PLAY [Configure iSCSI Initiator] **********************************************
skipping: no hosts matched

PLAY [Configure encrypted filesystems] ****************************************
skipping: no hosts matched

PLAY [Manage NFS service] *****************************************************
skipping: no hosts matched

PLAY [Manage NodeJS environment] **********************************************
skipping: no hosts matched

PLAY [Manage Ruby environment] ************************************************
skipping: no hosts matched

PLAY [Manage Go environment] **************************************************
skipping: no hosts matched

PLAY [Manage Java environment] ************************************************
skipping: no hosts matched

PLAY [Manage PHP5 environment] ************************************************
skipping: no hosts matched

PLAY [Manage fcgiwrap instances] **********************************************
skipping: no hosts matched

PLAY [Configure internal networks] ********************************************
skipping: no hosts matched

PLAY [Configure Router Advertisement Daemon] **********************************
skipping: no hosts matched

PLAY [Manage ISC DHCP server] *************************************************
skipping: no hosts matched

PLAY [Configure dnsmasq] ******************************************************
skipping: no hosts matched

PLAY [Configure tinc VPN] *****************************************************
skipping: no hosts matched

PLAY [Configure stunnel] ******************************************************
skipping: no hosts matched

PLAY [Manage docker-gen service] **********************************************
skipping: no hosts matched

PLAY [Manage nginx service] ***************************************************
skipping: no hosts matched

PLAY [Manage SNMP service] ****************************************************
skipping: no hosts matched

PLAY [Manage Monit service] ***************************************************
skipping: no hosts matched

PLAY [Manage Dovecot service] *************************************************
skipping: no hosts matched

PLAY [Manage TFTP service] ****************************************************
skipping: no hosts matched

PLAY [Manage Samba service] ***************************************************
skipping: no hosts matched

PLAY [Manage iSCSI Target service] ********************************************
skipping: no hosts matched

PLAY [Manage MariaDB server] **************************************************
skipping: no hosts matched

PLAY [Manage MariaDB client] **************************************************
skipping: no hosts matched

PLAY [Manage MySQL server] ****************************************************
skipping: no hosts matched

PLAY [Manage PostgreSQL server] ***********************************************
skipping: no hosts matched

PLAY [Manage PostgreSQL client] ***********************************************
skipping: no hosts matched

PLAY [Manage Elasticsearch server] ********************************************
skipping: no hosts matched

PLAY [Manage memcached server] ************************************************
skipping: no hosts matched

PLAY [Manage Redis server] ****************************************************
skipping: no hosts matched

PLAY [Manage Redis sentinel server] *******************************************
skipping: no hosts matched

PLAY [Manage reprepro repositories] *******************************************
skipping: no hosts matched

PLAY [Manage SMS gateway] *****************************************************
skipping: no hosts matched

PLAY [Manage Salt master service] *********************************************
skipping: no hosts matched

PLAY [Manage fail2ban service] ************************************************
skipping: no hosts matched

PLAY [Manage SKS Keyserver] ***************************************************
skipping: no hosts matched

PLAY [Manage iPXE configuration files] ****************************************
skipping: no hosts matched

PLAY [Manage BoxBackup service] ***********************************************
skipping: no hosts matched

PLAY [Manage rsnapshot service] ***********************************************
skipping: no hosts matched

PLAY [Manage Mailman service] *************************************************
skipping: no hosts matched

PLAY [Manage LibreNMS] ********************************************************
skipping: no hosts matched

PLAY [Manage DokuWiki] ********************************************************
skipping: no hosts matched

PLAY [Manage Etherpad service] ************************************************
skipping: no hosts matched

PLAY [Manage Preseed server] **************************************************
skipping: no hosts matched

PLAY [Manage ownCloud service] ************************************************
skipping: no hosts matched

PLAY [Manage phpIPAM service] *************************************************
skipping: no hosts matched

PLAY [Manage RStudio Server] **************************************************
skipping: no hosts matched

PLAY [Manage GitLab service] **************************************************
skipping: no hosts matched

PLAY [Manage GitLab CI service] ***********************************************
skipping: no hosts matched

PLAY [Manage GitLab CI Runner service] ****************************************
skipping: no hosts matched

PLAY [Install DebOps recursively] *********************************************
skipping: no hosts matched

PLAY [Manage LXC hosts] *******************************************************
skipping: no hosts matched

PLAY [Manage Docker service] **************************************************
skipping: no hosts matched

PLAY [Manage libvirt servers] *************************************************
skipping: no hosts matched

PLAY [Manage libvirt hosts] ***************************************************
skipping: no hosts matched

PLAY [Manage OpenVZ Hardware Nodes] *******************************************
skipping: no hosts matched

PLAY [Configure HWRaid support] ***********************************************
skipping: no hosts matched

PLAY [Configure GRUB] *********************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************

root@debops:~/debops-wordpress#

**Comment by carlalexander** [comment]
Can you try replacing "all_servers" to "debops_all_hosts" in your hosts
file and see if that helps?

**Comment by outerbridge** [comment]
Thanks Carl, that solved it.

Cheers
Mike
