### ISSUE TITLE
RuntimeError: autoconf error

### ISSUE THREAD

**Issue by thewebsitedev** [carlalexander/debops-wordpress#44]
Hello,

I am getting the below error on step 2 of installation (Install Ansible and DebOps).

`File "/private/tmp/pip-build-gCpPLJ/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")`

``` console
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-gCpPLJ/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TA6WBT-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-gCpPLJ/pycrypto
```

What can be the issue?

**Comment by carlalexander** [comment]
Is it possible that you don't have xcode command line installed? This [issue](https://github.com/ansible/ansible/issues/12354) seems to describe the problem that you're having.

**Comment by thewebsitedev** [comment]
Yes, I just ran Xcode and it installed some stuff. Didn't open Xcode from a long time. Seems to be working now.
