### ISSUE TITLE
Failed to upload PKI snapshot to Ansible Controller

### ISSUE THREAD

**Issue by thewebsitedev** [carlalexander/debops-wordpress#45]
I got this error - `FAILED! => {"changed": false, "failed": true, "msg": "file not found: /var/backups/pki-snapshot-debops-wordpress.tar"}` when I ran the common DebOps playbook. Is this fine? We don't have WordPress yet so I guess that is the reason? Just confirming before I move ahead.

My play recap is `ok=37   changed=20   unreachable=0    failed=1`.

**Comment by carlalexander** [comment]
What are your configuration options? Also can you try running it with
-VVVV.

**Comment by thewebsitedev** [comment]
ubuntu 14.04.3 x64
$5/mo plan

I followed the steps as mentioned in the wiki. Just replaced [all_servers] with [debops_all_hosts].

I actually went ahead and ran `debops wordpress -u root`. Now I see one of the known errors 'lookup plugin (tsk_src)' .

Should I recreate a droplet or continue with this only and configure the server again by running `$ debops -u root`?

**Comment by thewebsitedev** [comment]
I just rebuilt my droplet and I am now configuring the server again. This time using -vvvv.

**Comment by mosamlife** [comment]
You have to run this command in your local machine not remote droplate

**Comment by thewebsitedev** [comment]
Yes, I am running locally.

**Comment by thewebsitedev** [comment]
Same error again `FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"src": "/var/backups/pki-snapshot-debops-wordpress.tar"}}, "msg": "file not found: /var/backups/pki-snapshot-debops-wordpress.tar"}`

**Comment by carlalexander** [comment]
You can find the solution to `lookup plugin` issue [here](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found).

**Comment by thewebsitedev** [comment]
Yes, but will it fine moving forward with this error?
`FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"src": "/var/backups/pki-snapshot-debops-wordpress.tar"}}, "msg": "file not found: /var/backups/pki-snapshot-debops-wordpress.tar"}`

**Comment by carlalexander** [comment]
I've never seen this error. I'll have to run tests on my end and get back to you. Would it be possible to get more of the text before the error. What step was Ansible on when it failed?

Are you using the default configuration from the wiki?

**Comment by thewebsitedev** [comment]
This is what I see before the error statement -

`TASK [debops.pki : Upload PKI snapshot to Ansible Controller] ******************
task path: /Users/GT/Library/Application Support/debops/debops-playbooks/roles/debops.pki/tasks/main.yml:55
<thewebsitedev.com> ESTABLISH SSH CONNECTION FOR USER: root
<thewebsitedev.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/GT/.ansible/cp/ansible-ssh-%h-%p-%r -tt thewebsitedev.com 'mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1452790429.24-222315319590470 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1452790429.24-222315319590470 )"'
<thewebsitedev.com> PUT /var/folders/8x/ycbm99z148b5q1qkjzcgbh5r0000gn/T/tmpTIFTYa TO /root/.ansible/tmp/ansible-tmp-1452790429.24-222315319590470/slurp
<thewebsitedev.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/GT/.ansible/cp/ansible-ssh-%h-%p-%r '[thewebsitedev.com]'
<thewebsitedev.com> ESTABLISH SSH CONNECTION FOR USER: root
<thewebsitedev.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/GT/.ansible/cp/ansible-ssh-%h-%p-%r -tt thewebsitedev.com 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1452790429.24-222315319590470/slurp; rm -rf "/root/.ansible/tmp/ansible-tmp-1452790429.24-222315319590470/" > /dev/null 2>&1'`

I did follow the steps as written in the wiki. Just made a small adjustment as mentioned here - https://github.com/carlalexander/debops-wordpress/issues/42#issue-120394928.

**Comment by thewebsitedev** [comment]
I went ahead just to test. The website is working now but I am unable to use ssh. When I use `ssh thewebsitedev.com -l root` I get `ssh_exchange_identification: read: Connection reset by peer`. Debugging shows that it cannot find any of the ssh files.

I will try again from scratch once you provide a fix. :)

**Comment by drybjed** [comment]
I'm not sure why that upload task would fail... @gthapar, do you have a domain correctly set on the remote host? What do you get when you run:

```
ansible all -m setup -a 'filter=ansible_domain'
```

You should get your host domain. But still, it should be fine when `debops.pki` even runs.

Anyway, I'm working on a new `debops.pki` implementation, completely redesigned, with ACME and external CA support, and it won't have all of that "snapshot" nonsense anymore. Perhaps you would like to test it and repost if it works? There's no proper documentation yet, you can find some information about it in its PR: https://github.com/debops/ansible-pki/pull/33

**Comment by carlalexander** [comment]
What do you get when you run @drybjed's command @gthapar?

**Comment by thewebsitedev** [comment]
@carlalexander I tried with a new droplet and domain (ecstem.com). 

```
ecstem.com | UNREACHABLE! => {
    "changed": false, 
    "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", 
    "unreachable": true
}
```

I got the above response when I ran @drybjed command. But I am able to login to my server using `ssh root@ecstem.com`.

**Comment by drybjed** [comment]
@gthapar It might be that the host admin account hasn't been set up yet, ansible is trying to log in to `admin@ecstem.com` account and server is refusing - but that's just my guess. Run the command with `-vvvv` as the comment is suggesting to see the real reason, try to fix it and then see if the domain is correctly set.

**Comment by thewebsitedev** [comment]
@drybjed shall I post the error message here? I am a total noob with all this server stuff.

**Comment by drybjed** [comment]
@gthapar Sure.

**Comment by carlalexander** [comment]
You can post it here. I'm just confused isn't your site at `thewebsitedev.com`?

**Comment by thewebsitedev** [comment]
@carlalexander as I mentioned here https://github.com/carlalexander/debops-wordpress/issues/45#issuecomment-172493274 I am testing on a new droplet and domain. I shifted the previous domain to another droplet which uses one-click WP install.

Here you go -

```
"ERROR! SSH encountered an unknown error. 
The output was:\nOpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket \"/home/gautam/.ansible/cp/ansible-ssh-ecstem.com-22-gautam\" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to ecstem.com [159.203.109.92] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug3: timeout: 9709 ms remain after connect
debug3: Incorrect RSA1 identifier
debug3: Could not load \"/home/gautam/.ssh/id_rsa\" as a RSA1 public key
debug1: identity file /home/gautam/.ssh/id_rsa type 1
debug1: identity file /home/gautam/.ssh/id_rsa-cert type -1
debug1: identity file /home/gautam/.ssh/id_dsa type -1
debug1: identity file /home/gautam/.ssh/id_dsa-cert type -1
debug1: identity file /home/gautam/.ssh/id_ecdsa type -1
debug1: identity file /home/gautam/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/gautam/.ssh/id_ed25519 type -1
debug1: identity file /home/gautam/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug3: load_hostkeys: loading entries for host \"ecstem.com\" from file \"/home/gautam/.ssh/known_hosts\"
debug3: load_hostkeys: found key type ECDSA in file /home/gautam/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-ed25519,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: setup hmac-md5-etm@openssh.com
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug2: mac_setup: setup hmac-md5-etm@openssh.com
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 5b:17:cf:88:19:d6:28:d9:6f:dd:3a
debug3: load_hostkeys: loading entries for host \"ecstem.com\" from file \"/home/gautam/.ssh/known_hosts\"
debug3: load_hostkeys: found key type ECDSA in file /home/gautam/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys
debug3: load_hostkeys: loading entries for host \"159.203.109.92\" from file \"/home/gautam/.ssh/known_hosts\"
debug3: load_hostkeys: found key type ECDSA in file /home/gautam/.ssh/known_hosts:2
debug3: load_hostkeys: loaded 1 keys
debug1: Host 'ecstem.com' is known and matches the ECDSA host key.
debug1: Found key in /home/gautam/.ssh/known_hosts:1
debug1: ssh_ecdsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/gautam/.ssh/id_rsa (0x7fc3e1674aa0),
debug2: key: /home/gautam/.ssh/id_dsa ((nil)),
debug2: key: /home/gautam/.ssh/id_ecdsa ((nil)),
debug2: key: /home/gautam/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey
debug3: authmethod_lookup publickey
debug3: remaining preferred: ,gssapi-keyex,hostbased,publickey
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/gautam/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/gautam/.ssh/id_dsa
debug3: no such identity: /home/gautam/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/gautam/.ssh/id_ecdsa
debug3: no such identity: /home/gautam/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/gautam/.ssh/id_ed25519
debug3: no such identity: /home/gautam/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
Permission denied (publickey,password)."
```

**Comment by drybjed** [comment]
Can you connect over SSH to `gautam` account?

**Comment by thewebsitedev** [comment]
do you mean gautam@ecstem.com? I don't think I have ever created such user account.

**Comment by drybjed** [comment]
My guess is that Ansible is configured to connect to that account by default. You could try and override that like this:

```
ansible all -m setup -u root
```

As for bootstrapping a new host with DebOps, I suggest that you read the [Getting Started with DebOps](http://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html) guide.

**Comment by thewebsitedev** [comment]
@drybjed I ran your command and it appeared as success. But at the bottom it showed `"changed": false`.

I ran `debops -u root` again but unfortunately I got the same error.

```
TASK [debops.pki : Upload PKI snapshot to Ansible Controller] ******************
fatal: [ecstem.com]: FAILED! => {"changed": false, "failed": true, "msg": "file not found: /var/backups/pki-snapshot-debops-ubuntu.tar"}
```

**Comment by drybjed** [comment]
@gthapar I have got reports from other users about the same error. Would you like to test the new version of the `debops.pki` role available in [this PR](https://github.com/debops/ansible-pki/pull/33)? Do you use Ansible 2.0? Alternatively, you could check if Ansible 1.9.4 works OK.

**Comment by thewebsitedev** [comment]
Yes, ansible 2.0.0.2 is what I see installed. Removed 2.0 and installed 1.9.4. Now I don't see the error. :)

@drybjed I am not very comfortable with all this yet so without any kind of documentation it will be a bit hard for me to try something.

**Comment by drybjed** [comment]
@gthapar OK. I'll try to write some documentation for the new role soon. :-)

**Comment by carlalexander** [comment]
Just got this working on #12 while building a new Docker container. I'll let you know if I find a fix. I still don't get it with a configuration of a DO droplet though.

**Comment by carlalexander** [comment]
Here's what I get in Docker using `-vvvv`:

```
TASK [debops.pki : Upload PKI snapshot to Ansible Controller] ******************
task path: /root/.local/share/debops/debops-playbooks/roles/debops.pki/tasks/main.yml:55
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453143775.27-215728918329680 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453143775.27-215728918329680 )" )
localhost PUT /tmp/tmpeFBLbK TO /root/.ansible/tmp/ansible-tmp-1453143775.27-215728918329680/slurp
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453143775.27-215728918329680/slurp; rm -rf "/root/.ansible/tmp/ansible-tmp-1453143775.27-215728918329680/" > /dev/null 2>&1
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"src": "/var/backups/pki-snapshot-b4a0b458150e.tar"}}, "msg": "file not found: /var/backups/pki-snapshot-b4a0b458150e.tar"}
```

**Comment by carlalexander** [comment]
I'm thinking it might be a problem with the newest version of Ansible. This is the only difference between my setups. I didn't run into the issue if I downgraded Ansible versions in Docker. You can do it this way:

``` console
sudo pip uninstall ansible
sudo pip install -Iv https://pypi.python.org/packages/source/a/ansible/ansible-1.9.4.tar.gz
```

**Comment by thewebsitedev** [comment]
Yes, downgrading worked as mentioned here https://github.com/carlalexander/debops-wordpress/issues/45#issuecomment-172528926.

`sudo pip install ansible==1.9.4` worked just fine. ;)

**Comment by drybjed** [comment]
I just tried with Ansible 1.9.4 and clean PKI-related stuff, everything works fine... So, can somebody show me output of the `debops.pki` role so maybe I'll notice what might be the issue?

**Comment by carlalexander** [comment]
I put the output above

**Comment by drybjed** [comment]
@carlalexander Well, that's the error message, but it doesn't tell me what happened to see what could be the reason. Seeing all of the `debops.pki` tasks could tell me that. :-)

**Comment by thiagotalma** [comment]
@drybjed any news on this?

I have the same problem on the local machine

**Comment by drybjed** [comment]
@thiagotalma I tried to reproduce the issue on Ansible 2.0 with the "old" `debops.pki` but for me it works. If you have this problem, can you show me the output of all of the `debops.pki` tasks?

Otherwise I would either wait a bit, or try the new [debops.pki rewrite](https://github.com/debops/ansible-pki/pull/33) I'm currently working on. At the moment it should all work, ACME, rewalls, et al. I'm working on the documentation, should probably finish on the weekend.

**Comment by thiagotalma** [comment]
Ok @drybjed 

While you are working I'll let the "pki: False"
Thank you so much.
