### ISSUE TITLE
Setting up SSL

### ISSUE THREAD

**Issue by thewebsitedev** [carlalexander/debops-wordpress#46]
I need to install SSL on my server. And I am a little confused at the moment. So far what I have done is:
1. Generated `thewebsitedev.csr` and `thewebsitedev.key` files.
2. Bought and activated PositiveSSL certificate through Namecheap. I received the certificate (.crt) file.

As per the documentation I need to enter absolute path to the certificate.crt and certificate.key files. As far as I understand 'certificate.crt' is the file issued by the SSL certificate issuer (the .crt file that I received). And the `certificate.key` file is the file I created earlier (thewebsitedev.key). Is this correct?

So now,
1. I need to create `vars.yml` file under `debops-wordpress/inventory/host_vars/www.thewebsitedev.com/` with the below content (after replacing the file paths):

```
wordpress_ssl: True
wordpress_ssl_crt: '/absolute/path/to/certificate.crt'
wordpress_ssl_key: '/absolute/path/to/certificate.key'
```
1. Run `debops -u root` command.

Is this correct? Am I on the right path?

**Comment by carlalexander** [comment]
You should only need to run `debops wordpress -u root`. I'm going to amend the documentation.

**Comment by thewebsitedev** [comment]
Okay, error :(

```
NOTIFIED: [debops.nginx | Test nginx and reload] ****************************** 
failed: [www.thewebsitedev.com] => {"changed": true, "cmd": ["nginx", "-t"], "delta": "0:00:00.024781", "end": "2016-01-26 14:51:01.552459", "rc": 1, "start": "2016-01-26 14:51:01.527678", "warnings": []}
stderr: nginx: [emerg] ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
nginx: [emerg] ipv6only is not supported on addr "0.0.0.0:443", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:21
nginx: [emerg] ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
nginx: [emerg] BIO_new_file("/etc/pki/host/certs/www.thewebsitedev.com.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/host/certs/www.thewebsitedev.com.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

FATAL: all hosts have already failed -- aborting

TASK: [debops.pki | Set default trust policy for new certificates] ************ 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

what can be the cause? file not found?

**Comment by carlalexander** [comment]
Could you post your config with the paths to your certificates.

**Comment by thewebsitedev** [comment]
What do you mean by config?

This is what I have in `../debops-wordpress/inventory/host_vars/www.thewebsitedev.com/vars.yml`.

```
wordpress_ssl: True
wordpress_ssl_crt: '/home/gautam/Desktop/www_thewebsitedev_com.crt'
wordpress_ssl_key: '/home/gautam/Desktop/thewebsitedev.key'
```

**Comment by carlalexander** [comment]
Yep! That's what I meant by config. This looks fine to me. DebOps is supposed to upload those files if those path are correct.

What do you get on your server if you run `sudo ls -l /etc/pki/host/private/` and `sudo ls -l /etc/pki/host/certs/`. Is it empty?

**Comment by thewebsitedev** [comment]
Yes I checked these earlier and there are no such directories on the server.

**Comment by carlalexander** [comment]
Hmmm ok. I'm not too sure what else could cause the problem. Both paths seem correct to me (althought the file names are different). The only thing that DebOps does is copy those files to the server and then nginx uses them. The fact that those folders are empty means that the files aren't being copied.

**Comment by drybjed** [comment]
OK, I guess it's time for me to crash this party... @gthapar, would you be up to trying the new version of `debops.pki` role, which is not merged yet, but there's a [PR of it I'm working on](https://github.com/debops/ansible-pki/pull/33)? It slightly changes how the stuff in `/etc/pki/` works, but should be easier to manage custom external certificates like yours. Here's [an explanation of general PKI realm architecture](https://gist.github.com/drybjed/3be35732ce809d49b030) if you want to know more before trying it out, I'm currently writing the rest of the documentation before merging everything. Let me know if you got it working or there are any issues.

**Comment by thewebsitedev** [comment]
@carlalexander I ran `debops wordpress -u root` again without changing a single thing. And it worked! I don't know what happened earlier.

@drybjed Okay, if I can help you in any way. I can try this on a new server. Just let me know where to begin.

**Comment by thewebsitedev** [comment]
@carlalexander What do I need to do after this? My website doesn't seem to work with https.
www.thewebsitedev.com

**Comment by carlalexander** [comment]
Was it HTTP before? You might need to do some steps to migrate. This is a good guide to follow: https://css-tricks.com/moving-to-https-on-wordpress/

**Comment by thewebsitedev** [comment]
Just checked, I still can't find those directories you mentioned earlier. Is that fine?

**Comment by carlalexander** [comment]
Can you copy the content from `/etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf` here?

**Comment by thewebsitedev** [comment]
Okay, here it is..

```
# This file is managed remotely, all changes will be lost

# nginx server configuration for:
#    - https://www.thewebsitedev.com/
# generated by Ansible role: wordpress

server {
        listen 80 default_server ipv6only=off;

        server_name www.thewebsitedev.com;


        include snippets/acme-challenge.conf;

        location / {
                return 301 https://$host$request_uri;
        }
}

server {
        listen 443 ssl spdy default_server ipv6only=off;

        ssl_certificate           /etc/pki/host/certs/www.thewebsitedev.com.crt;
        ssl_certificate_key       /etc/pki/host/private/www.thewebsitedev.com.key;
        ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               "EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4"; # SSL cipher list: pfs
        ssl_dhparam               /etc/pki/dhparam/set0;
        ssl_ecdh_curve            secp384r1;
        ssl_stapling              on;
        ssl_stapling_verify       on;
        resolver                  8.8.8.8 8.8.4.4 valid=300s;
        resolver_timeout          5s;
        add_header                Strict-Transport-Security "max-age=15768000; includeSubDomains";

        server_name www.thewebsitedev.com;


        include snippets/acme-challenge.conf;

        keepalive_timeout 60;

        access_log /var/log/nginx/varnish.www.thewebsitedev.com_access.log;
        error_log /var/log/nginx/varnish.www.thewebsitedev.com_error.log;

        client_max_body_size  32M;

    location = /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1/32;
        allow ::1/128;
        allow 45.55.40.197;
        allow 10.17.0.11;
        deny all;
    }

        include /etc/nginx/site-default.d/*.conf;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Forwarded-Port 443;
                proxy_set_header Host $host;
                proxy_pass http://varnish;
        }


}
```

**Comment by carlalexander** [comment]
Yep, the ceritifcates are there in config. What happens if you run `sudo service nginx restart` on the server?

**Comment by thewebsitedev** [comment]
restart fails

**Comment by carlalexander** [comment]
Can you run `debops wordpress -vvvv -u root` and post what happens for this step: "Download custom private files"?

**Comment by thewebsitedev** [comment]
Okay, here it is:

```
TASK: [debops.pki | Download custom private files] **************************** 
skipping: [www.thewebsitedev.com] => (item={'dest': u'certs/www.thewebsitedev.com.crt', 'src': u'/home/gautam/Desktop/www_thewebsitedev_com.crt'})
skipping: [www.thewebsitedev.com] => (item={'dest': u'private/www.thewebsitedev.com.key', 'src': u'/home/gautam/Desktop/thewebsitedev.key'})
```

**Comment by carlalexander** [comment]
Is this with `-vvvv`? I tought Ansible would give more details. :cry:

**Comment by thewebsitedev** [comment]
yes using `-vvvv`. I saved the entire output to a different file. So if you need to check I can send it to you.

**Comment by thewebsitedev** [comment]
So I guess I need to place these files manually now.. ? And maybe configure SSL manually as well.. ?

**Comment by carlalexander** [comment]
I'd use the paths configured by DebOps, so `/etc/pki/host/certs/www.thewebsitedev.com.crt` and `/etc/pki/host/private/www.thewebsitedev.com.key`. But I don't understand why they're not copying. Both files are on your desktop?

**Comment by thewebsitedev** [comment]
Yes they are indeed! I even changed the names to match it with `www.thewebsitedev.com`. But don't know it always skips that download task.

**Comment by thewebsitedev** [comment]
I uploaded these files manually to the locations you mentioned. I then ran `debops wordpress -u root`. But I still cannot access SSL based links like https://www.thewebsitedev.com.

I get 

```
This webpage is not available
ERR_CONNECTION_REFUSED
```

**Comment by drybjed** [comment]
@gthapar Do you have IPv6 configured? What shows up when you run `netstat -nlp | grep nginx`?

**Comment by thewebsitedev** [comment]
I never enabled IPv6 while setting up the server. Below is what I got when I ran `netstat -nlp | grep nginx`.

```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1491/nginx      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1491/nginx  
```

**Comment by drybjed** [comment]
It looks like the `nginx` server wasn't properly restarted yet... I assume that the configuration you pasted above is still in place and certificates are where `nginx` expects them in the config... What happens when you restart `nginx` on the server?

**Comment by thewebsitedev** [comment]
Restarted nginx.. it didn't fail like previously.. 

```
* Restarting nginx nginx                                                [ OK ]
```

ran `netstat -nlp | grep nginx` again and I got

```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      24296/nginx     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      24296/nginx
```

**Comment by carlalexander** [comment]
This is just so weird! What does `tail /var/log/nginx/error.log` say?

**Comment by thewebsitedev** [comment]
```
2016/01/27 20:16:23 [emerg] 21513#0: ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
2016/01/27 20:16:23 [emerg] 21513#0: ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
2016/01/27 20:16:30 [emerg] 21553#0: ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
2016/01/27 20:16:30 [emerg] 21553#0: ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
2016/01/27 20:16:30 [emerg] 1491#0: ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
2016/01/27 20:16:30 [emerg] 1491#0: ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
2016/01/27 21:39:01 [emerg] 24291#0: ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
2016/01/27 21:39:01 [emerg] 24291#0: ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
2016/01/27 21:39:02 [emerg] 24295#0: ipv6only is not supported on addr "0.0.0.0:80", ignored in /etc/nginx/sites-enabled/varnish.www.thewebsitedev.com.conf:8
2016/01/27 21:39:02 [emerg] 24295#0: ipv6only is not supported on addr "0.0.0.0:8080", ignored in /etc/nginx/sites-enabled/www.thewebsitedev.com.conf:8
```

**Comment by drybjed** [comment]
Hmm, interesting. @gthapar, what OS do you use, and what does `dpkg -l | grep nginx` show? As well as `apt-cache policy nginx-full`?

**Comment by thewebsitedev** [comment]
On server, I selected `Ubuntu 14.04.3 x64`

dpkg -l | grep nginx

```
ii  nginx-common                         1.4.6-1ubuntu3.3                     all          small, powerful, scalable web/proxy server - common files
ii  nginx-full                           1.4.6-1ubuntu3.3                     amd64        nginx web/proxy server (standard version)
```

apt-cache policy nginx-full

```
nginx-full:
  Installed: 1.4.6-1ubuntu3.3
  Candidate: 1.4.6-1ubuntu3.3
  Version table:
 *** 1.4.6-1ubuntu3.3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.4.6-1ubuntu3.1 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/universe amd64 Packages
     1.4.6-1ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
```

**Comment by drybjed** [comment]
This error is raised when IPv6 is not configured on the host but `ipv6only` is enabled: http://hg.nginx.org/nginx/file/4a71ef1aa36d/src/http/ngx_http_core_module.c#l4129

Looking for a fix...

**Comment by drybjed** [comment]
@gthapar Try setting in Ansible inventory:

```
nginx_manage_ipv6only: False
```

This should prevent `debops.nginx` from adding `ipv6only=off` automatically in the configuration.

**Comment by thewebsitedev** [comment]
Okay, under `group_vars` or `host_vars`?

Then I need to run `debops wordpress -u root` again right?

**Comment by thewebsitedev** [comment]
Ah okay inside hosts file under inventory. Now I need to run `debops wordpress -u root` again?

**Comment by thewebsitedev** [comment]
Sorry I am confused right now. This is what you mean right?

```
# This is an Ansible inventory file in INI format. You can define a list of
# hosts and groups to be managed by this particular inventory.

# Hosts listed under [all_servers] will have common DebOps plays
# ran against them. It will include services such as iptables, DNS, Postfix,
# sshd configuration and more.
#
# View the list here:
# https://github.com/debops/debops-playbooks/blob/master/playbooks/common.yml

[debops_all_hosts]
www.thewebsitedev.com

[wordpress]
www.thewebsitedev.com

nginx_manage_ipv6only: False
```

**Comment by drybjed** [comment]
@gthapar Put it in `ansible/inventory/host_vars/<hostname>/nginx.yml`. It's a YAML variable definition.

**Comment by thewebsitedev** [comment]
And this is on the sever side or my local machine? Sorry, as I said earlier I am a noob with all this server related stuff.

**Comment by drybjed** [comment]
@gthapar On your local machine, in the same place that the Ansible inventory directory is located. Basically, when you see the `hosts` file, create `host_vars/www.thewebsitedev.com/nginx.yml` file and put the variable there.

**Comment by thewebsitedev** [comment]
Okay, this is the path to the file on my local machine. Added the variable as well.
`/usr/local/lib/python2.7/dist-packages/ansible/inventory/host_vars/www.thewebsitedev.com/nginx.yml`

Now what I need to do?

**Comment by drybjed** [comment]
@gthapar I'm confused a bit... Is that path to where you keep your Ansible inventory on the host that Ansible runs from? Anyway, in the `nginx.yml` file, add this content:

```
---
nginx_manage_ipv6only: False
```

This will tell Ansible that for this particular host, it shouldn't add `ipv6only=off` option in the `nginx` configuration. After that, re-run Ansible and your webserver should restart and listen on `443` port for HTTPS connections.

**Comment by thewebsitedev** [comment]
I am confused myself.. :)

This is the only Ansible directory on my local machine. I installed Ansible as per the instructions here - https://github.com/carlalexander/debops-wordpress/wiki/Installation#install-ansible-and-debops.

Can you please tell which command I need to run for ansible?

**Comment by drybjed** [comment]
@gthapar OK, how about this. Put the contents I specified earlier in `~/debops-wordpress/ansible/inventory/host_vars/www.thewebsitedev.com/nginx.yml`. And then, being in that project directory, run `debops -u root`. Does that work?

**Comment by thewebsitedev** [comment]
This is what I get -

```
gautam@ubuntu:~/debops-wordpress$ debops -u root
Running Ansible playbook from:
/home/gautam/.local/share/debops/debops-playbooks/playbooks/site.yml ...

PLAY [Prepare core environment] *********************************************** 

GATHERING FACTS *************************************************************** 
fatal: [www.thewebsitedev.com] => SSH Error: ssh: connect to host www.thewebsitedev.com port 22: Connection refused
    while connecting to 192.168.1.1:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [debops.core | Create root directories] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
debops.core | Create root directories ----------------------------------- 0.01s
           to retry, use: --limit @/home/gautam/site.retry

www.thewebsitedev.com      : ok=0    changed=0    unreachable=1    failed=0   
```

**Comment by drybjed** [comment]
@gthapar What command do you use to configure DebOps for WordPress?

**Comment by thewebsitedev** [comment]
Okay ran again.. `debops -vvvv -u root` and its running right now..

**Comment by thewebsitedev** [comment]
I used `debops -u root` earlier

**Comment by thewebsitedev** [comment]
Okay, I get this -

```
PLAY RECAP ******************************************************************** 
debops.ferm | Configure ip(6)tables rules ----------------------------- 115.93s
debops.core | Create root directories ---------------------------------- 81.10s
debops.ferm | Remove ip(6)tables rules if requested -------------------- 40.52s
debops.postfix | Generate Postfix hash tables sources ------------------ 33.25s
debops.core | Save local facts ----------------------------------------- 30.97s
debops.ferm | Make sure required directories exist --------------------- 30.76s
debops.auth | Ensure common system groups exist ------------------------ 28.76s
debops.postfix | Generate Postfix tables sources ----------------------- 27.03s
debops.core | Install local fact scripts ------------------------------- 25.36s
debops.apt | Update package lists -------------------------------------- 20.42s
www.thewebsitedev.com      : ok=220  changed=7    unreachable=0    failed=0 
```

**Comment by drybjed** [comment]
@gthapar OK, so, how does the website `nginx` configuration look like now?

**Comment by thewebsitedev** [comment]
ran `netstat -nlp | grep nginx`

```
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      32703/nginx     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      32703/nginx 
```

**Comment by drybjed** [comment]
@gthapar Yes, I know, I can see that the webserver does not listen on the `443` port. But, show me contents of `/etc/nginx/sites-enabled/*.conf` files, each with the filename please.

**Comment by thewebsitedev** [comment]
varnish.www.thewebsitedev.com.conf

```
# This file is managed remotely, all changes will be lost

# nginx server configuration for:
#    - http://www.thewebsitedev.com/
# generated by Ansible role: wordpress

server {
        listen 80 default_server ipv6only=off;

        server_name www.thewebsitedev.com;


        include snippets/acme-challenge.conf;

        keepalive_timeout 60;

        access_log /var/log/nginx/varnish.www.thewebsitedev.com_access.log;
        error_log /var/log/nginx/varnish.www.thewebsitedev.com_error.log;

        client_max_body_size  32M;

    location = /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1/32;
        allow ::1/128;
        allow 45.55.40.197;
        allow 10.17.0.11;
        deny all;
    }

        include /etc/nginx/site-default.d/*.conf;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto http;
                proxy_set_header X-Forwarded-Port 80;
                proxy_set_header Host $host;
                proxy_pass http://varnish;
        }


}
```

www.thewebsitedev.com.conf

```
# This file is managed remotely, all changes will be lost

# nginx server configuration for:
#    - http://www.thewebsitedev.com/
# generated by Ansible role: wordpress

server {
        listen 8080 default_server ipv6only=off;

        server_name www.thewebsitedev.com;

        root /var/www/www.thewebsitedev.com;

        include snippets/acme-challenge.conf;

        keepalive_timeout 60;

        access_log /var/log/nginx/www.thewebsitedev.com_access.log;
        error_log /var/log/nginx/www.thewebsitedev.com_error.log;

        index index.html index.htm index.php;

        client_max_body_size  32M;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types application/atom+xml
          application/javascript
          application/json
          application/ld+json
          application/manifest+json
          application/rdf+xml
          application/rss+xml
          application/schema+json
          application/vnd.geo+json
          application/vnd.ms-fontobject
          application/x-font-ttf
          application/x-javascript
          application/x-web-app-manifest+json
          application/xhtml+xml
          application/xml
          font/eot
          font/opentype
          image/bmp
          image/svg+xml
          image/vnd.microsoft.icon
          image/x-icon
          text/cache-manifest
          text/css
          text/javascript
          text/plain
          text/vcard
          text/vnd.rim.location.xloc
          text/vtt
          text/x-component
          text/x-cross-domain-policy
          text/xml;

        rewrite /wp-admin$ $scheme://$host$uri/ permanent;

    # Disallow access to hidden files and directories
    location ~ /\. {
        return 404;
    }

    location = /favicon.ico {
        try_files /favicon.ico =204;
        access_log off;
        log_not_found off;
    }

    location = /nginx_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1/32;
        allow ::1/128;
        allow 45.55.40.197;
        allow 10.17.0.11;
        deny all;
    }

        include /etc/nginx/site-default.d/*.conf;

        location ~ /(\.|wp-config.php|readme.html|license.txt|wp-cli.local.yml|wp-cli.yml) {
                return 404;
        }

        location ~* ^.+\.(css|js|ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
                access_log off;
                expires max;
                add_header Cache-Control "public";
        }

        location = /robots.txt {
                access_log off;
                log_not_found off;
                try_files /robots.txt /index.php;
        }

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        location ~ ^(?!.+\.php/)(?<script_name>.+\.php)$ {
                limit_except GET HEAD POST { deny all; }

                try_files $script_name =404;

                include fastcgi_params;

                set $php_https off;

                if ($http_x_forwarded_proto = "https") {
                  set $php_https on;
                }

                fastcgi_param HTTPS $php_https;

                fastcgi_index index.php;
                fastcgi_pass php;
        }

        location ~ ^(?<script_name>.+\.php)(?<path_info>/.*)$ {
                limit_except GET HEAD POST { deny all; }

                try_files $script_name =404;

                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$script_name;
                fastcgi_param PATH_INFO $path_info;
                #fastcgi_param PATH_TRANSLATED $document_root$path_info;

                set $php_https off;

                if ($http_x_forwarded_proto = "https") {
                  set $php_https on;
                }

                fastcgi_param HTTPS $php_https;

                fastcgi_index index.php;
                fastcgi_pass php;
        }


}
```

**Comment by thewebsitedev** [comment]
Don't I need to run `debops wordpress -u root` as well?

**Comment by drybjed** [comment]
OK, so `ipv6only=off` is still there. @gthapar, did you create the `nginx.yml` file and put the `nginx_manage_ipv6only: False` in it? Where did you create it? Show me the output of:

```
ansible all -m setup -a 'filter=ansible_local'
```

The `debops wordpress -u root` command... I guess you could, but it shouldn't be needed at this point. The point is to stop `nginx` from trying to manage IPv6 configuration, which the variable i gave earlier should have done.

**Comment by thewebsitedev** [comment]
Path to the file:
`/home/gautam/debops-wordpress/ansible/host_vars/www.thewebsitedev.com/nginx.yml`

File content -

```
---
nginx_manage_ipv6only: False
```

Running `ansible all -m setup -a 'filter=ansible_local'` under project directory gives me -

```
www.thewebsitedev.com | FAILED => SSH Error: Permission denied (publickey).
    while connecting to 45.55.40.197:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
```

**Comment by drybjed** [comment]
@gthapar Move the file to

```
/home/gautam/debops-wordpress/ansible/inventory/host_vars/www.tewebsitedev.com/nginx.yml
```

and re-run the `debops -u root` command.

**Comment by thewebsitedev** [comment]
Oops sorry! missed the inventory folder. :facepalm:

ran `debops -u root` again and it skipped everything.

**Comment by thewebsitedev** [comment]
skipping: no hosts matched

**Comment by drybjed** [comment]
@gthapar I dunno, try with `debops -vvvv -u root`. Perhaps that will work?

**Comment by thewebsitedev** [comment]
same result.. :(

**Comment by drybjed** [comment]
@gthapar What did you do [that time like an hour ago](https://github.com/carlalexander/debops-wordpress/issues/46#issuecomment-176080524) when it worked?

**Comment by thewebsitedev** [comment]
I just ran this `debops -vvvv -u root` command.

**Comment by thewebsitedev** [comment]
I get this -

```
Running Ansible playbook from:
/home/gautam/.local/share/debops/debops-playbooks/playbooks/site.yml ...
 [WARNING]: provided hosts list is empty, only localhost is available
```

**Comment by drybjed** [comment]
When you run these commands, in which directory do you do this? Run `pwd` and show the result.

**Comment by thewebsitedev** [comment]
Project directory -
`/home/gautam/debops-wordpress`

**Comment by drybjed** [comment]
Let's call this directory `$PWD`. What's in `$PWD/ansible/inventory/hosts`?

**Comment by thewebsitedev** [comment]
there is no hosts directory..

under inventory I have 'host_vars' directory.

**Comment by drybjed** [comment]
@gthapar Perhaps this is the wrong approach after all, I think we all got confused somewhere.

How about this: read the [Getting Started with DebOps](http://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html) guide. It should explain where everything should go, it will help you set up a new host with DebOps, or at least give you better overview how the project. After that you should know what a "DebOps project directory" is, and where various files should end up. That should help you set up DebOps for WordPress correctly.

**Comment by thewebsitedev** [comment]
Okay.. I just followed the steps mentioned here - https://github.com/carlalexander/debops-wordpress/wiki/Installation.

Thanks anyways!

**Comment by carlalexander** [comment]
I updated the documentation to be clearer about the command to run for existing servers. I'm going to close this since that was the initial point of this issue.

If you find more details about the other issue you had @gthapar , feel free to open a new one!
