### ISSUE TITLE
Running multiple sites on the same server?

### ISSUE THREAD

**Issue by khromov** [carlalexander/debops-wordpress#50]
Is there any support for running multiple sites on the same Debops server? Would be a great feature for smaller sites that still want to leverage all of the niceties Debops for WP offers.

**Comment by carlalexander** [comment]
We discussed it before in #3 and #32. I don't support it for now because it's hard to do properly. Each site needs to be well isolated so that they don't get cross-contaminated. 

I'll leave this open. I'm a bit more open to doing this than before. I've done some custom setups that way and Varnish works fine. It'll just require a lot of rework of the role so that it creates multiple sites, uploads all the SSL certificates, etc.

**Comment by carlalexander** [comment]
So I had a bit of an epiphany about this in the morning and ran some tests just now. The role can create multiple sites on the same server. You need to point a different domain to the same server. That said, you'll need to do some extra configuration by hand.

Here's what I did:
1. Added new blog domain to `hosts` file under `wordpress` group.
2. Created a `host_vars` file for the new domain.
3. Make sure you have a different `wordpress_database_name` for this new site.
4. Copy necessary `mariadb` credentials like `root` password and `wordpress` (if using same user name).
5. Ran `debops wordpress -u root --limit="wordpress.example2.com"`

I haven't tested everything, but my educated guess is that everything will work fine.

Now, I need to do my due diligence and point out that this _**isn't**_ a secure setup. You're pretty much creating a [soup kitchen server](https://blog.sucuri.net/2013/01/wordpress-security-5-steps-to-reduce-your-risk.html). So I'd use this workaround at your own risk. I still think 5$/month for a single site is acceptable.

_But_ knowing that something like this is possible does make it easier to shore up the missing security elements without rewriting the whole role. I'd say the only thing missing is moving away from `www-data` as the PHP user and owner of the WordPress folder. It's on my roadmap to change this. I'll run some more tests once it's live.

**Comment by andrewgoodnz** [comment]
This would be great once secured :) We run a number of WP sites for clients and there are huge benefits and economies of scale to securely run many sites on a single server.

**Comment by setroot** [comment]
Why not use WP Multisite?

**Comment by andrewgoodnz** [comment]
Multisite is not always a good option. For our use case we would be hosting multiple Single sites.

**Comment by setroot** [comment]
This is all possible with Multisite.

**Comment by andrewgoodnz** [comment]
@whosjose Thanks for your feedback and input to this issue.

**Comment by carlalexander** [comment]
My preference isn't to use such a setup, but I plan on supporting it in some capacity. I still need to work through the remaining issue around creating a unique user for the PHP process. Once we do that, we'll just need some documentation. The workaround above should work in the meantime.

**Comment by carlalexander** [comment]
Alright, so you can now change the wordpress system user which was the last security issue for this ticket. The only thing left is to write some documentation.

**Comment by AdamQuadmon** [comment]
Nice! I was just looking for this.

**Comment by carlalexander** [comment]
Finally got to writing the documentation for this. You can find it [here](https://github.com/carlalexander/debops-wordpress/wiki/How-to-configure-multiple-WordPress-sites-on-a-single-server).

**Comment by khromov** [comment]
@carlalexander Perfect, thanks so much!
