### ISSUE TITLE
debops.fail2ban fails

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#58]
When running debops wordpress -u root I get this error message. 

TASK [debops.fail2ban : Configure custom fail2ban actions] *********************
fatal: [test.tobyschrapel.com]: FAILED! => {"failed": true, "msg": "lookup plugin (template_src) not found"}

If I set wordpress_fail2ban_enabled: False it obviously works fine

**Comment by tobeycodes** [comment]
Spoke too soon. Now I get it here

TASK [debops.nginx : DebOps pre_tasks hook] ************************************
fatal: [test.tobyschrapel.com]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/...../playbooks/wordpress.retry

**Comment by tobeycodes** [comment]
I most recently updated debops and all the dependencies

**Comment by carlalexander** [comment]
Can you try [this](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found) and let me know if you still have the issue? I had someone else upgrade to Ansible 2.1.0 and have this issue come back up.

**Comment by tobeycodes** [comment]
Damn, I thought this fix was global and I hadn't done it in a while so forgot. I'm sure this is the problem but will double check later

Enviado desde mi iPhone

**Comment by tobeycodes** [comment]
That fixed it.
