### ISSUE TITLE
WordPress Setup

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#59]
Would you accept a pull request for a wordpress_setup flag that defaults to true.

When it is false it will not install wp-cli, download core, setup the config or install wordpress?

I always go into the var/www/ and rm -rf in the directory before I deploy my git repository anyway.

Or is there a better way to go about it?

**Comment by carlalexander** [comment]
Yep! Makes sense and I'd probably need it for #2 as well!

**Comment by lchski** [comment]
Doing some work over the weekend in a (currently private) fork, I separated the WP tasks you described (wp-cli, downloading core, etc) into its in Ansible role and playbook. I think that goes a bit against your two-command vision, @carlalexander, but it worked nicely for me.

**Comment by carlalexander** [comment]
I'm not against more roles or playbooks or commands. I just think, in this case, it's more of a setting for the WordPress role itself.

The same way you can use `wordpress_dependencies: false` to disable all role dependencies. You should have a way to disable the automatic installation of WordPress for setups that don't need it.

**Comment by tobeycodes** [comment]
I just submitted a pull request https://github.com/carlalexander/debops-wordpress/pull/61

I left the task in there to create the directory and set the permissions. 

Also the task for setting a cron job. I assume that people are still using WordPress

**Comment by tobeycodes** [comment]
Actually, now I just realised that if we are going to deploy a Bedrock build the cron URL will be wrong

**Comment by carlalexander** [comment]
Yeah, there's already a flag for the cron too I believe.

**Comment by carlalexander** [comment]
Just added a variable for the path to `wp-cron.php`.
