### ISSUE TITLE
Default config breaks web fonts in Safari

### ISSUE THREAD

**Issue by lchski** [carlalexander/debops-wordpress#60]
Steps to reproduce:
- Set up the project as per normal;
- Visit the WP site running Twenty Sixteen in Safari.

As you’ll see, most of the text doesn’t render at all. This affects the admin area, too.

If you open the web inspector, you’ll see that the there are still requests running. Clicking the “stop” button ends these requests, and causes the fonts to load.

Not sure what this is about, but I think it has something to do with Varnish; when I ran the project without the Varnish components, it worked fine.

**Comment by carlalexander** [comment]
I'll run some tests on this and get back to you. I've used Safari before and didn't notice any of this.

**Comment by lchski** [comment]
Cool. If you can’t replicate it and want me to try it again on my end sometime, let me know.

**Comment by lchski** [comment]
Tried to replicate this last night, couldn’t. Closing!
