### ISSUE TITLE
TASK [debops.mariadb : Create databases] Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by tmuka** [carlalexander/debops-wordpress#65]
I'm getting stuck here with an ssh connection error in the middle of the db create process. I'm not sure how to troubleshoot this further.  ssh connections to the host work fine both manually, and for the other previous debops steps before this part of the process.

```
tmuka@workstation:~/debops-wordpress$ debops wordpress -u root  -vvvv
...[removed a bunch of log output that worked fine]...

TASK [debops.mariadb : Create databases] ***************************************
task path: /home/tmuka/.local/share/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu> ESTABLISH SSH CONNECTION FOR USER: None
<ubuntu> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/tmuka/.ansible/cp/ansible-ssh-%h-%p-%r ubuntu '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464369242.9-26154098700774 `" && echo ansible-tmp-1464369242.9-26154098700774="` echo $HOME/.ansible/tmp/ansible-tmp-1464369242.9-26154098700774 `" ) && sleep 0'"'"''
failed: [64.137.246.121] (item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [64.137.246.121]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}
        to retry, use: --limit @/home/tmuka/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
64.137.246.121             : ok=60   changed=0    unreachable=1    failed=0
```

Is it possible maybe my local ssh-key is an old format or something that would work for ssh but not the maria-db connections?

I am able to ssh into the server using key auth, and from there i am able to connect to mysql.  I can even connect to server mysql over an ssh tunnel from my workstation.

I'm not sure the next step for troubleshooting this, i did try running the line directly

```
ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/tmuka/.ansible/cp/ansible-ssh-%h-%p-%r ubuntu '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464369242.9-26154098700774 `" && echo ansible-tmp-1464369242.9-26154098700774="` echo $HOME/.ansible/tmp/ansible-tmp-1464369242.9-26154098700774 `" ) && sleep 0'"'"''
```

it outputs 

```
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/tmuka/.ansible/cp/ansible-ssh-ubuntu-22-tmuka" does not exist
ssh: Could not resolve hostname ubuntu: Name or service not known
```

i see my remote server is `Ubuntu 14.04.1 LTS` while my workstation is `Ubuntu 14.04.4 LTS`, so i'll try to do an `apt-get update && apt-get upgrade` then try again to see if that matters.  This is a cloudatcost.com 512MB server i'm provisioning...

Thanks for any insight you might have! I'm happy to provide more info if it would be helpful!
Tony

**Comment by carlalexander** [comment]
Hey Tony!

What's the name that you gave your virtual machine on cloudatcost?

**Comment by drybjed** [comment]
Hello.

The `debops.mariadb` role might be somewhat complicated to use in certain setups. Namely, by default it's designed to work in a case where you run Ansible on your workstation and manage the database on a remote host relative to your workstation.

It seems to me that your host `ubuntu` that you are trying to configure does not have a Fully Qualified Domain Name. The `debops.mariadb` server uses that by default to connect to the remote host, and if this value is incorret, that might result in an error similar to yours.

To check if your host is configured correctly, run this command:

```
ansible all -m setup -a 'filter=ansible_fqdn'
```

You should see an entry with value that has at least 1 dot. If it does not, you need to make sure that your host has correctly configured domain. You can use `debops.bootstrap` role to configure it.

You might also want to check out [Getting Started guide](http://docs.debops.org/en/latest/debops-playbooks/docs/guides/getting-started.html) to see how DebOps inventory and environment works together.

**Comment by tmuka** [comment]
thanks for the quick replies!  
@carlalexander i was trying to use the ip address since i spun up a new vm today and it got a new ip for my dev.tonymuka.com fqdn i was eventually testing with.  I did put temporarily put the fqdn in my local /etc/hosts file as a shortcut...

@drybjed that sounds like it, i'll give it a another try now that dns is resolving correctly.  I appreciate the doc link too- it looks like a weath of information there for me to digest.

**Comment by tmuka** [comment]
it looks like i have some more research to do...   my fqdn resolves fine and works, but the ansible test still says UNREACHABLE...  in the following snippet after the test i verify that i can scp to the fqdn with the root user using the ssh-key auth...

```
tmuka@tMythtv:~/debops-wordpress$ ansible all -m setup -a 'filter=ansible_fqdn'                                                                                                                    │··········································
dev.tonymuka.com | UNREACHABLE! => {                                                                                                                                                               │··········································
    "changed": false,                                                                                                                                                                              │··········································
    "msg": "Failed to connect to the host via ssh.",                                                                                                                                               │··········································
    "unreachable": true                                                                                                                                                                            │··········································
}                                                                                                                                                                                                  │··········································
tmuka@tMythtv:~/debops-wordpress$ scp README.md root@dev.tonymuka.com:/tmp/                                                                                                                        │··········································
README.md                                                                                                                                                        100% 2339     2.3KB/s   00:00     │··········································
tmuka@tMythtv:~/debops-wordpress$ dig dev.tonymuka.com +short                                                                                                                                      │··········································
64.137.246.121
```

**Comment by drybjed** [comment]
@tmuka You mentioned that you added the entry for the remote host in `/etc/hosts` - you mean just on the Ansible Controller machine, ie. your workstation? In that case it won't work, because Ansible uses the information from the remote host itself to delegate the task. In other words, the remote host needs to be able to resolve the same FQDN as your Ansible Controller. Try and dig that domain on the remote host itself, see what you get.

**Comment by tmuka** [comment]
thanks, @drybjed 

correct. i previously removed the ansible controller machine hosts file entry workaround.  the fqdn resolves correctly on the remote and local hosts.  is it possible ansible is caching the old nslookup?

```
tmuka@tMythtv:~/debops-wordpress$ ssh root@dev.tonymuka.com dig +short dev.tonymuka.com                                                                                                            
64.137.246.121  
```

**Comment by drybjed** [comment]
Hold on a minute, I just noticed your error message about Ansible unable to connect... Can you show contents of your `ansible/inventory/hosts` file?

**Comment by tmuka** [comment]
sure, i really appreciate your help on this!

```
[debops_all_hosts]                
#<hostname>                       
#64.137.246.121                   
dev.tonymuka.com                  

[wordpress]                       
#<hostname>                       
#64.137.246.121                   
dev.tonymuka.com                  
```

i didn't have my remote ubuntu vm "hostname" set to match my fqdn, perhaps that is the issue? i just updated that and will try again too.  therefore, where my remote /etc/hosts file had
`127.0.0.1 ubuntu` it now says `127.0.0.1 dev.tonymuka.com`. fingers crossed!

**Comment by drybjed** [comment]
No, you cannot use the `127.0.0.1 dev.tonymuka.com` that way, let me explay why:

The combination of `debops.mariadb_server` and `debops.mariadb` roles was designed so that you can either use them on the same host, locally relative to the remote host you are managing, or the MariaDB database can be hosted on a different host and accessed remotely. To accomplish that, the roles use `delegate_to` Ansible functionality, in a somewhat convoluted manner. if the MariaDB server is expected to be used "locally" relative to the remote host, which is the default case, the tasks that manage the database are delegated to that remote host using `ansible_fqdn` variable. This is done, so that tasks won't be delegated to `localhost`, which would result in them being run on Ansible Controller.

Remember that Ansible takes the `ansible_fqdn` value from the remote host itself. So what do you get if you use the above line in remote `/etc/hosts`? That depends on the configuration of the DNS. If both hosts (Ansible Controller and remote host) see the same value, we are in agreement, otherwise weird things might happen.

So, the best solution would be to correctly configure your actual DNS zone for `tonymuka.com` so that both Ansible Controller and remote host see the same address at `dev.tonymuka.com` That means that if you cannot manage the DHCP server in your data center to point the host on the correct domain (`tonymuka.com`), you should add something like this to the remote `/etc/hosts`:

```
64.137.246.121 dev.tonymuka.com dev ubuntu
```

As for the Ansible SSH error, try running above command with `-vvvv` to see the SSH errors, maybe that will help fix the issue.

**Comment by tmuka** [comment]
i really appreciate the explanation, i'm excited about this progress!

I arrived at adding the `127.0.0.1 dev.tonymuka.com` hosts file entry when reading help on changing the ubuntu hostname.  I do manage the dns zone, so I commented that out now, and started the ansible tasks again, and it looks like it's working! they're still running, but nginx is running now at http://dev.tonymuka.com/ !!!  that's further than i've made it before!

many thanks to you on your help!  i hope you enjoy the weekend!

**Comment by drybjed** [comment]
Well, it looks like it finished fine. Now it's time to make HTTPS with Let's Encrypt, I wonder how is @carlalexander progressing with that. :-)

**Comment by tmuka** [comment]
yay!  awesome!  thanks again!  i'd be pumped to see Let's Encrypt support rolled in too!

**Comment by carlalexander** [comment]
It's coming. lol
