### ISSUE TITLE
SFTP access to deploy site

### ISSUE THREAD

**Issue by andrewgoodnz** [carlalexander/debops-wordpress#67]
How would you setup  SFTP access to deploy files into /var/www/sitename.com/ ?

We are using Deploybot to handle deployment however I cant access as the right user.

**Comment by carlalexander** [comment]
I'd create another user for deploys. There's a [wiki article](https://github.com/carlalexander/debops-wordpress/wiki/How-to-manage-additional-users) that should walk you through the process. I found this [docs page](http://support.deploybot.com/article/829-how-do-i-set-up-public-key-authentication-for-sftp-shell-deployments) that explains how to get the public key for DeployBot. You'll probably need to put that user in the `www-data` group.

**Comment by andrewgoodnz** [comment]
Cheers! All working now :)

**Comment by andrewgoodnz** [comment]
Well almost.. Deploybot connects with the new user "deploy" and is able to create directories but fails when creating/updating files.

`attempt failed with the following server response: "Permission denied: /var/www/site_url.com/wp-settings.php"`

**Comment by carlalexander** [comment]
Ok, it's because the directory only lets `www-data` write to it. This is still new ground for the project. We have a few tickets open for automating deployments with different solutions. I just haven't gotten to it yet.

For now, a quick workaround is to just login and run `chmod -R 775 /var/www/site_url.com`. This should let DeplyBot do its thing.

**Comment by carlalexander** [comment]
Did this work?

**Comment by andrewgoodnz** [comment]
Yea it worked although maybe not the nicest solution. I needed to add a few scripts to run before and after the code deployment. 
1. Do chmod as you suggested
2. deploy code
3. chown all files to www-data:www-data (the deploy user creates files as itself which cant be read)
4. chmod back to "normal" (755 for dirs, 644 for files)
