### ISSUE TITLE
ERROR! the role 'debops.backporter' was not found

### ISSUE THREAD

**Issue by alveshelio** [carlalexander/debops-wordpress#68]
Hi,

I'm getting this error:

ERROR! the role 'debops.backporter' was not found in /root/.local/share/debops/debops-playbooks/playbooks/env/roles:/root/.local/share/debops/debops-playbooks/playbooks/env:/home/debops-wordpress/roles:/home/debops-wordpress/ansible/roles:/root/.local/share/debops/debops-playbooks/playbooks/../roles:/root/.local/share/debops/debops-playbooks/playbooks/roles:/etc/ansible/roles:/root/.local/share/debops/debops-playbooks/roles

The error appears to have been in '/root/.local/share/debops/debops-playbooks/roles/debops.ruby/meta/main.yml': line 15, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

```
# Backport 'rubygems-integration' package
```
- role: debops.backporter
  ^ here

I've followed the installation steps. I'm on Ubuntu 14.04

**Comment by alveshelio** [comment]
I was able to solve this issue by installing dbops.backporter with this command:
ansible-galaxy install debops.backporter

**Comment by carlalexander** [comment]
Was this with a fresh install?

**Comment by drybjed** [comment]
Looks like a recent change in `debops/debops-playbooks` repository backfired, and some of the roles that are included in the main playbook are not installed correctly. I'll have to fix that soon.

**Comment by alveshelio** [comment]
Hi @carlalexander,

Yes it was a fresh install. I've launched a server on Digital Ocean and started from scratch.

I am having other issues running this command: debops -u root, I'll create a new issue for this though.

Thanks guys

**Comment by drybjed** [comment]
I've added back the roles that were removed previously, so that error shouldn't happen anymore.

**Comment by kleinaber** [comment]
I ran into a similar problems, but the packages missing where:

debops.dnsmasq
debops.docker_gen
debops.dovecot
debops.postgresql_server
debops.gitlab

I was able to fix it with the suggested command.
Just wanted to let you know.
