### ISSUE TITLE
fatal: [mysite.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

### ISSUE THREAD

**Issue by alveshelio** [carlalexander/debops-wordpress#69]
Hi guys,

When I run command debops -u root I'm getting this error:
fatal: [mysite.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
PLAY RECAP *********************************************************************
mysite.com                : ok=0    changed=0    unreachable=1    failed=0

TASK: setup ------------------------------------------------------------- 0.97s

When I run the command debops -u root -vvvv I get the following output:
<mysite.com> ESTABLISH SSH CONNECTION FOR USER: root
<mysite.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r mysite.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1464709734.13-184742552051869`" && echo ansible-tmp-1464709734.13-184742552051869="`echo $HOME/.ansible/tmp/ansible-tmp-1464709734.13-184742552051869`" ) && sleep 0'"'"''
fatal: [mysite.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/root/.local/share/debops/debops-playbooks/playbooks/site.retry

I've properly configured the domain in Digital Ocean, when I ping the domain it points to the right IP, if I do a whois I get the right information.

Any ideas what I'm doing wrong?

**Comment by andrewgoodnz** [comment]
I got this error too at the start, found out i needed to specify the location of the ssh key

`debops -u --private-key=pathtosshkey.pem`

**Comment by carlalexander** [comment]
Did you setup your DO droplet with a SSH key?

**Comment by ggloveswp** [comment]
Facing the same issue. Do I need to bundle something in .pem (regarding andrew's response?)
I tried debops -u --private-key=/location/of/file.pub with no luck

**Comment by alveshelio** [comment]
Hi @carlalexander,

Yes I've added my SSH Key when I've created the droplet.
I actually don't have any .pub file in ~/.ssh folder, should I generate one?

**Comment by carlalexander** [comment]
Yeah, that's probably the issue. Ansible will try to use your SSH config in `~/.ssh`.

**Comment by alveshelio** [comment]
Hi @carlalexander,

I'm still having the same problem.

Here's what I did, I've generated an SSH key, I've followed the instructions here: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

now in /home/root/.ssh, I have two files, id_rsa.pub and id_rsa. I have run this command: 
debops -u root --private-key=~/.ssh/id_rsa.pub
but I'm still getting the same error :(

@andrewgoodnz said that he used this command: debops -u --private-key=pathtosshkey.pem I don't have any pem file.

I'm wondering what I'm doing wrong. Should I simply destroy the droplet and start from the ground up and not add any key?

**Comment by andrewgoodnz** [comment]
@alveshelio are you able to ssh into server normally?

`ssh -i ~/.ssh/id_rsa.pub root@123.456.789.012`

I was setting up on an AWS EC2 instance which provides the .pem

**Comment by alveshelio** [comment]
@andrewgoodnz I am able to login with the ssh key. Before I was not but then I've deleted my id_rsa and id_rsa.pub files and I've followed this guide: https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2

Now I'm able to connect with the SSH key but I'm still getting the same error :(

**Comment by andrewgoodnz** [comment]
Does the domain you put in the 'inventory/hosts' file point to the IP of your droplet?

**Comment by alveshelio** [comment]
Yes it does

I've purchased a domain just to test younik.info and I've pointed it to my DO droplet, in my Digital Ocean Networking panel I've added the domain, when I ping younik.info it points to the server IP. So I guess this is well set up.

**Comment by andrewgoodnz** [comment]
Can you paste the full output of
`debops -u root --private-key=~/.ssh/id_rsa.pub`

I am running out of ideas here. @carlalexander have you got any other pointers?

**Comment by drybjed** [comment]
@alveshelio Just to get things out of the way:
- how do you plan to use Ansible, do you want to run it from your own workstation and configure a remote host, or do you want to run Ansible on a remote host to configure it?
- what are the contents of `ansible/inventory/hosts` file?

**Comment by carlalexander** [comment]
If you still have to use `ssh -i`,  we haven't solved the problem for `debops -u --private-key=pathtosshkey.pem`. You need to be able to connect to your server by running `ssh root@wordpress.example.com`. If you're getting an error there, that's what we need to fix.

**Comment by alveshelio** [comment]
@andrewgoodnz, this is the output of the command

Running Ansible playbook from:
/root/.local/share/debops/debops-playbooks/playbooks/site.yml ...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Prepare core environment] ************************************************

TASK [setup] *******************************************************************
fatal: [younik.info]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/root/.local/share/debops/debops-playbooks/playbooks/site.retry

PLAY RECAP *********************************************************************
younik.info                : ok=0    changed=0    unreachable=1    failed=0

TASK: setup ------------------------------------------------------------- 1.34s

@drybjed this is what I have in my hosts file

```
# This is an Ansible inventory file in INI format. You can define a list of
# hosts and groups to be managed by this particular inventory.

# Hosts listed under [debops_all_hosts] will have common DebOps plays
# ran against them. It will include services such as iptables, DNS, Postfix,
# sshd configuration and more.
#
# View the list here:
# https://github.com/debops/debops-playbooks/blob/master/playbooks/common.yml

[debops_all_hosts]
#<hostname>
#http://159.203.37.143
younik.info

[wordpress]
#<hostname>
#http://159.203.37.143
younik.info
```

@drybjed you are asking how do I plan to use Ansible, right now all the commands I'm running them in my server, I didn't know I could use them on my computer. I'm on a Mac and to be honest, I'm quite inexperienced with Server Administration so I was simply following the steps for the installation and hopping everything would go well :)

@carlalexander I can connect using ssh root@younik.info without a problem I'm not asked for the password.

I think I might need to trash the server and start over? Or do you guys have a better idea?

Thank you all for your help, really appreciated.

**Comment by drybjed** [comment]
@alveshelio Ah yes, the information that you are running the Ansible playbook on that remote server is cruical. By default, everything is set up to execute over SSH. With your inventory, the host is trying to SSH to itself, and failing.

Read [my comment in another thread](https://github.com/carlalexander/debops-wordpress/issues/70#issuecomment-222918919) to see how you can run Ansible and DebOps "locally" relative to the remote host.

**Comment by alveshelio** [comment]
Hi @drybjed,

It definitely helped adding ansible_connection=local in [debops_all_hosts]

I didn't know that Ansible needed to be installed in my computer and I was trying to run it in the server. By adding ansible_connection=local it solved my problem.

I'm now trying to run it from my computer but I have python 3.5 and Ansible seems to have a problem with it, so I need to go configure my computer to be able to use both python 3.5 and 2.7.

Thank you again for the precious help.

**Comment by caramiame** [comment]
read through the links on the two that I followed to do one manually on the command line 

```
On Tuesday, May 31, 2016 9:12 PM, andrewgoodnz <notifications@github.com> wrote:
```

 Does the domain you put in the 'inventory/hosts' file point to the IP of your droplet?—
