### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by tigerdencafe** [carlalexander/debops-wordpress#71]
we have tried to install DebOps, Ansible on cpanel and plain servers.

But the installation stops due to server requirements. 

while trying to login through the debops we are facing errors.

Also we have configured Ansible on plain server. While trying to deploy the wordpress on remote we are facing conflict errors due to pre -installed Mysql and other services.

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @playbook.retry

PLAY RECAP *********************************************************************
IP.AD.D.RESS               : ok=2    changed=0    unreachable=0    failed=1 

can you please help me out

**Comment by carlalexander** [comment]
Have you gone through the getting started guide in the [wiki](https://github.com/carlalexander/debops-wordpress/wiki)? What's in your `hosts`file?

**Comment by carlalexander** [comment]
Have you gotten this working?

**Comment by tigerdencafe** [comment]
hi we went through the wiki, and followed the steps but we have not found a solution to the same yet we get the same error

**Comment by drybjed** [comment]
Hello. I'm afraid that the issue might be CPanel interfering with deployment somehow. DebOps is designed to be deployed on minimal Debian installs, other configurations are not really tested.

Although the above error messages just indicate that "there was an error". Is there something else before that which could help with debugging? Also, in Ansible inventory, is your host included at least in the `[debops_all_hosts]` group?

**Comment by carlalexander** [comment]
Did you try what @drybjed said  @tigerdencafe?

**Comment by tigerdencafe** [comment]
yes i tried @carlalexander what @drybjed  said and he was right it does not work with cpanel server with centos and was giving errors 

it worked on ubuntu did not try debain yet, but ubuntu as a webserver ? 

thank you very much @drybjed your input helped a lot

**Comment by carlalexander** [comment]
Awesome, closing! 😄
