### ISSUE TITLE
How to access Wordpress Password and MariaDB password

### ISSUE THREAD

**Issue by alveshelio** [carlalexander/debops-wordpress#72]
Hi guys,

I've finished the installation and everything is working fine, however I'm having some trouble getting the password for Wordpress admin and mariadb.

in the doc it says that to retrieve the admin password I should go here:
secret/wordpress/younik.info/credentials/admin/password
And for mariadb
secret/mariadb/younik.info/credentials/wordpress/password

I'm not sure whether or not I need to access it in my browser or somewhere else but when I try to access these URLs I get "This site can’t be reached"

Any thoughts?

**Comment by carlalexander** [comment]
It's the path based on the root of the project. It's not a URL :)

**Comment by alveshelio** [comment]
@carlalexander 👍  thank you very much.
