### ISSUE TITLE
want to install this on aws with aws-cli package installed.

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#79]
Hi Carl,

could you make a wiki page on how to add other packages to the installation?
in particular i need to be able to connect the ec2 instance to s3 and for that i need aws-cli. was also thinking of installing phantomjs for above the fold inline css

best,
C

**Comment by cezarneaga** [comment]
running `debops -u ubuntu --private-key=...` goes well
somehow `debops wordpress -u ubuntu --private-key=...` fails on 

`TASK [debops.mariadb : Create databases] ***************************************
failed: [aws.cezarneaga.eu] (item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [aws.cezarneaga.eu]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}
    to retry, use: --limit @/Users/cezar/mhpss/playbooks/wordpress.retry`

EDITED: saw the other related issue :)
sorry

**Comment by carlalexander** [comment]
So this second thing is related to #76? As for the extra package wiki, this is a great idea!

**Comment by cezarneaga** [comment]
yes, it is related to #76  :)
hope you can help me there
