### ISSUE TITLE
roles/hhvm/defaults/main.yml missing /  ?

### ISSUE THREAD

**Issue by jpurpleman** [carlalexander/debops-wordpress#8]
the line ~ 28 =   'repo.central.path': 'var/run/hhvm/hhvm.hhbc'

I could be wrong but you might be missing a leading / on var.

**Comment by carlalexander** [comment]
I think you might be right. I'll fix it locally and test it first.

**Comment by carlalexander** [comment]
Ran some tests. Looks good. It was typo!
