### ISSUE TITLE
how does one perform an update on an ansible managed server?

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#80]
i tried 
sudo apt-get update && sudo apt-get upgrade
but still shows i need updates

best,
C

**Comment by carlalexander** [comment]
Was there an error? That should be all you need to do.

**Comment by cezarneaga** [comment]
No error but when i log out and back in the same no of updates needed shows up

**Comment by cezarneaga** [comment]
had to perform reboot on machine. 
solved.
