### ISSUE TITLE
debops.ferm and avoid being locked out

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#81]
Once changed the role in debops to either 
`ferm__filter_syn: False` or 
by increasing the limits of the parameters can i run debops -u root on an existing machine?
what would be the right command - --limit ...?

Is there a way to remove rate limitations if the root is creating them through ssh?

what if like me you have a chat plugin installed on the wp installation that pings every 2 seconds. this locked me out too.
cheers,
C

**Comment by carlalexander** [comment]
I believe you can run something like `debops -u root --tags role::ferm`. This should only run the `debops.ferm` role. You use `--limit` for targeting a specific host or set of hosts.

As for the rate limitations, @drybjed might know. I haven't done any rate limitation from the firewall.

**Comment by drybjed** [comment]
You can execute specific roles via their service playbooks by specifying the playbook as the first parameter of the `debops` command. For example to run only the `debops.ferm` role, you can use:

```
debops service/ferm -u root --limit hostname
```

Only the first parameter is checked, so the order is important.

You can configure the ICMP rate limits in the `debops.ferm` role, [using these variables](https://github.com/debops/ansible-ferm/blob/master/defaults/main.yml#L110-L132).

SSH rate limits and filtering is configured by the `debops.sshd` role, [here are specific variables](https://github.com/debops/ansible-sshd/blob/master/defaults/main.yml#L111-L143).

**Comment by cezarneaga** [comment]
Thanks so much guys. Will give this a shot

**Comment by carlalexander** [comment]
Did this work?

**Comment by cezarneaga** [comment]
Haven't applied it yet.

**Comment by cezarneaga** [comment]
Hi,

just ran the command. worked fine. will report back later if it worked. not sure how i could check on server if things were applied, except by trying to bust it again. 

i did a loader.io test now with 1000 clients per minute and it was incredible. see below.
![test](https://cloud.githubusercontent.com/assets/645227/16610660/f074228c-435c-11e6-80de-a4c4e413099c.png)

cheers,
C

**Comment by carlalexander** [comment]
Sweet! Smallest DO droplet?

**Comment by cezarneaga** [comment]
nope, this is the AWS ubuntu (m3.medium) where i have issues that ftp doesnt work. so far i think its because aws doesnt allow root user but ubuntu and your setup works differently. but i digress. :) yet again.

**Comment by jbicha** [comment]
I was getting locked out of ssh until I applied the `ferm__filter_syn: False` fix.
