### ISSUE TITLE
Wiki inconcistency between Table of contents and actual content

### ISSUE THREAD

**Issue by tobiasmuehl** [carlalexander/debops-wordpress#82]
On the [recommended plugins page](https://github.com/carlalexander/debops-wordpress/wiki/Recommended-plugins) 4 plugins are listed in the table of contents, but only 3 exist in the wiki page.

Since Responsive Images are built into WordPress, the 4. plugin item can be removed from the table of contents.

**Comment by carlalexander** [comment]
Good catch! Fixed!
