### ISSUE TITLE
Migrate to Xenial/PHP 7

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#87]
Xenial has been out for a few months. The first point release is about to come out which will make it the official LTS version at that point. I'm going to look at migrating the entire project to it. This change to Xenial will bring a few big changes:
### Drop HHVM support for PHP 7.

PHP 7 is the default PHP version on Xenial. Since it performs as well as HHVM, but is more stable. We're going to drop the `hhvm` role for `debops.php`. This will also allow us to fix #55 since we'll be able to configure individual fpm pools.
### No more PHP 5 failover

Continuing with the switch to PHP 7. We're also going to lose the fallback to PHP 5. That's because Xenial has [dropped support for PHP5](https://www.symfony.fi/entry/php-7-included-in-ubuntu-16-04-lts-xenial-xerus). We could add a custom upstream and compile two versions, but I'll hold off for now.
### Drop upstream APT repository for Varnish

This is a more minor change is the removal of the Varnish upstream. Xenial supports Varnish 4.1 by default which is what the `varnish` role installed.

**Comment by tobeycodes** [comment]
Very excited for this.

**Comment by carlalexander** [comment]
On a fresh Xenial machine, Ansible runs into issues since Python2 doesn't come installed like with 14.04. I've documented the issue [here](https://github.com/debops/debops-playbooks/issues/288). We'll see what can be done on the DebOps side and what needs to be handled by us.

**Comment by carlalexander** [comment]
The debian package for wp-cli is also [broken](https://github.com/wp-cli/wp-cli/issues/3206) on a fresh install of Xenial.

**Comment by carlalexander** [comment]
Alright, it looks like outside these two documented issues. Everything else worked fine for the playbook. 

Blank screen [issue](https://github.com/carlalexander/debops-wordpress/issues/) still seems to be there. So that probably means it's a Varnish issue.

Right now, I can't merge this because both issues are blocking. `wpcli` role could be reverted to not using the Debian package at worst. But the Python2 issue needs some more upstream work I think.

**Comment by blindpet** [comment]
The Varnish problem may actually be an Ubuntu 16.04 Varnish package issue related to ipv6. If you specify the ipv4 address to use for Varnish in its systemd script then supposedly the ipv6 issue is resolved.

**Comment by carlalexander** [comment]
As per @drybjed's comment, it seems we need to run `debops.bootstrap` with Xenial. I'll run some more tests tonight.

**Comment by carlalexander** [comment]
It's not quite that issue @blindpet. The blank page is just that, when you install a plugin, the WordPress page gets stuck.

**Comment by drybjed** [comment]
@carlalexander With Digital Ocean, you could look into configuring initial host steps through their API:
- [How To Use Cloud-Config For Your Initial Server Setup](https://www.digitalocean.com/community/tutorials/how-to-use-cloud-config-for-your-initial-server-setup)
- [An Introduction to Cloud-Config Scripting](https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting)

I think that other providers might support similar things as well.

**Comment by carlalexander** [comment]
I'm sure they do. It's just tricky because it's a step outside Ansible and trying to minimize those right now. 😉

**Comment by drybjed** [comment]
You can use Ansible to configure a Digital Ocean droplet, using [digital_ocean module](https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2-with-ansible-2-0-on-ubuntu-14-04). Maybe it has support for `cloud-config` as well, not sure.

**Comment by carlalexander** [comment]
So running `debops bootstrap -u root` solved the python2 issue. We'll need to add some documentation for that. I think it might be time to start working on our own CLI to streamline all these steps as discussed in #11.

The changes to wp-cli Debian package are going to go in, but they're scheduled for the next major release which could be in a few months. I added the old install method as an alternative and put it as the default for now.

I still a few more things to finish. I'm hoping to have this all pushed upstream by next week. Almost done!

**Comment by carlalexander** [comment]
Just pushed all the changes after some extensive testing this week. I updated the README with the three commands necessary now (we have to `debops bootstrap` first).

Please note that there are some BC breaks. I renamed all the variables to follow the new namespacing standard of DebOps. Check the `UPGRADE-0.3.md` document for details.

I'll need to update the documentation closer to when I tag a new version.

**Comment by matthew6688** [comment]
migrate to php7, then the memcached and opac code will not be install and supported?

**Comment by carlalexander** [comment]
Memcached was never supported. This setup uses Redis. What's "opac code"? You mean opcode caching? That's built into PHP since 5.6 (I think)

**Comment by carlalexander** [comment]
Updated all the wiki entries for the new version. Tagged the last commit from two weeks ago. This is a wrap!
