### ISSUE TITLE
Disable access to website via IP address

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#88]
If we have specific a domain we shouldn't be able to see the site via it's IP address

**Comment by carlalexander** [comment]
Can you give me a bit more context. Are you trying to limit access to a specific IP only? Or is it the opposite? Everyone can see except this one IP?

**Comment by tobeycodes** [comment]
If my host is tobyschrapel.com when I visit the servers ip address it should not load tobyschrapel.com

**Comment by carlalexander** [comment]
But it loads for everyone else?

**Comment by tobeycodes** [comment]
It loads for everyone. E.g.

https://45.55.208.66/

**Comment by carlalexander** [comment]
Ohhhhhhhh! I wasn't even thinking the same thing lol! Got it.

**Comment by carlalexander** [comment]
[This](http://serverfault.com/questions/578648/properly-setting-up-a-default-nginx-server-for-https) is the cleanest way I found to do this with SSL. Currently, nginx doesn't have a good way to create a catchall default server for SSL connections.
