### ISSUE TITLE
php-redis No package available?

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#90]
Hi there, 

am having a new problem. i searched and couldn't find any similar issues.

```
failed: [socialimpactaward.de] (item=[u'php5-cli', u'php5-fpm', u'php5', u'php5-curl', u'php5-gd', u'php5-mcrypt', u'php5-mysql', u'php5-curl', u'php5-dev', u'php-redis']) => {"failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": null, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": false, "name": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "only_upgrade": false, "package": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "purge": false, "state": "present", "update_cache": false, "upgrade": null}, "module_name": "apt"}, "item": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "msg": "No package matching 'php-redis' is available"}
```

this is the output from `debops wordpress -vvvv` 

any idea what happened?
its on ubuntu 14. debops updated, latest repo cloned. all else worked fine
Cheers,
C

**Comment by carlalexander** [comment]
Weird never encountered the issue. Package [exists](http://packages.ubuntu.com/source/trusty/php-redis) according to Ubuntu.

**Comment by cezarneaga** [comment]
tried it now 3 times on new servers. same error.
i installed php-redis manually then re-run. no cigar.
before i lost hope i noticed that roles/wordpress/defaults/main.yml line 339 had php-redis in it

```
-- wordpress__php_packages: [ 'mysql', 'curl', 'dev', 'php-redis' ]
++ wordpress__php_packages: [ 'mysql', 'curl', 'dev', 'php5-redis' ]
```

after making this change it worked. maybe its worth looking into it.

the problem now is i get 502 Bad Gateway after successfully completing :)
Cezar

**Comment by drybjed** [comment]
Try changing the package name to `redis`, see if that works. If yes, that's the correct solution.

**Comment by carlalexander** [comment]
Wait, are you using the current master branch on 14.04? You need to use the `v0.2.0` tag  with 14.04. I haven't tested it with the Xenial changes. If anything, I think it'll be broken because I removed the Varnish upstream which means you'll get Varnish 3.

**Comment by cezarneaga** [comment]
thanks @drybjed !
tried that. it completed successfully but still 502 Bad Gateway

**Comment by cezarneaga** [comment]
@carlalexander  yes. shouldn't i?

**Comment by carlalexander** [comment]
No, I didn't maintain BC with 14.04 because there were too many things changing. I tagged a version just before I started working on it. Sorry if that wasn't clear 😞

**Comment by cezarneaga** [comment]
oh. i see. is tag v2... the right one to use?

**Comment by carlalexander** [comment]
Yep, try with `v0.2.0`. I switched from `debops.php5` to `debops.php` when I switched to Xenial. And Xenial doesn't have a `php7.0-redis` package yet so I have to specify that one.

**Comment by cezarneaga** [comment]
now i get this:

```
fatal: [socialimpactaward.de]: FAILED! => {"changed": true, "cmd": ["nginx", "-t"], "delta": "0:00:00.022956", "end": "2016-08-16 12:53:18.836271", "failed": true, "rc": 1, "start": "2016-08-16 12:53:18.813315", "stderr": "nginx: [emerg] BIO_new_file(\"/etc/pki/realms/socialimpactaward.de/default.crt\") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/pki/realms/socialimpactaward.de/default.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stdout": "", "stdout_lines": [], "warnings": []}
```

do i need to install certbot first?
C

**Comment by carlalexander** [comment]
Is this a brand new dropet?

**Comment by cezarneaga** [comment]
its brand new but on aws.

**Comment by carlalexander** [comment]
Yeah, I have no experience with AWS sadly. I'd have to try to setup an
account. I know the branch worked on DO two weeks ago.

**Comment by carlalexander** [comment]
I created an [issue](https://github.com/carlalexander/debops-wordpress/issues/92) for AWS. I'll try to get to it this weekend. There seems to be [issues](https://github.com/carlalexander/debops-wordpress/issues/91) with AWS from what I can see.

**Comment by cezarneaga** [comment]
just to give more context, i followed this process after creating an instance:

```
// change hostname in order for wp to install
sudo vi /etc/hosts
[elastic_ip] web.example.com web 

sudo vi /etc/hostname
web.example.com

sudo reboot

// allow root login https://gist.github.com/tracend/4016872
vi /etc/ssh/sshd_config
PermitRootLogin without-password
RSAAuthentication yes
PubkeyAuthentication yes
AuthorizedKeysFile     .ssh/authorized_keys

// on local
cat ~/.ssh/{{key}}.pem | ssh ubuntu@{{server}} 'cat - >> ~/.ssh/authorized_keys'
//on server
chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh/

vi .ssh/authorized_keys //remove command part
```

this allows you to run stuff just as on DO with root instead of ubuntu.

i wanted to do a wiki on it if it would have worked :)

cezar

**Comment by cezarneaga** [comment]
Hi there,

just tried it with DO, and i get this error now:

```
fatal: [domain]: FAILED! => {"changed": false, "cmd": "apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 1BE7A449", "failed": true, "msg": "gpg: requesting key 1BE7A449 from hkp server pool.sks-keyservers.net\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0", "rc": 2, "stderr": "gpg: requesting key 1BE7A449 from hkp server pool.sks-keyservers.net\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\n", "stdout": "Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.U4CePoZbeZ --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://pool.sks-keyservers.net --recv 1BE7A449\ngpgkeys: key 1BE7A449 can't be retrieved\n", "stdout_lines": ["Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.U4CePoZbeZ --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://pool.sks-keyservers.net --recv 1BE7A449", "gpgkeys: key 1BE7A449 can't be retrieved"]}
```

did you get this one before?
i did put this setting in: `wordpress_ssl: True`

Cezar

**Comment by drybjed** [comment]
The most important bit is missing. What role, which task?
16 sie 2016 18:19 "Cezar Neaga" notifications@github.com napisał(a):

**Comment by cezarneaga** [comment]
not sure i understand but it happened in: 
TASK [hhvm : Get upstream APT GPG key]
i added the `wordpress_ssl: True` setting in: host_vars/[domain]/vars.yml

**Comment by drybjed** [comment]
Great, now we know where to look :)
16 sie 2016 18:23 "Cezar Neaga" notifications@github.com napisał(a):

**Comment by cezarneaga** [comment]
:) love how you and @carlalexander put the time in this project.
i hope you know its appreciated.

thanks
C
PS: if you need any support let me know

**Comment by drybjed** [comment]
@cezarneaga Come over to `#debops` on FreeNode if you're interested, there's more to it than just WordPress, you know. :-) Check out https://debops.org/status.html

**Comment by carlalexander** [comment]
Did you select 14.04 with DO? They default to 16.04.1 now. If you're on 14.04, I'll have to run some tests and see. Sorry, that's the best I can do right now 😞

**Comment by cezarneaga** [comment]
its 14.04 yes

**Comment by cezarneaga** [comment]
i ran `debops wordpress -u root` and this time completed without error.

**Comment by carlalexander** [comment]
Ah yes, you need to do that with Trusty. The new commands are for Xenial.
Sorry again, it's confusing because I don't have version specific docs.
