### ISSUE TITLE
Error during 'Get list of installed Wordpress plugins

### ISSUE THREAD

**Issue by AIM-Media-Indiana** [carlalexander/debops-wordpress#91]
Hello!

I've run into an error that I can't seem to get past during the second 'phase' of the install.  It's acting like WordPress never fully installed and then it fails while trying to get the list of installed WordPress plugins.  Here's the error message:

TASK [wordpress : Get list of installed WordPress plugins] *********************
fatal: [new.hnedigital.com]: FAILED! => {"changed": false, "cmd": ["wp", "plugin", "list", "--format=json"], "delta": "0:00:00.151426", "end": "2016-08-15 20:52:01.093710", "failed": true, "rc": 1, "start": "2016-08-15 20:52:00.942284", "stderr": "Error: The site you have requested is not installed.\nRun `wp core install`.", "stdout": "", "stdout_lines": [], "warnings": []}

This was run on a fresh Ubuntu 14.04 install on AWS.  I did setup the FQDN before I started any of the install process.

Can you offer any suggestions?

Thanks!
Scott

**Comment by carlalexander** [comment]
@AIM-Media-Indiana Are you using the `v0.2.0` with 14.04?

**Comment by AIM-Media-Indiana** [comment]
@carlalexander - I believe so yes.  I ran the following to setup the project on my local machine:

```
git clone https://github.com/carlalexander/debops-wordpress.git
cd debops-wordpress/
git checkout tags/v0.2.0
```

**Comment by carlalexander** [comment]
What happens if you run `wp core install` by hand? I haven't tested anything on AWS. Does AWS have 16.04.1 yet?

**Comment by AIM-Media-Indiana** [comment]
I get an error message when running it by hand.  Here's the command and error:

```
ubuntu@new:/var/www/new.hnedigital.com$ wp core intall
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

That seems odd because in the log file for the script it does seem to be doing OK at downloading and installing.  Here's that part of the log:

```
TASK [wordpress : Create WordPress directory] **********************************
ok: [new.hnedigital.com]

TASK [wordpress : Configure wp-cli] ********************************************
ok: [new.hnedigital.com]

TASK [wordpress : Check if WordPress is installed] *****************************
ok: [new.hnedigital.com]

TASK [wordpress : Download WordPress] ******************************************
ok: [new.hnedigital.com]

TASK [wordpress : Configure WordPress] *****************************************
ok: [new.hnedigital.com]

TASK [wordpress : Install WordPress] *******************************************
skipping: [new.hnedigital.com]

TASK [wordpress : Install WordPress Multisite] *********************************
skipping: [new.hnedigital.com]

TASK [wordpress : Schedule regular calls to wp-cron.php] ***********************
ok: [new.hnedigital.com]

TASK [wordpress : Get list of installed WordPress plugins] *********************
fatal: [new.hnedigital.com]: FAILED! => {"changed": false, "cmd": ["wp", "plugin", "list", "--format=json"], "delta": "0:00:00.151426", "end": "2016-08-15 20:52:01.093710", "failed": true, "rc": 1, "start": "2016-08-15 20:52:00.942284", "stderr": "Error: The site you have requested is not installed.\nRun `wp core install`.", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by carlalexander** [comment]
Right, it does seem weird. I created an [issue](https://github.com/carlalexander/debops-wordpress/issues/92) for AWS compatibility. I have just not tried it at all and I'm not sure if @drybjed tried DebOps with it either.

**Comment by carlalexander** [comment]
I'm going to close this for now, but the AWS issue is still one of my next priorities.
