### ISSUE TITLE
Test compatibility with AWS

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#92]
AWS is a popular hosting option and it doesn't seem like the project is working well on it. We need to test compatibility with AWS and document how to setup a server on the platform.

**Comment by carlalexander** [comment]
Did some testing on AWS today. I haven't been able to get past the step to create MariaDB databases. I'm using the `0.2.0` tag with some fixes since Xenial isn't on AWS yet.

There was an issue connecting to the database via SSH since AWS requires a certificate file to connect. You could solve this by forcing the local connection with `mariadb__delegate_to: '127.0.0.1'`. This worked fine.

The new issue is that it says `sudo: a password is required` when trying to create a database. My guess is that it's related to the fact that AWS doesn't use the `root` account. Instead, it uses the `ubuntu` account.

Not too sure what the workaround is at this point? Will give it another go at it soon.

**Comment by cezarneaga** [comment]
you could try this before: https://github.com/carlalexander/debops-wordpress/issues/90#issuecomment-240114080

then you can use root

**Comment by carlalexander** [comment]
Ran some more tests today with `root` as the user. Still doesn't work. I get "Failed to connect to the host via ssh." I'll need to dive deeper into `debops.mariadb` and see what's going on.

**Comment by carlalexander** [comment]
Closing this in favour of #205
