### ISSUE TITLE
tag v0.2.0 installs multisite by default

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#93]
Hi Carl,

i ran the installation twice now (fresh installs for different domains) using the tag v0.2.0 and it installed a multisite each time. i deleted the wp-config multisite stuff and imported the already existing database of the single site which solved the problem.

the only thing that doesnt work is that the media library doesnt show old media. i think perhaps it's due to blogs uploads urls config that maybe persists in nginx somewhere.

i added `wordpress_multisite: False` to the host_vars/[domain]/vars.yml and re-ran `debops wordpress -u root` but still nothing. could you help me out?

thanks,
C

**Comment by carlalexander** [comment]
Yeah, I slipped a bug right before the tag. You can fix it by applying the fix in this [commit](https://github.com/carlalexander/debops-wordpress/commit/c925db560ea5d2d65a5723e3db226d6d18ffa3a6). Sorry 😞

**Comment by cezarneaga** [comment]
No problems :)
re-running `debops wordpress -u root` would fix the media library issue or should i reinstall everything from scratch?

**Comment by carlalexander** [comment]
I think that you'll have to reinstall from scratch.

**Comment by cezarneaga** [comment]
doing it now. will consider it closed but maybe add a tag v0.2.1 :)
