### ISSUE TITLE
Media library bug

### ISSUE THREAD

**Issue by cezarneaga** [carlalexander/debops-wordpress#94]
so i ran a perfect installation. 

it works very well but if i import the older website (db and files) the media library gets replaced with the default pngs. files work if i follow the url. permissions are fine, owner and group fine.

![media library](https://cloud.githubusercontent.com/assets/645227/17753679/2c0eba42-64d1-11e6-895f-7098bdb21945.png)

anyone has experience importing files after setup?
thanks
C

**Comment by carlalexander** [comment]
Everything is owned `www-data`? You have to change the permissions if I recall correctly because they'll be under the user that uploaded the files.

**Comment by cezarneaga** [comment]
i forgot to say that it works well with new uploads. they show up fine. they are `www-data:www-data`

**Comment by carlalexander** [comment]
New uploads should have the proper file permissions, but not files you upload via FTP for examples

**Comment by cezarneaga** [comment]
i ran `chown -R www-data:www-data wp-content` after uploading them.

**Comment by carlalexander** [comment]
What happens if you try to edit an image?

**Comment by cezarneaga** [comment]
![media library edit](https://cloud.githubusercontent.com/assets/645227/17754418/b2f8eca0-64d4-11e6-9efa-2636c5ce0f7d.png)

**Comment by cezarneaga** [comment]
the edit more details that takes you to `.../wp-admin/post.php?post=1004&action=edit` shows the image but the image url is broken: `https://newviennacongress.eu/wp-content/uploads//VVO-Versicherungsverband-Oesterreich.jpg`
![edit media advanced](https://cloud.githubusercontent.com/assets/645227/17754644/d055bb2e-64d5-11e6-9718-254e54491210.png)

**Comment by carlalexander** [comment]
The year/date is missing from the URL. Was that the case on the old site?

**Comment by cezarneaga** [comment]
no. had them there before. the database has year/month/ 
it's somehow a setting in wp?

**Comment by cezarneaga** [comment]
solved it. its my bad. db import was the cause.
