### ISSUE TITLE
Issue can't connect to host via ssh

### ISSUE THREAD

**Issue by matthew6688** [carlalexander/debops-wordpress#96]
The error message:

ASK [setup] *******************************************************************
fatal: [balaxidata.com]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    to retry, use: --limit @/root/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
balaxidata.com             : ok=0    changed=0    unreachable=1    failed=0   

I am using Digital Ocean ubuntu 14.04. 

What to do now? Any idea what is the problem

**Comment by carlalexander** [comment]
I need a more detailed log than this. Can you show me the output with `-vvvv`?

**Comment by matthew6688** [comment]
TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu-512mb-sgp1-01> ESTABLISH SSH CONNECTION FOR USER: root
<ubuntu-512mb-sgp1-01> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r ubuntu-512mb-sgp1-01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472542965.22-177820340248465`" && echo ansible-tmp-1472542965.22-177820340248465="`echo $HOME/.ansible/tmp/ansible-tmp-1472542965.22-177820340248465`" ) && sleep 0'"'"''
failed: [ifengshuo.cn](item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [ifengshuo.cn]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}

**Comment by carlalexander** [comment]
You can't use the default droplet name like `ubuntu-512mb-sgp1-01`. You need a full domain name as per the [wiki article](https://github.com/carlalexander/debops-wordpress/wiki/Create-a-Digital-Ocean-droplet).

**Comment by carlalexander** [comment]
This is the same error as #97. Can you please close this issue or the other one. Thanks! 😄
