### ISSUE TITLE
Run into issues (Digital Ocean Ubuntu 14.04 fresh set up)

### ISSUE THREAD

**Issue by matthew6688** [carlalexander/debops-wordpress#97]
Run into the problems in the last wordpress install 

TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu-512mb-sgp1-01> ESTABLISH SSH CONNECTION FOR USER: root
<ubuntu-512mb-sgp1-01> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r ubuntu-512mb-sgp1-01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472542965.22-177820340248465`" && echo ansible-tmp-1472542965.22-177820340248465="`echo $HOME/.ansible/tmp/ansible-tmp-1472542965.22-177820340248465`" ) && sleep 0'"'"''
failed: [ifengshuo.cn](item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [ifengshuo.cn]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}

Anyone have this problem before?

Regards,

Matthew

**Comment by matthew6688** [comment]
Also i am running into issue below, when i execute the command: **sudo pip install ansible debops passlib pycrypto**

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-sNjj8b-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log

**Comment by matthew6688** [comment]
When i run debops -u root command, the error message below:



root@ubuntu-512mb-sgp1-01:~/debops-wordpress# debops -u root
Running Ansible playbook from:
/root/.local/share/debops/debops-playbooks/playbooks/site.yml ...
ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 79, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 30, in <module>
    from ansible.executor.playbook_executor import PlaybookExecutor
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 27, in <module>
    from ansible.executor.task_queue_manager import TaskQueueManager
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 28, in <module>
    from ansible.executor.play_iterator import PlayIterator
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/play_iterator.py", line 29, in <module>
    from ansible.playbook.block import Block
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/__init__.py", line 25, in <module>
    from ansible.playbook.play import Play
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 27, in <module>
    from ansible.playbook.base import Base
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/base.py", line 32, in <module>
    from jinja2.exceptions import UndefinedError
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

**Comment by matthew6688** [comment]
Thank you. I really didn't notice the droplet need to be the same with domain name, I will correct the name and retry now. Thank you. @carlalexander

**Comment by matthew6688** [comment]
I correct the droplet name, and retry, it is new issue as below:

TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<ubuntu-512mb-sgp1-01> ESTABLISH SSH CONNECTION FOR USER: root
<ubuntu-512mb-sgp1-01> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r ubuntu-512mb-sgp1-01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472547642.08-70389455680224`" && echo ansible-tmp-1472547642.08-70389455680224="`echo $HOME/.ansible/tmp/ansible-tmp-1472547642.08-70389455680224`" ) && sleep 0'"'"''
failed: [ifengshuo.cn](item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [ifengshuo.cn]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}

I am using Mac ox, and already do the known issues, still the problem, please have a look

**Comment by carlalexander** [comment]
How did you change the domain name of the droplet? I'm still seeing `ubuntu-512mb-sgp1-01` in the output?

**Comment by matthew6688** [comment]
@carlalexander I actually restore from snapshot, and the server name didn't change. so it is the same mistakes.

After that i destroy and restart new server in DG.  This time, it still shows the below mistakes in the debops -u root command:

`TASK [setup] *******************************************************************
<ifengshuo.cn> ESTABLISH SSH CONNECTION FOR USER: root
<ifengshuo.cn> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r ifengshuo.cn '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1472609541.41-114133961749547 `" && echo ansible-tmp-1472609541.41-114133961749547="` echo $HOME/.ansible/tmp/ansible-tmp-1472609541.41-114133961749547 `" ) && sleep 0'"'"''
fatal: [ifengshuo.cn]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
 [WARNING]: Could not create retry file '/Users/ringse/Library/Application
Support/debops/debops-playbooks/playbooks/site.retry'.         [Errno 13]
Permission denied: '/Users/ringse/Library/Application Support/debops/debops-
playbooks/playbooks/site.retry'`

I have tested that, i can login server through ssh just fine. and the domain name have well pointed to my server ip address. and the server name is named after my domain name. 

Can you troubleshoot for me?   Because i don't know anything about the server set up, and i have been follow you your server set up through Zach hgv-deploy-full.  I have implement his set up, the server is fast, but still have some varnish set up problems.

**Comment by matthew6688** [comment]
It is very werid.

After i change the host name to my server ip address, not the domain name.  Now the command debops -u root is proceeding.

But I do check about ping my host name in the terminal. It is showing the domain name is correctly resolve to my server ip.

Can't understand. 

Will it ok, if i proceed with the server ip as the host name?

**Comment by matthew6688** [comment]
When i proceed with host name set up to my server ip address.

The debops -u root have successfully executed.

Run into the new problem when i type: debops wordpress -u root:

`TASK [debops.postfix : DebOps pre_tasks hook] **********************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.postfix/tasks/main.yml:3
fatal: [188.166.224.192]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}`

I do checked the known issues, and add link and edit the .debops.cfg files accordingly.

Any idea what might happen?

**Comment by carlalexander** [comment]
This last one might be fixed by following this [workaround](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found).

**Comment by matthew6688** [comment]
when should i start this workaround, right before debops wordpress command? 
------------------ Original ------------------

**Comment by carlalexander** [comment]
Yes

**Comment by matthew6688** [comment]
TASK [debops.nginx : Generate custom nginx snippets] ***************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.nginx/tasks/main.yml:128
<fengsyringe.com> ESTABLISH SSH CONNECTION FOR USER: root
<fengsyringe.com> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r fengsyringe.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472640125.08-279832275816508`" && echo ansible-tmp-1472640125.08-279832275816508="`echo $HOME/.ansible/tmp/ansible-tmp-1472640125.08-279832275816508`" ) && sleep 0'"'"''
<fengsyringe.com> PUT /var/folders/3k/qjrv5lss4gbglbwvhchkncz00000gn/T/tmpYdZzpI TO /root/.ansible/tmp/ansible-tmp-1472640125.08-279832275816508/stat
<fengsyringe.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r '[fengsyringe.com]'
<fengsyringe.com> ESTABLISH SSH CONNECTION FOR USER: root
<fengsyringe.com> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r -tt fengsyringe.com '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1472640125.08-279832275816508/stat && sleep 0'"'"''
<fengsyringe.com> PUT /var/folders/3k/qjrv5lss4gbglbwvhchkncz00000gn/T/tmpiMGlsz TO /root/.ansible/tmp/ansible-tmp-1472640125.08-279832275816508/source
<fengsyringe.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r '[fengsyringe.com]'
failed: [fengsyringe.com](item=acme-challenge) => {"item": "acme-challenge", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [fengsyringe.com]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": "acme-challenge", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}]}

**Comment by matthew6688** [comment]
![debops cfg](https://cloud.githubusercontent.com/assets/19649680/18152539/1d08b4ae-7029-11e6-8258-897d928e594e.jpg)
![debops](https://cloud.githubusercontent.com/assets/19649680/18152540/1d221520-7029-11e6-9578-6ccfc92f3ed8.jpg)

I have do as in the konwn issues as per the screenshot above.

Now when i debops wordpress -u root

it show below error:

TASK [debops.php : Install PHP packages] ***************************************
failed: [fengsyringe.com](item=[u'php5-cli', u'php5-fpm', u'php5', u'php5-curl', u'php5-gd', u'php5-mcrypt', u'php5-mysql', u'php5-curl', u'php5-dev', u'php-redis']) => {"failed": true, "item": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "msg": "No package matching 'php-redis' is available"}

NO MORE HOSTS LEFT *************************************************************

**Comment by carlalexander** [comment]
Yes, this is a [known issue](https://github.com/carlalexander/debops-wordpress/issues/90). Unfortunately, with the release of Xenial, I'm phasing out Trusty support slowly.

**Comment by matthew6688** [comment]
Thank you for your reply.

So, this known issue is solved in Xenial or not?  Or this is the issue go with Mac system. it will still exist in Xenial.

I would love to try on Xenial server.   Should i still go with the 3 command, or need to remove hhvm, and remove varnish, and reinstall varinish like you did?

I paste more details below:

TASK [debops.php : Install PHP packages] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.php/tasks/main.yml:6
<fengsyringe.com> ESTABLISH SSH CONNECTION FOR USER: root
<fengsyringe.com> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r fengsyringe.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1472695923.44-134613370294835`" && echo ansible-tmp-1472695923.44-134613370294835="`echo $HOME/.ansible/tmp/ansible-tmp-1472695923.44-134613370294835`" ) && sleep 0'"'"''
<fengsyringe.com> PUT /var/folders/3k/qjrv5lss4gbglbwvhchkncz00000gn/T/tmpq20VT7 TO /root/.ansible/tmp/ansible-tmp-1472695923.44-134613370294835/apt
<fengsyringe.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r '[fengsyringe.com]'
<fengsyringe.com> ESTABLISH SSH CONNECTION FOR USER: root
<fengsyringe.com> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r -tt fengsyringe.com '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1472695923.44-134613370294835/apt; rm -rf "/root/.ansible/tmp/ansible-tmp-1472695923.44-134613370294835/" > /dev/null 2>&1 && sleep 0'"'"''
failed: [fengsyringe.com](item=[u'php5-cli', u'php5-fpm', u'php5', u'php5-curl', u'php5-gd', u'php5-mcrypt', u'php5-mysql', u'php5-curl', u'php5-dev', u'php-redis']) => {"failed": true, "invocation": {"module_args": {"allow_unauthenticated": false, "autoremove": false, "cache_valid_time": null, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": false, "name": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "only_upgrade": false, "package": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "purge": false, "state": "present", "update_cache": false, "upgrade": null}, "module_name": "apt"}, "item": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis"], "msg": "No package matching 'php-redis' is available"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/ringse/debops-wordpress/playbooks/wordpress.retry

**Comment by carlalexander** [comment]
This issue doesn't happen on Xenial. You need to run the three commands in the readme. But it's not 100% stable yet, I'm in transition sorry. I probably won't be able to finish until end of September.   For now, you can refer to the discussion [here](https://github.com/carlalexander/debops-wordpress/issues/89)

**Comment by matthew6688** [comment]
TASK [debops.mariadb : Create databases] ***************************************
task path: /Users/ringse/Library/Application Support/debops/debops-playbooks/roles/debops.mariadb/tasks/manage_contents.yml:12
<fengclass> ESTABLISH SSH CONNECTION FOR USER: None
<fengclass> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/ringse/.ansible/cp/ansible-ssh-%h-%p-%r fengclass '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1473816567.87-4496983974911`" && echo ansible-tmp-1473816567.87-4496983974911="`echo $HOME/.ansible/tmp/ansible-tmp-1473816567.87-4496983974911`" ) && sleep 0'"'"''
failed: [fengclass.cn](item={u'name': u'wordpress'}) => {"item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [fengclass.cn]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"name": "wordpress"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}

**Comment by carlalexander** [comment]
Is mariadb on a different server? You shouldn't be using ssh I believe.

**Comment by matthew6688** [comment]
it is on the same server

**Comment by carlalexander** [comment]
I've tagged a new version for Xenial support earlier today. I don't plan on supporting 14.04 anymore.
